import { test, expect } from '@playwright/test'
const deal='/deals/33333333-3333-4333-8333-333333333333'
const jwt=[{alg:'HS256',typ:'JWT'},{sub:'11111111-1111-4111-8111-111111111111',exp:4102444800,iat:1700000000,role:'authenticated'},'fixture'].map(x=>typeof x==='string'?x:Buffer.from(JSON.stringify(x)).toString('base64url')).join('.')
test.beforeEach(async({context,request})=>{
 await context.route('**/*',route=>{const host=new URL(route.request().url()).hostname;return ['127.0.0.1','localhost'].includes(host)?route.continue():route.abort()})
 await request.post('http://127.0.0.1:55440/__reset')
 const session={access_token:jwt,refresh_token:'local-fixture-refresh',expires_at:4102444800,expires_in:3600,token_type:'bearer',user:{id:'11111111-1111-4111-8111-111111111111',role:'authenticated',email:'local@example.test'}}
 await context.addCookies([{name:'sb-127-auth-token',value:'base64-'+Buffer.from(JSON.stringify(session)).toString('base64url'),domain:'127.0.0.1',path:'/'}])
})
test('lost successful price-save response restores the same revision after reload without storing form data',async({page,request})=>{
 await page.goto(deal+'/quote-builder');const source='66666666-6666-4666-8666-666666666666';await page.locator(`[data-quote-id="${source}"]`).getByRole('button',{name:'価格を改訂して確認',exact:true}).click();const dialog=page.getByRole('dialog',{name:'価格改訂の確認',exact:true})
 await dialog.getByLabel('消費税率（%・0も明示）',{exact:true}).fill('10');await dialog.getByLabel('確認した取得元・根拠',{exact:true}).fill('Synthetic reload reference');await dialog.getByLabel('基準日時（タイムゾーン付ISO）',{exact:true}).fill('2026-09-30T00:00:00Z');await dialog.getByLabel('レート・根拠・基準日時を確認しました',{exact:true}).check()
 for(const name of ['版代','色指定費','中国国内送料','国際送料','その他費用']){await dialog.getByLabel(name+'の総額',{exact:true}).fill('0');await dialog.getByLabel(name+'を確認',{exact:true}).check()}
 await dialog.getByRole('button',{name:'価格・費目を確認',exact:true}).click();await expect(dialog).toContainText('DB確認済み')
 let resolve!:()=>void;const lost=new Promise<void>(r=>resolve=r)
 await page.route('**/*',async route=>{if(route.request().method()==='POST'&&route.request().headers()['next-action']){await route.fetch();await route.abort('failed');resolve()}else await route.fallback()})
 await dialog.getByRole('button',{name:'この内容で新しい価格版を保存',exact:true}).click();await lost;await page.unroute('**/*')
 const key=`baoflow-request:v1:11111111-1111-4111-8111-111111111111:pricing/${deal.split('/').pop()}/${source}`
 const pending=await page.evaluate(k=>JSON.parse(sessionStorage.getItem(k)!),key);expect(Object.keys(pending).sort()).toEqual(['id','signature'])
 await page.reload();await page.locator(`[data-quote-id="${source}"]`).getByRole('button',{name:'価格を改訂して確認',exact:true}).click();await expect(page.getByRole('dialog',{name:'価格改訂の確認',exact:true})).toContainText('前回の価格版を保存済みです')
 const state=await(await request.get('http://127.0.0.1:55440/__state')).json();expect(state.deal_quotes).toHaveLength(2);expect(state.quote_pricing_requests).toHaveLength(1)
})
test('manual FX and every cost must be confirmed; selling unit preview saves a separate price version once',async({page,request})=>{
 const base=(await(await request.get('http://127.0.0.1:55440/__state')).json()).deal_quotes[0]
 await page.goto(deal+'/quote-builder');await page.getByRole('button',{name:'価格を改訂して確認',exact:true}).click();const dialog=page.getByRole('dialog',{name:'価格改訂の確認',exact:true})
 await expect(dialog.getByRole('button',{name:'価格・費目を確認',exact:true})).toBeDisabled()
 await dialog.getByRole('combobox',{name:'入力する価格',exact:true}).selectOption('selling_price');await dialog.getByLabel('税抜売単価（円・整数）',{exact:true}).fill('37');await dialog.getByLabel('消費税率（%・0も明示）',{exact:true}).fill('10')
 await dialog.getByLabel('確認した取得元・根拠',{exact:true}).fill('Synthetic manually confirmed reference');await dialog.getByLabel('基準日時（タイムゾーン付ISO）',{exact:true}).fill('2026-09-30T00:00:00Z');await dialog.getByLabel('レート・根拠・基準日時を確認しました',{exact:true}).check()
 for(const name of ['版代','色指定費','中国国内送料','国際送料','その他費用']){await dialog.getByLabel(name+'の総額',{exact:true}).fill(name==='国際送料'?'20':'0');await dialog.getByLabel(name+'を確認',{exact:true}).check()}
 await expect(dialog).toContainText('税込 ¥40,700');await dialog.getByRole('button',{name:'価格・費目を確認',exact:true}).click();await expect(dialog).toContainText('DB確認済み')
 await dialog.getByLabel('税抜売単価（円・整数）',{exact:true}).fill('38');await expect(dialog.getByRole('button',{name:'この内容で新しい価格版を保存',exact:true})).toHaveCount(0);await dialog.getByLabel('税抜売単価（円・整数）',{exact:true}).fill('37');await dialog.getByRole('button',{name:'価格・費目を確認',exact:true}).click();await expect(dialog).toContainText('DB確認済み')
 await page.setViewportSize({width:390,height:900});await dialog.getByRole('button',{name:'この内容で新しい価格版を保存',exact:true}).scrollIntoViewIfNeeded();expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await expect(dialog.getByRole('button',{name:'この内容で新しい価格版を保存',exact:true})).toBeInViewport();await page.screenshot({path:'tmp/quote-stage3/pricing-confirm-390.png'})
 await request.post('http://127.0.0.1:55440/__fail',{data:{table:'save_quote_pricing_v2'}});await dialog.getByRole('button',{name:'この内容で新しい価格版を保存',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('保存結果を確認できません');await expect(dialog.getByLabel('税抜売単価（円・整数）',{exact:true})).toBeDisabled()
 await dialog.getByRole('button',{name:'この内容で新しい価格版を保存',exact:true}).click();await expect(dialog).not.toBeVisible()
 const after=(await(await request.get('http://127.0.0.1:55440/__state')).json());expect(after.deal_quotes).toHaveLength(2);expect(after.deal_quotes[0]).toEqual(base);expect(after.deal_quotes[1].selling_price_jpy).toBe(37);expect(after.deal_quotes[1].sample_cost_usd).toBe(0);expect(after.quote_pricing_requests).toHaveLength(1)
 await page.reload();await expect(page.getByRole('button',{name:'価格を改訂して確認',exact:true})).toHaveCount(2)
})

test('sea base calculator is ticket scoped and never changes confirmed pricing costs',async({page,request})=>{
 await page.setViewportSize({width:390,height:844});await page.goto(deal+'/quote-builder');await page.getByRole('button',{name:'価格を改訂して確認',exact:true}).click();const dialog=page.getByRole('dialog',{name:'価格改訂の確認',exact:true});const cost=await dialog.getByLabel('国際送料の総額',{exact:true}).inputValue()
 await dialog.getByText('海源・海運の基本送料を確認',{exact:true}).click();await dialog.getByLabel('1票の実重量（kg）',{exact:true}).fill('2');await dialog.getByLabel('1票の容積（CBM）',{exact:true}).fill('0.02');await expect(dialog.getByRole('status',{name:'海運基本送料の計算結果',exact:true})).toContainText('420 CNY');await expect(dialog.getByRole('status',{name:'海運基本送料の計算結果',exact:true})).toContainText('送料総額は未確定');await dialog.getByLabel('票全体の区分',{exact:true}).selectOption('sensitive');await expect(dialog.getByRole('status',{name:'海運基本送料の計算結果',exact:true})).toContainText('504 CNY');await expect(dialog.getByLabel('国際送料の総額',{exact:true})).toHaveValue(cost);await expect(dialog.getByRole('button',{name:'価格・費目を確認',exact:true})).toBeDisabled();await page.screenshot({path:'artifacts/haiyuan-base-390.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const state=await(await request.get('http://127.0.0.1:55440/__state')).json();expect(state.quote_pricing_requests||[]).toHaveLength(0)
})

test('official Kaigen fee boundaries stay separate and legacy specifications remain read-only',async({page,request})=>{
 await page.setViewportSize({width:390,height:844});await page.goto(deal+'/quote-builder');await page.getByRole('button',{name:'価格を改訂して確認',exact:true}).click();const dialog=page.getByRole('dialog',{name:'価格改訂の確認',exact:true});const cost=await dialog.getByLabel('国際送料の総額',{exact:true}).inputValue();await dialog.getByText('海源・通関と食品届出の手数料を確認',{exact:true}).click();await dialog.getByLabel('1件のインボイス品目数',{exact:true}).fill('31');await dialog.getByLabel('納税の支払方法',{exact:true}).selectOption('advance');await expect(dialog.getByRole('status',{name:'DQ手数料の計算結果'})).toContainText('¥4,000');await expect(dialog.getByRole('status',{name:'DQ手数料の計算結果'})).toContainText('¥1,400');await dialog.getByLabel('納税の支払方法',{exact:true}).selectOption('realtime');await expect(dialog.getByRole('status',{name:'DQ手数料の計算結果'})).toContainText('¥0');await dialog.getByLabel('海源作成・1工場の品目数',{exact:true}).fill('10');await expect(dialog.getByRole('status',{name:'食品届出手数料の計算結果'})).toContainText('¥19,000');await expect(dialog).toContainText('消費税扱い未確認');await expect(dialog.getByLabel('国際送料の総額',{exact:true})).toHaveValue(cost);await dialog.locator('details').filter({hasText:'海源・通関と食品届出の手数料を確認'}).screenshot({path:'artifacts/kaigen-fees-390.png'});await dialog.getByRole('button',{name:'閉じる',exact:true}).click()
 const rest='http://127.0.0.1:55440/rest/v1/';await request.patch(rest+'deal_quotes?id=eq.66666666-6666-4666-8666-666666666666',{data:{variant_id:null,status:'approved'}});await request.post(rest+'deal_specifications',{data:{deal_id:deal.split('/').pop(),product_name:'Synthetic legacy pouch',width_mm:100,height_mm:150,depth_mm:30,material_category:'PET',printing_method:'Synthetic method',print_colors:'2 colors',processing_list:['Synthetic process']}});const before=await(await request.get('http://127.0.0.1:55440/__state')).json();await page.goto(deal);await page.getByText('旧仕様・見積との対応を確認',{exact:true}).click();await expect(page.getByText('Synthetic legacy pouch',{exact:false})).toBeVisible();await expect(page.getByText('出自と採用見積との対応は未確認です。',{exact:false})).toBeVisible();await page.locator('details').filter({has:page.getByText('旧仕様・見積との対応を確認',{exact:true})}).screenshot({path:'artifacts/legacy-specification-390.png'});const after=await(await request.get('http://127.0.0.1:55440/__state')).json();expect(after.deal_quotes).toEqual(before.deal_quotes);expect(after.deal_products).toEqual(before.deal_products)
})

test('official tracking link uses user navigation and manual records, without automatic shipment update',async({page,request})=>{const order='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',rest='http://127.0.0.1:55440/rest/v1/';await request.post(rest+'factory_purchase_orders',{data:{id:order,deal_id:deal.split('/').pop(),order_no:'LOCAL-TRACK',quantity:1,status:'ordered',snapshot:{}}});await request.post(rest+'fixture_shipment_context',{data:{actor:'staff',order:{id:order,deal_id:deal.split('/').pop(),quantity:1},plans:[],deal_status:'in_production',qc_available_quantity:0,ship_ready:false,options:{partners:[],actors:[]}}});const response=await page.goto(deal+'/shipping');expect(response?.status()).toBe(200);await page.getByText('海源の公式追跡・実績更新',{exact:true}).click();await expect(page.getByRole('link',{name:'海源の公式追跡画面を開く'})).toHaveAttribute('href','https://japan-kaigen.com/tsuiseki/');await expect(page.getByText('追跡の自動同期は未接続です。',{exact:false})).toBeVisible();const state=await(await request.get('http://127.0.0.1:55440/__state')).json();expect(state.shipment_workflow_requests||[]).toHaveLength(0)})

test('archive from current case list excludes analytics and restores via normal archive UI without deleting quotes',async({page,request})=>{await page.setViewportSize({width:390,height:844});await request.patch('http://127.0.0.1:55440/rest/v1/deal_quotes',{data:{status:'approved',cost_ratio:0.5}});const before=await(await request.get('http://127.0.0.1:55440/__state')).json();await page.goto('/analytics');await expect(page.getByText('¥39,600',{exact:true}).first()).toBeVisible();await page.goto('/deals?scope=all&selected='+deal.split('/').pop());await page.getByRole('button',{name:'アーカイブ・復元可能',exact:true}).click();const modal=page.getByRole('dialog',{name:'案件をアーカイブ'});await modal.getByLabel('アーカイブ理由の補足').fill('Synthetic old-data exclusion; reversible');await modal.getByRole('button',{name:'アーカイブする',exact:true}).click();await expect(modal).not.toBeVisible();await expect(page.getByRole('table',{name:'案件一覧'})).not.toContainText('LOCAL-001');await page.goto('/analytics');await expect(page.getByText('¥0',{exact:true}).first()).toBeVisible();await page.goto('/archive');await expect(page.getByText('LOCAL-001',{exact:true})).toBeVisible();await page.screenshot({path:'artifacts/legacy-archive-390.png',fullPage:true});page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'解除',exact:true}).click();await page.goto('/deals?scope=all');await expect(page.getByRole('table',{name:'案件一覧'})).toContainText('LOCAL-001');await page.goto('/analytics');await expect(page.getByText('¥39,600',{exact:true}).first()).toBeVisible();const after=await(await request.get('http://127.0.0.1:55440/__state')).json();expect(after.deal_quotes).toEqual(before.deal_quotes);expect(after.clients).toEqual(before.clients);expect(after.factories).toEqual(before.factories);expect(after.deals[0].archived_at).toBeNull()})
