import { test, expect } from '@playwright/test'
const fixture='http://127.0.0.1:55440'
const deal='/deals/33333333-3333-4333-8333-333333333333'
const userId='11111111-1111-4111-8111-111111111111'
const factories=['77777777-7777-4777-8777-777777777771','77777777-7777-4777-8777-777777777772']
const jwt=[{alg:'HS256',typ:'JWT'},{sub:userId,exp:4102444800,iat:1700000000,role:'authenticated'},'fixture'].map(x=>typeof x==='string'?x:Buffer.from(JSON.stringify(x)).toString('base64url')).join('.')
test.beforeEach(async({context,request})=>{
 await context.route('**/*',route=>['127.0.0.1','localhost'].includes(new URL(route.request().url()).hostname)?route.continue():route.abort())
 await request.post(fixture+'/__reset')
 await request.post(fixture+'/rest/v1/factories',{data:factories.map((id,i)=>({id,factory_name:`検証工場${i+1}`,basic_info_completed:true,contact_email:`factory${i+1}@example.test`}))})
 const session={access_token:jwt,refresh_token:'local-fixture-refresh',expires_at:4102444800,expires_in:3600,token_type:'bearer',user:{id:userId,role:'authenticated',email:'local@example.test'}}
 await context.addCookies([{name:'sb-127-auth-token',value:'base64-'+Buffer.from(JSON.stringify(session)).toString('base64url'),domain:'127.0.0.1',path:'/'}])
})
test('RFQ retry creates one complete request and copyable links without automatically sending email',async({page,request})=>{
 await page.goto(deal+'?step=3')
 await page.getByRole('button',{name:'見積依頼(RFQ)をつくる',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'見積依頼を作成',exact:true})
 await dialog.getByLabel('検証工場1',{exact:false}).check()
 await dialog.getByLabel('検証工場2',{exact:false}).check()
 await request.post(fixture+'/__fail',{data:{table:'rfq_form'}})
 await dialog.getByRole('button',{name:'RFQ を作成',exact:true}).click()
 await expect(dialog.getByRole('alert')).toContainText('同じ内容で再試行')
 let state=await (await request.get(fixture+'/__state')).json()
 expect(state.rfq_requests).toHaveLength(0)
 await dialog.getByRole('button',{name:'RFQ を作成',exact:true}).click()
 await expect(page.getByRole('dialog',{name:'見積依頼を作成しました',exact:true})).toBeVisible()
 const done=page.getByRole('dialog',{name:'見積依頼を作成しました',exact:true})
 await expect(done).toContainText('メールはまだ送信していません')
 await expect(done.getByRole('button',{name:'工場にメールを送信する',exact:true})).toHaveCount(2)
 const urls=await done.locator('input[readonly]').evaluateAll(inputs=>inputs.map(input=>(input as HTMLInputElement).value))
 expect(urls).toHaveLength(2)
 for(const url of urls)expect(url).toMatch(/^http:\/\/127\.0\.0\.1:3100\/external\/[0-9a-f]{64}$/)
 state=await (await request.get(fixture+'/__state')).json()
 expect(state.rfq_requests).toHaveLength(1);expect(state.rfq_factory_invitations).toHaveLength(2);expect(state.external_forms).toHaveLength(2)
 expect(state.rfq_creation_requests).toHaveLength(1)
 expect(state.rfq_factory_invitations.every((i:{invitation_sent_at:unknown})=>i.invitation_sent_at===null)).toBe(true)
 await page.goto(urls[0])
 await expect(page.getByRole('button',{name:'Submit quotation / 提交报价',exact:true})).toBeVisible()
 await expect(page.getByText('Your contact',{exact:false})).toBeVisible()
 // Email buttons are deliberately not clicked: no real provider calls are authorized.
})

test('unregistered factory submits saved answer, staff explicitly selects its registered factory and imports once',async({page,request})=>{
 const response=await page.goto(deal+'?step=3');expect(response?.status()).toBe(200)
 await page.getByRole('button',{name:'見積依頼(RFQ)をつくる',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'見積依頼を作成',exact:true})
 await dialog.getByLabel('未登録工場名',{exact:true}).fill('未登録検証工場')
 await dialog.getByLabel('未登録工場メール (任意)',{exact:true}).fill('invalid-email')
 await dialog.getByRole('button',{name:'RFQ を作成',exact:true}).click()
 await expect(dialog.getByRole('alert')).toContainText('有効なメールアドレス')
 expect((await(await request.get(fixture+'/__state')).json()).rfq_requests).toHaveLength(0)
 await dialog.getByLabel('未登録工場メール (任意)',{exact:true}).fill('pending@example.test')
 await dialog.getByRole('button',{name:'RFQ を作成',exact:true}).click()
 const done=page.getByRole('dialog',{name:'見積依頼を作成しました',exact:true})
 await expect(done).toBeVisible();const url=await done.locator('input[readonly]').inputValue()
 let state=await(await request.get(fixture+'/__state')).json();expect(state.rfq_factory_invitations[0].factory_id).toBeNull()
 await page.goto(url)
 for(const [label,value] of [['Unit USD / 单价','0.1'],['MOQ','1000'],['PCS/CTN','100'],['Lead days / 交期','15'],['Carton W cm','30'],['Carton H cm','40'],['Carton D cm','30'],['G.W kg','10']])await page.getByLabel(label,{exact:true}).fill(value)
 await page.getByRole('button',{name:'Submit quotation / 提交报价',exact:true}).click();await expect(page.getByText('Thank you for your quotation.',{exact:false})).toBeVisible()
 state=await(await request.get(fixture+'/__state')).json();expect(state.deal_quotes.filter((q:{source_type:string})=>q.source_type==='rfq_response')).toHaveLength(0)
 await page.goto(deal+'?step=3')
 await expect(page.getByText('未登録工場の回答は自動で紐付けません。',{exact:false})).toBeVisible()
 const select=page.getByLabel('未登録検証工場 の登録工場',{exact:true})
 await expect(select).toHaveValue('');await expect(page.getByRole('button',{name:'この工場の回答として取り込む',exact:true})).toBeDisabled()
 await select.selectOption(factories[0]);await page.getByRole('button',{name:'この工場の回答として取り込む',exact:true}).click()
 await expect(page.getByText('保存済み回答を見積に取り込みました。',{exact:false})).toBeVisible()
 await page.reload();await page.getByRole('button',{name:'未登録工場の回答を確認',exact:true}).click()
 await expect(page.getByRole('button',{name:'この工場の回答として取り込む',exact:true})).toHaveCount(0)
 state=await(await request.get(fixture+'/__state')).json();const quotes=state.deal_quotes.filter((q:{source_type:string})=>q.source_type==='rfq_response')
 expect(quotes).toHaveLength(1);expect(quotes[0].factory_id).toBe(factories[0]);expect(quotes[0].quantity).toBe(1000);expect(state.rfq_answer_imports).toHaveLength(1)
})

test('legacy adopted quote remains readable, blocks speculative factory order and can reissue a document without changing its old record',async({page,request})=>{
 await request.patch(fixture+'/rest/v1/deal_quotes?id=eq.66666666-6666-4666-8666-666666666666',{data:{variant_id:null,spec_id:null,status:'approved',factory_id:factories[0]}})
 await request.delete(fixture+'/rest/v1/deal_products')
 const old={id:'88888888-8888-4888-8888-888888888888',deal_id:deal.split('/').pop(),document_type:'quotation',document_number:'QUO-LEGACY-001',version:1,issued_at:'2026-09-01T00:00:00Z',metadata:{notes:'Synthetic old note'}}
 await request.post(fixture+'/rest/v1/documents',{data:old})
 const response=await page.goto(deal+'?step=10');expect(response?.status()).toBe(200)
 await expect(page.getByText('過去の採用見積には商品・仕様の紐付けがありません。',{exact:false})).toBeVisible()
 await expect(page.getByRole('button',{name:'この内容で工場に発注する',exact:true})).toBeDisabled()
 const docResponse=await page.goto(deal+'/documents');expect(docResponse?.status()).toBe(200)
 await page.getByRole('button',{name:/QUO-LEGACY-001.*を表示/}).click()
 await expect(page.getByRole('alert').filter({hasText:'現在の案件情報を参考表示'})).toBeVisible()
 await page.getByRole('button',{name:'新しい帳票を作成する',exact:true}).click()
 await page.getByRole('button',{name:'この内容で発行する',exact:true}).click()
 await expect(page.getByText('発行履歴 (2)',{exact:true})).toBeVisible()
 const state=await(await request.get(fixture+'/__state')).json()
 expect(state.documents.find((d:{id:string})=>d.id===old.id).metadata).toEqual(old.metadata)
 expect(state.deal_quotes[0].variant_id).toBeNull();expect(state.deal_quotes).toHaveLength(1)
})
