'use server'
import {createClient} from '@/lib/supabase/server'
import {requireSalesAccess} from './deal-access'
import {revalidatePath} from 'next/cache'
import {createHash} from 'node:crypto'
import {deliveryNotePDF} from '@/lib/pdf/delivery-note'
import {milestoneNames,type ShipmentContext,type DeliverySnapshot,type Milestone} from '@/lib/shipping/types'
export async function getShipmentWorkflow(orderId:string):Promise<ShipmentContext|null>{const db=await createClient(),{data,error}=await db.rpc('shipment_context',{p_order_id:orderId});return error||!data?null:data as ShipmentContext}
export async function shipmentCommand(requestId:string,orderId:string,operation:string,input:Record<string,unknown>){const db=await createClient(),{data,error}=await db.rpc('shipment_command',{p_request_id:requestId,p_order_id:orderId,p_operation:operation,p_input:input});if(error||!data)return {error:error?.message||'保存を確認できません。同じ内容で再試行してください'};revalidatePath('/portal/shipments');revalidatePath('/logistics/shipments');revalidatePath(`/factory/orders/${orderId}`);revalidatePath(`/deals/${(await getShipmentWorkflow(orderId))?.order.deal_id}/shipping`);return {result:data as Record<string,unknown>}}
async function mailData(planId:string,eventKey:string){
 const db=await createClient(),denied=await requireSalesAccess(db);if(denied)return {error:denied};const {data:p,error}=await db.from('shipment_plans').select('*').eq('id',planId).single();if(error||!p)return {error:'配送版を確認できません'}
 const doc=eventKey==='delivery'?await db.from('shipment_delivery_documents').select('*').eq('plan_id',planId).single():null,event=eventKey!=='delivery'?await db.from('shipment_milestones').select('*').eq('id',eventKey).eq('plan_id',planId).single():null
 if(doc?.error||event?.error)return {error:'通知対象を確認できません'}
 const destination=event?.data?.kind==='factory_dispatched'?await db.from('logistics_partners').select('contact_email').eq('id',p.partner_id).single():await db.from('clients').select('email').eq('id',p.client_id).single()
 const from=process.env.RFQ_MAIL_FROM,to=(destination.data?('contact_email' in destination.data?destination.data.contact_email:destination.data.email):null),base=process.env.NEXT_PUBLIC_APP_URL
 if(destination.error||!from||!to||!base||!process.env.RESEND_API_KEY)return {error:'登録宛先・送信元・アプリURL・メール設定を確認してください。未送信です'}
 const url=new URL(event?.data?.kind==='factory_dispatched'?`/logistics/shipments/${p.order_id}`:`/portal/shipments/${p.order_id}`,base);if(url.protocol!=='https:'&&!['127.0.0.1','localhost'].includes(url.hostname))return {error:'安全なURLを確認してください'}
 const pdf=doc?.data?await deliveryNotePDF({...doc.data.snapshot,number:doc.data.document_number} as DeliverySnapshot):null
 const subject=doc?.data?`納品書 ${doc.data.document_number}`:`配送更新：${milestoneNames[event!.data.kind as Milestone]}`
 const body=doc?.data?`${p.snapshot.customer_name} 御中\n${p.snapshot.item_name} ${p.quantity}個 / 顧客受領日 ${doc.data.snapshot.received_on}\n納品書を添付します。\n${url}`:`${p.snapshot.item_name} ${p.quantity}個\n${milestoneNames[event!.data.kind as Milestone]}\n発生時刻 ${event!.data.occurred_at}\n追跡番号 ${event!.data.tracking_number}\n手動確認情報です。追跡APIは未連携です。\n${url}`
 const payload={from,to,subject,body,attachment:doc?.data?`${doc.data.document_number}.pdf`:null,pdf_sha256:pdf?createHash('sha256').update(pdf).digest('hex'):null},receipt=await db.from('shipment_mail_receipts').select('status').eq('event_key',`${planId}:${eventKey}`).maybeSingle();if(receipt.error)return {error:'送信履歴を確認できません'}
 return {payload,pdf,status:receipt.data?.status||null,fingerprint:createHash('sha256').update(JSON.stringify(payload)).digest('hex')}
}
export async function previewShipmentMail(planId:string,eventKey:string){const r=await mailData(planId,eventKey);return r.error?{error:r.error}:{preview:{...r.payload!,fingerprint:r.fingerprint!,status:r.status}}}
export async function sendShipmentMail(planId:string,eventKey:string,fingerprint:string){const r=await mailData(planId,eventKey);if(r.error)return {error:r.error};if(r.fingerprint!==fingerprint)return {error:'宛先・内容が変更されています。再確認してください'};if(r.status)return {status:r.status,error:r.status==='accepted'?undefined:'予約・履歴済みのため再送停止。結果を確認してください'};const db=await createClient(),claim=await db.rpc('claim_shipment_email',{p_plan_id:planId,p_event_key:eventKey,p_payload:r.payload});if(claim.error||!claim.data)return {error:'送信予約を確認できません。再送停止'};if(!claim.data.claimed)return {status:claim.data.status,error:claim.data.status==='accepted'?undefined:'送信予約済みのため再送停止'};let status='unknown',providerId:string|null=null;try{const p=r.payload!,response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':`shipment/${planId}/${eventKey}`},body:JSON.stringify({from:p.from,to:[p.to],subject:p.subject,text:p.body,...(r.pdf?{attachments:[{filename:p.attachment,content:Buffer.from(r.pdf).toString('base64')}]}:{})})});if(!response.ok)status='rejected';else{const b=await response.json();if(typeof b.id==='string'&&b.id){status='accepted';providerId=b.id}}}catch{}const finished=await db.rpc('finish_shipment_email',{p_attempt_id:claim.data.attempt_id,p_status:status,p_provider_id:providerId});return finished.error||!finished.data?{status:'unknown',error:'結果保存未確認。重複防止のため再送停止'}:{status,error:status==='accepted'?undefined:'受付未確認。再送せず履歴を確認してください'}}
