import test from 'node:test'
import assert from 'node:assert/strict'
import {PGlite} from '@electric-sql/pglite'
import {readFile} from 'node:fs/promises'
import {randomUUID as uuid} from 'node:crypto'
const staff=uuid(),clientUser=uuid(),foreignUser=uuid(),factoryUser=uuid(),logistics=uuid(),otherLogistics=uuid(),client=uuid(),foreign=uuid(),factory=uuid(),deal=uuid(),rfq=uuid()
async function setup(){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.actor',true),'')::uuid$$;
 create table profiles(id uuid primary key,role text,client_id uuid,factory_id uuid,display_name text);insert into profiles values('${staff}','sales',null,null,'staff'),('${clientUser}','client','${client}',null,'client'),('${foreignUser}','client','${foreign}',null,'foreign'),('${factoryUser}','factory',null,'${factory}','factory'),('${logistics}','logistics',null,null,'logistics'),('${otherLogistics}','logistics',null,null,'other');
 create function is_staff() returns boolean language sql as $$select coalesce((select role in('sales','admin') from profiles where id=auth.uid()),false)$$;
 create table clients(id uuid primary key,company_name text);insert into clients values('${client}','Synthetic client'),('${foreign}','Foreign client');create table factories(id uuid primary key,factory_name text);insert into factories values('${factory}','Synthetic factory');
 create table deals(id uuid primary key,client_id uuid,archived_at timestamptz,deal_code text);insert into deals values('${deal}','${client}',null,'SYN-CHAT');
 create table rfq_requests(id uuid,deal_id uuid);insert into rfq_requests values('${rfq}','${deal}');create table rfq_factory_invitations(rfq_id uuid,factory_id uuid);insert into rfq_factory_invitations values('${rfq}','${factory}');create table factory_purchase_orders(deal_id uuid,factory_id uuid,status text);create table sample_rounds(deal_id uuid,factory_id uuid);create table shipment_plans(deal_id uuid,logistics_actor_id uuid);insert into shipment_plans values('${deal}','${logistics}');
 create type chat_room_type as enum('client_sales','sales_factory','internal');create table chat_rooms(id uuid primary key default gen_random_uuid(),deal_id uuid,room_type chat_room_type,created_at timestamptz default now());create table chat_messages(id uuid primary key default gen_random_uuid(),room_id uuid references chat_rooms(id),user_id uuid,content_original text,original_language text,source text,created_at timestamptz default now());
 create table sample_invoices(id uuid primary key default gen_random_uuid(),deal_id uuid,document_number text,status text,previous_invoice_id uuid,cancellation_reason text,snapshot jsonb,created_at timestamptz default now());
 grant usage on schema public,auth to authenticated;grant execute on function auth.uid(),is_staff() to authenticated;grant all on chat_rooms,chat_messages to public;
 set test.actor='${staff}';`);await db.exec(await readFile('supabase/migrations/20261001200000_case_chat_and_client_samples_v1.sql','utf8'));return db}
async function actor(db:PGlite,id:string){await db.query("select set_config('test.actor',$1,false)",[id])}
const query=async(db:PGlite,sql:string,args:unknown[]=[])=> (await db.query<any>(sql,args)).rows[0]?.r
const open=async(db:PGlite,role:string,id:string)=>query(db,'select open_case_chat($1,$2,$3) r',[deal,role,id])
const send=async(db:PGlite,room:string,text:string,key=uuid())=>query(db,'select send_case_chat($1,$2,$3) r',[key,room,text])
test('explicit rooms isolate client/factory/assigned logistics, revoke inherited direct writes; unread and retry are bounded',async()=>{const db=await setup();try{
 const c=await open(db,'client',client),f=await open(db,'factory',factory),l=await open(db,'logistics',logistics);assert.equal(await open(db,'client',client),c);await assert.rejects(open(db,'logistics',otherLogistics));
 const key=uuid();const saved=await send(db,c,'Synthetic <b>plain text</b>',key);assert.deepEqual(await send(db,c,'Synthetic <b>plain text</b>',key),saved);await assert.rejects(send(db,c,'changed',key));await send(db,f,'Factory separate');await send(db,l,'Logistics separate');
 const legacy=uuid();await db.query("insert into chat_rooms(id,deal_id,room_type) values($1,$2,'internal')",[legacy,deal]);
 await actor(db,clientUser);const rooms=await query(db,'select list_case_chats() r');assert.equal(rooms.length,1);assert.equal(rooms[0].id,c);assert.equal(rooms[0].unread,1);assert.equal((await query(db,'select read_case_chat($1) r',[c])).messages[0].content,'Synthetic <b>plain text</b>');for(const id of [f,l,legacy])await assert.rejects(query(db,'select read_case_chat($1) r',[id]));await assert.rejects(open(db,'client',client));
 await assert.rejects(db.query('select mark_case_chat_read($1,999)',[c]));await db.query('select mark_case_chat_read($1,$2)',[c,saved.sequence]);assert.equal((await query(db,'select list_case_chats() r'))[0].unread,0);await send(db,c,'Client reply');
 await db.exec('set role authenticated');assert.equal((await db.query('select * from chat_rooms')).rows.length,1);await assert.rejects(db.query("insert into chat_messages(room_id,content_original) values($1,'bypass')",[c]),/permission denied/);await assert.rejects(db.exec('truncate chat_messages'),/permission denied/);await db.exec('reset role');
 await actor(db,factoryUser);assert.equal((await query(db,'select list_case_chats() r'))[0].id,f);await actor(db,logistics);assert.equal((await query(db,'select list_case_chats() r'))[0].id,l);await actor(db,foreignUser);assert.deepEqual(await query(db,'select list_case_chats() r'),[]);
 await actor(db,clientUser);await db.query('update deals set client_id=$1 where id=$2',[foreign,deal]);await assert.rejects(send(db,c,'Former client'));assert.deepEqual(await query(db,'select list_case_chats() r'),[])
 }finally{await db.close()}})
test('sample invoices freeze own recipient; no legacy inference, raw cost pointer or staff cancellation notes',async()=>{const db=await setup();try{
 const snapshot={lines:[{cost_id:uuid(),quantity:4,customer_charge_jpy:'1500'}],total:'1650'};const id=uuid();await db.query("insert into sample_invoices(id,deal_id,document_number,status,cancellation_reason,snapshot) values($1,$2,'SYN-1','issued','Internal secret',$3)",[id,deal,JSON.stringify(snapshot)]);
 await actor(db,clientUser);let invoices=await query(db,'select client_sample_invoices() r');assert.equal(invoices.length,1);assert.equal(invoices[0].snapshot.client_id,client);assert.equal(invoices[0].snapshot.lines[0].cost_id,undefined);assert.equal(invoices[0].cancellation_reason,null);
 await db.query('update deals set client_id=$1 where id=$2',[foreign,deal]);assert.equal((await query(db,'select client_sample_invoices() r')).length,1);await actor(db,foreignUser);assert.deepEqual(await query(db,'select client_sample_invoices() r'),[]);await actor(db,factoryUser);await assert.rejects(query(db,'select client_sample_invoices() r'));
 await actor(db,staff);await db.query('update sample_invoices set client_id=null,snapshot=$1 where id=$2',[JSON.stringify(snapshot),id]);await actor(db,clientUser);assert.deepEqual(await query(db,'select client_sample_invoices() r'),[])
 }finally{await db.close()}})

test('latest history is bounded and older pages preserve strict sequence without overlap',async()=>{const db=await setup();try{const room=await open(db,'client',client);for(let i=0;i<105;i++)await send(db,room,`Synthetic sequence ${i}`);await actor(db,clientUser);const latest=await query(db,'select read_case_chat($1) r',[room]);assert.equal(latest.messages.length,100);assert.equal(latest.messages[0].sequence,6);assert.equal(latest.has_more,true);const older=await query(db,'select read_case_chat($1,$2) r',[room,6]);assert.equal(older.messages.length,5);assert.equal(older.has_more,false);await db.query('select mark_case_chat_read($1,105)',[room]);await db.query('select mark_case_chat_read($1,1)',[room]);assert.equal((await query(db,'select list_case_chats() r'))[0].unread,0)}finally{await db.close()}})
