import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {runInNewContext} from 'node:vm'
import ts from 'typescript'
import * as fx from '../src/lib/calc/fx-reference'
const q=()=>({id:'quote',status:'approved',quantity:2,total_billing_jpy:800,pricing_snapshot:{fx:{rate:'150',cny_jpy_rate:'20',reference:'ExchangeRate-API internal evidence must stay private',as_of:'2026-10-01T00:00:00.000000Z'},cost_lines:[{currency:'CNY'}]}})
function harness({available=true,rate=150,asOf='2026-10-01T00:00:00.000Z',manual=false}={}){
 let sent:any=null,fetches=0;const quote=q();if(manual)quote.pricing_snapshot.fx.reference='Private bank evidence not for customer'
 const rows:any={deals:[{id:'deal',deal_code:'SYN',client_id:'client'}],deal_quotes:[quote],deal_products:[],deal_product_variants:[],deal_specifications:[],deal_fees:[],documents:[],system_settings:[{}]}
 const db={auth:{getUser:async()=>({data:{user:{id:'actor'}}})},from:(table:string)=>{const x:any={select:()=>x,eq:()=>x,order:()=>x,like:()=>x,limit:()=>x,single:async()=>({data:rows[table][0],error:null}),then:(resolve:any)=>Promise.resolve({data:rows[table],error:null}).then(resolve)};return x},rpc:async(_name:string,args:any)=>{sent=args;return {data:{id:'doc',metadata:{...args.p_metadata,snapshot:args.p_snapshot}},error:null}}}
 const exports:any={};runInNewContext(ts.transpileModule(readFileSync('src/lib/actions/documents.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Date,console,require:(name:string)=>name.includes('fx-reference')?fx:name.includes('exchange-rate')?{pricingReferenceRates:async(fresh:boolean)=>{assert.equal(fresh,true);fetches++;return {usd:{success:available,rate,timestamp:asOf},cny:{success:available,rate:20,timestamp:asOf}}}}:name.includes('supabase/server')?{createClient:async()=>db}:name.includes('deal-access')?{requireSalesAccess:async()=>null}:name==='next/cache'?{revalidatePath:()=>{}}:(()=>{throw Error('Unexpected module '+name)})()})
 return {issue:(type='quotation')=>exports.issueDocument({request_id:'request',deal_id:'deal',document_type:type,metadata:{notes:'Synthetic agreed conditions',manual_fx:{rate:150,confirmed:true}}}),sent:()=>sent,fetches:()=>fetches}
}
test('fresh daily basis is fixed in document notes; only public source and no internal evidence',async()=>{const h=harness();assert.equal((await h.issue()).error,null);assert.equal(h.fetches(),1);const notes=h.sent().p_metadata.notes;assert.match(notes,/日次参考値 ExchangeRate-API/);assert.match(notes,/150 JPY\/USD/);assert.match(notes,/20 JPY\/CNY/);assert.match(notes,/2026-10-01T00:00:00/);assert.doesNotMatch(notes,/internal evidence/);assert.match(notes,/銀行決済用ではありません/)})
test('changed rate or latest source date and provider failure stop issuance before RPC',async()=>{for(const options of [{rate:151},{asOf:'2026-10-02T00:00:00Z'},{available:false}]){const h=harness(options);assert.ok((await h.issue()).error);assert.equal(h.sent(),null)}})
test('invoice retains agreed reference; manual evidence is redacted and never falsely called latest daily',async()=>{const old=harness({available:false});assert.equal((await old.issue('invoice')).error,null);assert.equal(old.fetches(),0);assert.match(old.sent().p_metadata.notes,/2026-10-01/);const manual=harness({manual:true});assert.equal((await manual.issue()).error,null);assert.equal(manual.fetches(),0);assert.match(manual.sent().p_metadata.notes,/手入力参考値/);assert.doesNotMatch(manual.sent().p_metadata.notes,/Private bank|ExchangeRate-API/)})
