import test from 'node:test'
import assert from 'node:assert/strict'
import {PGlite} from '@electric-sql/pglite'
import {readFile} from 'node:fs/promises'
const actor='00000000-0000-0000-0000-000000000001',order='00000000-0000-0000-0000-000000000002',plan='00000000-0000-0000-0000-000000000003',org='00000000-0000-0000-0000-000000000004',other='00000000-0000-0000-0000-000000000005'
test('creator history follows current role and organization; demoted staff cannot read prepared addresses',async()=>{const db=new PGlite();try{await db.exec(`create role anon;create role authenticated;create schema auth;create function auth.uid() returns uuid language sql as $$select '${actor}'::uuid$$;create table profiles(id uuid,role text,client_id uuid,factory_id uuid);insert into profiles values('${actor}','sales','${org}','${org}');create function is_staff() returns boolean language sql security definer as $$select role in('sales','admin') from profiles where id=auth.uid()$$;create table factory_purchase_orders(id uuid,factory_id uuid);insert into factory_purchase_orders values('${order}','${org}');create table shipment_plans(id uuid,order_id uuid,logistics_actor_id uuid,client_id uuid);insert into shipment_plans values('${plan}','${order}','${actor}','${org}');create table shipment_workflow_requests(created_by uuid,order_id uuid,operation text,payload jsonb);alter table shipment_workflow_requests enable row level security;create policy actor_request_read on shipment_workflow_requests for select to authenticated using(created_by=auth.uid());grant usage on schema public,auth to authenticated;grant select on shipment_workflow_requests to authenticated;insert into shipment_workflow_requests values('${actor}','${order}','prepare','{"address":"Synthetic sensitive address"}'),('${actor}','${order}','milestone','{"kind":"factory_dispatched","plan_id":"${plan}"}'),('${actor}','${order}','milestone','{"kind":"china_received","plan_id":"${plan}"}'),('${actor}','${order}','receive','{"plan_id":"${plan}"}');`);await db.exec(await readFile('supabase/migrations/20261001210000_shipment_request_role_scope.sql','utf8'));
 async function visible(role:string){await db.exec(`reset role;update profiles set role='${role}';set role authenticated;`);return (await db.query<{operation:string,payload:any}>('select operation,payload from shipment_workflow_requests')).rows}
 assert.equal((await visible('sales')).length,4);
 for(const [role,op,kind] of [['factory','milestone','factory_dispatched'],['logistics','milestone','china_received'],['client','receive',undefined]]){const rows=await visible(role!);assert.equal(rows.length,1);assert.equal(rows[0].operation,op);if(kind)assert.equal(rows[0].payload.kind,kind)}
 await db.exec(`reset role;update profiles set client_id='${other}',factory_id='${other}';update shipment_plans set logistics_actor_id='${other}';`);for(const role of ['factory','client','logistics'])assert.equal((await visible(role)).length,0);await db.exec('reset role');assert.equal((await db.query<{allowed:boolean}>("select has_function_privilege('anon','shipment_request_visible(uuid,text,jsonb)','EXECUTE') allowed")).rows[0].allowed,false)
 }finally{await db.close()}})
