import test from 'node:test'
import assert from 'node:assert/strict'
import {randomUUID} from 'node:crypto'
import {readFile} from 'node:fs/promises'
import {PGlite} from '@electric-sql/pglite'
const ids=Object.fromEntries(['staff','factoryActor','logistics','otherLogistics','clientActor','otherClient','factory','client','deal','order','product','variant','partner'].map(k=>[k,randomUUID()]))
async function setup(){const db=new PGlite();await db.exec(`set timezone='UTC';create role authenticated;create role anon;create schema auth;create type simple_status as enum('in_production','shipped','delivered');create table profiles(id uuid primary key,role text,factory_id uuid,client_id uuid,display_name text);
insert into profiles values('${ids.staff}','sales',null,null,'Synthetic sales'),('${ids.factoryActor}','factory','${ids.factory}',null,'Synthetic factory'),('${ids.logistics}','logistics',null,null,'Synthetic logistics'),('${ids.otherLogistics}','logistics',null,null,'Other logistics'),('${ids.clientActor}','client',null,'${ids.client}','Synthetic customer'),('${ids.otherClient}','client',null,'${randomUUID()}','Other customer');
grant usage on schema auth to authenticated;create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.actor',true),'')::uuid$$;create function is_staff() returns boolean language sql security definer as $$select coalesce((select role='sales' from profiles where id=auth.uid()),false)$$;
create table factories(id uuid primary key);insert into factories values('${ids.factory}');create table clients(id uuid primary key,company_name text,default_delivery_address text);insert into clients values('${ids.client}','Synthetic customer','Synthetic saved customer address');
create table deals(id uuid primary key,client_id uuid,archived_at timestamptz,simple_status simple_status default 'in_production');insert into deals(id,client_id) values('${ids.deal}','${ids.client}');
create table factory_purchase_orders(id uuid primary key,deal_id uuid,factory_id uuid,status text,quantity integer,snapshot jsonb,order_no text);insert into factory_purchase_orders values('${ids.order}','${ids.deal}','${ids.factory}','ordered',100,'{"variant_id":"${ids.variant}","item_name":"Synthetic package"}','SYNTH-PO');
create table factory_production_starts(order_id uuid primary key);insert into factory_production_starts values('${ids.order}');create table deal_products(id uuid primary key,shipping_address_full text,shipping_recipient_name text,shipping_phone text);insert into deal_products values('${ids.product}','Synthetic product address','Synthetic recipient','000000000');create table deal_product_variants(id uuid primary key,product_id uuid);insert into deal_product_variants values('${ids.variant}','${ids.product}');
create table logistics_partners(id uuid primary key,company_name text,address text,partner_kind text,is_active boolean);insert into logistics_partners values('${ids.partner}','Synthetic Haiyuan','Synthetic registered China address','shipping',true);
create table system_settings(company_info_phase1 jsonb);insert into system_settings values('{"name":"Synthetic BAO issuer","address":"Synthetic issuer address"}');
create function factory_order_ship_ready(oid uuid) returns boolean language sql as $$select current_setting('test.ready',true)='true'$$;
create function keep_factory_workflow_history() returns trigger language plpgsql as $$begin raise exception 'History immutable';end$$;
create function set_deal_simple_status(did uuid,status simple_status,note text,expected simple_status) returns jsonb language plpgsql as $$begin if not is_staff() then raise exception 'Staff only';end if;update deals set simple_status=status where id=did and simple_status=expected;if not found then raise exception 'Status changed';end if;return '{}';end$$;
set test.actor='${ids.staff}';set test.ready='true';`);await db.exec(await readFile('supabase/migrations/20261001145000_shipment_workflow_v1.sql','utf8'));return db}
const actor=(db:PGlite,id:string)=>db.query("select set_config('test.actor',$1,false)",[id])
async function cmd(db:PGlite,op:string,input:unknown,key=randomUUID()){return (await db.query<any>('select shipment_command($1,$2,$3,$4) r',[key,ids.order,op,JSON.stringify(input)])).rows[0].r}
const plan=(quantity=100,food=true)=>({quantity:String(quantity),partner_id:ids.partner,logistics_actor_id:ids.logistics,method:'sea',food_required:food,food_basis:'Synthetic inspection source',china_address:'Synthetic confirmed China address',china_source:'Synthetic verified logistics contact',destination_source:'saved_product',destination_address:'Synthetic product address',recipient:'Synthetic recipient',phone:'000000000',confirmed:true})
async function event(db:PGlite,pid:string,kind:string){const stamp=(await db.query<any>('select clock_timestamp()::text t')).rows[0].t;return cmd(db,'milestone',{plan_id:pid,kind,source:'Synthetic carrier document',note:'Synthetic actual milestone',tracking_number:'SYNTH-TRACK',occurred_at:stamp,confirmed:true})}
async function deliver(db:PGlite,pid:string,food=true){await actor(db,ids.factoryActor);await event(db,pid,'factory_dispatched');await actor(db,ids.logistics);for(const kind of ['china_received',...(food?['inspection_ready','inspection_cleared']:[]),'international_departed','japan_arrived','out_for_delivery','carrier_delivered'])await event(db,pid,kind)}
async function receipt(db:PGlite,pid:string,quantity:number,received=0){return cmd(db,'receive',{plan_id:pid,quantity:String(quantity),expected_received:String(received),received_on:new Date().toISOString().slice(0,10),note:'Synthetic actual receipt',confirmed:true})}
test('actual shipping/inspection, partial customer receipt and frozen delivery note are distinct; direct completion bypass denied',async()=>{const db=await setup();try{
 await assert.rejects(db.exec("update deals set simple_status='shipped'"),/Actual dispatch/);await assert.rejects(db.exec("update deals set simple_status='delivered'"),/Actual dispatch/);const key=randomUUID(),p=await cmd(db,'prepare',plan(),key);assert.deepEqual(await cmd(db,'prepare',plan(),key),p);await assert.rejects(db.exec("update deals set simple_status='shipped'"),/Actual dispatch/);await actor(db,ids.staff);await assert.rejects(cmd(db,'issue_delivery',{plan_id:p.plan_id}),/full customer/)
 await actor(db,ids.factoryActor);await event(db,p.plan_id,'factory_dispatched');await actor(db,ids.logistics);await event(db,p.plan_id,'china_received');await assert.rejects(event(db,p.plan_id,'international_departed'),/Next actual/);for(const k of ['inspection_ready','inspection_cleared','international_departed','japan_arrived','out_for_delivery','carrier_delivered'])await event(db,p.plan_id,k)
 await actor(db,ids.staff);await cmd(db,'advance_shipped',{plan_id:p.plan_id});await assert.rejects(db.exec("update deals set simple_status='delivered'"),/Actual full customer/);await actor(db,ids.clientActor);await receipt(db,p.plan_id,40);await assert.rejects(receipt(db,p.plan_id,60,0),/Current remaining/);await receipt(db,p.plan_id,60,40)
 await actor(db,ids.staff);const doc=await cmd(db,'issue_delivery',{plan_id:p.plan_id});await assert.rejects(cmd(db,'advance_delivered',{plan_id:p.plan_id}),/mail acceptance/);const mail=(await db.query<any>("select claim_shipment_email($1,'delivery','{}') r",[p.plan_id])).rows[0].r;await db.query("select finish_shipment_email($1,'accepted','synthetic')",[mail.attempt_id]);await cmd(db,'advance_delivered',{plan_id:p.plan_id});const snap=(await db.query<any>('select shipment_delivery_context($1) r',[doc.document_id])).rows[0].r;assert.equal(snap.quantity,100);assert.equal(snap.customer_name,'Synthetic customer');assert.equal(snap.destination_address,'Synthetic product address');assert.equal(snap.unit_price_usd,undefined);await db.exec("update deal_products set shipping_address_full='Changed later'");assert.deepEqual((await db.query<any>('select shipment_delivery_context($1) r',[doc.document_id])).rows[0].r,snap)
 await assert.rejects(db.exec('delete from shipment_customer_receipts'),/immutable/)
 }finally{await db.close()}})
test('split shipment plan totals, food-unneeded and air/manual source must be explicit; no warehouse or guessed address',async()=>{const db=await setup();try{
 for(const bad of [{china_source:''},{china_address:''},{confirmed:false},{destination_address:'Changed'},{destination_source:'warehouse'},{food_required:''},{method:'unknown'}])await assert.rejects(cmd(db,'prepare',{...plan(),...bad}))
 const a=await cmd(db,'prepare',plan(60,false));await cmd(db,'prepare',{...plan(40,false),method:'air',destination_source:'manual',destination_address:'Synthetic one-off address'});await assert.rejects(cmd(db,'prepare',plan(1)),/exceeds order/)
 await deliver(db,a.plan_id,false);await actor(db,ids.staff);await assert.rejects(cmd(db,'advance_shipped',{plan_id:a.plan_id}),/All order quantities/)
 await db.exec("set test.ready='false'");await actor(db,ids.factoryActor);const plans=(await db.query<any>('select shipment_context($1) r',[ids.order])).rows[0].r.plans;await assert.rejects(event(db,plans[1].id,'factory_dispatched'),/QC and payment/)
 }finally{await db.close()}})
test('role/order scopes and sanitized customer context; actual events cannot be impersonated or backdated',async()=>{const db=await setup();try{
 const p=await cmd(db,'prepare',plan());await assert.rejects(event(db,p.plan_id,'factory_dispatched'),/Factory dispatch/);await actor(db,ids.factoryActor);await assert.rejects(cmd(db,'prepare',plan(1)),/Staff active manufacturing/);await assert.rejects(cmd(db,'milestone',{plan_id:p.plan_id,kind:'factory_dispatched',source:'Synthetic',note:'Synthetic',tracking_number:'Synthetic',occurred_at:'2000-01-01T00:00:00Z',confirmed:true}),/chronological/)
 for(const foreign of [ids.otherLogistics,ids.otherClient]){await actor(db,foreign);await assert.rejects(db.query('select shipment_context($1)',[ids.order]),/unavailable/)}
 await actor(db,ids.clientActor);const ctx=(await db.query<any>('select shipment_context($1) r',[ids.order])).rows[0].r;assert.equal(ctx.options,null);assert.equal(ctx.plans[0].snapshot.china_address,undefined);assert.equal(ctx.plans[0].snapshot.logistics_actor_id,undefined);await assert.rejects(receipt(db,p.plan_id,100),/after carrier/);await db.query('update deals set client_id=$1',[randomUUID()]);await assert.rejects(receipt(db,p.plan_id,100),/unavailable/);await db.query('update deals set client_id=$1',[ids.client]);
 await actor(db,ids.factoryActor);const factoryContext=(await db.query<any>('select shipment_context($1) r',[ids.order])).rows[0].r;assert.equal(factoryContext.plans[0].snapshot.destination_address,undefined);assert.equal(factoryContext.plans[0].snapshot.phone,undefined);await db.exec('set role authenticated');assert.equal((await db.query('select * from shipment_plans')).rows.length,0);await assert.rejects(db.exec('truncate shipment_plans cascade'),/permission/);await assert.rejects(db.exec('insert into shipment_workflow_requests default values'),/permission/);await db.exec('reset role;set role anon');await assert.rejects(db.query('select shipment_context($1)',[ids.order]),/permission/)
 }finally{await db.close()}})
test('permanent mail reservation survives unknown delivery/late retries and one terminal result; no external sender access',async()=>{const db=await setup();try{
 const p=await cmd(db,'prepare',plan());await deliver(db,p.plan_id);await actor(db,ids.staff);const eid=(await db.query<any>('select id::text from shipment_milestones where plan_id=$1 limit 1',[p.plan_id])).rows[0].id;const claim=async()=>(await db.query<any>('select claim_shipment_email($1,$2,$3) r',[p.plan_id,eid,'{"to":"dummy@example.test"}'])).rows[0].r;const first=await claim();assert.equal(first.claimed,true);assert.equal((await claim()).claimed,false);await db.query("select finish_shipment_email($1,'unknown',null)",[first.attempt_id]);assert.equal((await claim()).status,'unknown');assert.equal((await db.query<any>("select finish_shipment_email($1,'accepted','late') r",[first.attempt_id])).rows[0].r,false);await actor(db,ids.logistics);await assert.rejects(claim(),/Staff mail/)
 }finally{await db.close()}})
test('legacy case without new manufacturing ledger stays compatible; adopting one new order requires all active order quantities',async()=>{
 const legacy=await setup();try{await legacy.exec('delete from factory_production_starts');await legacy.exec("update deals set simple_status='delivered'");assert.equal((await legacy.query<any>('select count(*)::int n from shipment_plans')).rows[0].n,0);await assert.rejects(cmd(legacy,'prepare',plan()),/active manufacturing/)}finally{await legacy.close()}
 const mixed=await setup();try{const other=randomUUID();await mixed.query("insert into factory_purchase_orders(id,deal_id,factory_id,status,quantity,snapshot,order_no) values($1,$2,$3,'ordered',10,'{}','SYNTH-LEGACY-PO')",[other,ids.deal,ids.factory]);const p=await cmd(mixed,'prepare',plan());await actor(mixed,ids.factoryActor);await event(mixed,p.plan_id,'factory_dispatched');await actor(mixed,ids.staff);await assert.rejects(cmd(mixed,'advance_shipped',{plan_id:p.plan_id}),/All order quantities/);await assert.rejects(mixed.exec("update deals set simple_status='shipped'"),/Actual dispatch/)}finally{await mixed.close()}
})
