'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {clientFinanceCommand,previewClientReissue,previewClientPriceReissue,previewClientDocumentResend,sendClientDocumentAgain} from '@/lib/actions/client-finance'
import {useWorkflowRequest} from '@/lib/hooks/use-workflow-request'
import {FinanceSummary,type FinancePacket,type FinanceSnapshot} from './client-finance-panel'
export interface FinanceState {packet_id:string;payment_totals:{gross_jpy:string;refund_jpy:string;net_jpy:string};valid_link:boolean;send_state:{status:string|null;can_resend:boolean}}
const field='w-full min-h-11 rounded-input border border-[#E2E1DA] bg-[#EFEFEA] px-3'
const button='min-h-11 rounded-full border border-[#E2E1DA] px-4 font-bold disabled:opacity-40'
export function ClientFinanceCorrections({dealId,packets,documents,states}:{dealId:string;packets:FinancePacket[];documents:{id:string;document_type:string;document_number:string}[];states:FinanceState[]}){
 const router=useRouter(),request=useWorkflowRequest(`finance-corrections:${dealId}`,'client_finance')
 const [packetId,setPacketId]=useState(''),[operation,setOperation]=useState('renew_link'),[reason,setReason]=useState(''),[documentId,setDocumentId]=useState(''),[amount,setAmount]=useState(''),[date,setDate]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[preview,setPreview]=useState<Record<string,unknown>|null>(null),[mail,setMail]=useState<{fingerprint:string;from:string;to:string;subject:string;attachment:string;body:string;canResend:boolean}|null>(null)
 const active=packets.filter(p=>p.status==='active'),packet=active.find(p=>p.id===packetId),state=states.find(s=>s.packet_id===packetId),blocked=busy||!request.ready||!!request.recovered
 const unshared=documents.filter(d=>d.document_type==='invoice'&&!packets.some(p=>p.document_id===d.id))
 function reset(){setPreview(null);setMail(null);setConfirmed(false);setError('');setSuccess('')}
 async function inspect(){setBusy(true);setError('');try{if(operation==='reissue_invoice'||operation==='reissue_priced_invoice'){const approval=active.find(p=>p.document_type==='quotation');const r=operation==='reissue_priced_invoice'?await previewClientPriceReissue(packetId,documentId,approval?.id||''):await previewClientReissue(packetId,documentId);if(r.error)setError(r.error);else setPreview(r.preview!)}else{const r=await previewClientDocumentResend(packetId);if(r.error)setError(r.error);else setMail(r.preview!)}}catch{setError('内容を確認できません。再試行してください')}finally{setBusy(false)}}
 async function save(){setBusy(true);setError('');try{
  const input:Record<string,unknown>={packet_id:packetId,reason,...((operation==='reissue_invoice'||operation==='reissue_priced_invoice')?{approval_packet_id:active.find(p=>p.document_type==='quotation')?.id,payment_allocation_confirmed:confirmed,document_id:documentId,expected:preview,same_obligation_confirmed:confirmed}:operation==='record_refund'?{amount_jpy:amount,refunded_on:date,bank_reference:reference,bank_confirmed:confirmed}:operation==='resend'?{fingerprint:mail?.fingerprint,recipient_requested:confirmed}:{})}
  const id=await request.requestId({operation,input})
  if(operation==='resend'){const r=await sendClientDocumentAgain(id,packetId,mail!.fingerprint,reason,confirmed);if(r.error){setError(r.error);return}setSuccess('メールサービス受付済みです。到達は別途確認してください')}
  else{const r=await clientFinanceCommand(id,operation,input);if(r.error){if(r.canCorrect)request.complete();setError(r.error);return}setSuccess(r.result?.token?`保存済み。共有リンク：/portal/documents/${r.result.packet_id}?token=${r.result.token}`:'履歴を保存しました。実着金と未収を確認してください')}
  request.complete();setPreview(null);setMail(null);setConfirmed(false);router.refresh()
 }catch(e){setError(e instanceof Error?e.message:'保存結果を確認できません')}finally{setBusy(false)}}
 const canSave=!!packet&&(operation==='renew_link'?!state?.valid_link:!!reason.trim()&&((operation==='reissue_invoice'||operation==='reissue_priced_invoice')?!!preview&&confirmed:operation==='resend'?!!mail?.canResend&&confirmed:operation==='record_refund'?confirmed&&/^[1-9][0-9]*$/.test(amount)&&!!date&&!!reference.trim():true))
 return <details className="rounded-card border border-[#E2E1DA] bg-white p-4"><summary className="min-h-11 cursor-pointer font-bold">訂正・期限切れリンク・再送・返金記録</summary><div className="space-y-3 pt-3">
 <p className="text-[12px]">履歴と元の着金を残して対応します。金額・条件が変わる請求の訂正は担当者へ相談してください。銀行への送金は実行しません。</p>
 <label className="block">対象の有効版<select className={field} value={packetId} onChange={e=>{setPacketId(e.target.value);setOperation('renew_link');reset()}}><option value="">共有版を選択</option>{active.map(p=><option key={p.id} value={p.id}>{p.snapshot.number}</option>)}</select></label>
 <label className="block">対応<select aria-label="対応" className={field} value={operation} onChange={e=>{setOperation(e.target.value);reset()}}><option value="renew_link">期限切れリンクを更新</option><option value="resend">顧客の依頼で同じ版を再送</option>{packet?.document_type==='invoice'&&<><option value="reissue_priced_invoice">再承認済み新価格に請求を差替</option><option value="reissue_invoice">同じ請求の訂正版を共有</option><option value="record_refund">銀行実施済みの返金を記録</option></>}<option value="cancel_packet">差引着金ゼロの版を取消</option></select></label>
 {state&&packet?.document_type==='invoice'&&<p>実着金 ¥{Number(state.payment_totals.gross_jpy).toLocaleString('ja-JP')} · 実施済み返金 ¥{Number(state.payment_totals.refund_jpy).toLocaleString('ja-JP')} · 差引着金 ¥{Number(state.payment_totals.net_jpy).toLocaleString('ja-JP')}</p>}
 {operation==='renew_link'?<p>{state?.valid_link?'現在のリンクは有効です。更新せず既存リンクを共有してください。':'更新後のリンクは7日間有効です。帳票の内容は変わりません。'}</p>:<label className="block">対応理由<textarea className={field} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label>}
 {(operation==='reissue_invoice'||operation==='reissue_priced_invoice')&&<><label className="block">新しく発行した請求書<select className={field} value={documentId} onChange={e=>{setDocumentId(e.target.value);setPreview(null);setConfirmed(false)}}><option value="">訂正版を選択</option>{unshared.map(d=><option key={d.id} value={d.id}>{d.document_number}</option>)}</select></label><p className="text-[12px]">{operation==='reissue_priced_invoice'?'新価格と引継ぎ額の顧客再承認後、帳票画面で新しい請求書を発行してください。発注済みや承認後の引継ぎ額変更は差替できません。':'先に帳票画面で訂正版を発行してください。数量・金額・期限・支払条件が同じ場合だけ、旧版の着金を引き継ぎます。'}</p><button className={button} disabled={blocked||!packet||!documentId} onClick={()=>void inspect()}>訂正版を確認</button>{preview&&<FinanceSummary snapshot={preview as unknown as FinanceSnapshot}/>}</>}
 {operation==='record_refund'&&<><label className="block">実際に返金した金額（円）<input className={field} inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="block">銀行で実施した返金日<input className={field} type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="block">銀行明細の一意な照合番号<input className={field} maxLength={500} value={reference} onChange={e=>setReference(e.target.value)}/></label></>}
 {operation==='resend'&&<><p className="text-[12px]">前回の受付確認済みと、顧客からの再送依頼が必要です。結果不明の送信は再送できません。</p><button className={button} disabled={blocked||!packet||!state?.send_state.can_resend} onClick={()=>void inspect()}>再送内容を確認</button>{mail&&<div className="break-all"><p>送信元 {mail.from}<br/>宛先 {mail.to}<br/>件名 {mail.subject}<br/>添付 {mail.attachment}</p><p className="whitespace-pre-wrap">{mail.body}</p></div>}</>}
 {['reissue_invoice','reissue_priced_invoice','record_refund','resend'].includes(operation)&&<label className="flex items-center gap-2 min-h-11"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{operation==='reissue_priced_invoice'?'顧客の新価格承認と差引着金の一度だけの引継ぎ・差額未収を確認した':operation==='reissue_invoice'?'同じ請求の置換であり二重請求ではない':operation==='record_refund'?'銀行明細で実施済みの返金を確認した':'顧客の明示的な再送依頼と宛先・添付を確認した'}</label>}
 {error&&<p role="alert" className="border border-[#FF5C34] rounded-card p-3">{error}</p>}{success&&<p role="status" className="break-all">{success}</p>}
 {request.recovered&&<p role="status">前回の保存結果があります。履歴を確認して続けてください。<button className={button} onClick={()=>{request.complete();router.refresh()}}>保存済み履歴を確認した</button></p>}
 <button className={button} disabled={blocked||!canSave} onClick={()=>void save()}>{busy?'保存中…':operation==='resend'?'確認したPDFを再送する':operation==='record_refund'?'実施済み返金を記録する':operation==='reissue_priced_invoice'?'着金を引継いで再承認済み請求へ差替える':operation==='reissue_invoice'?'旧版を残して訂正版を共有する':operation==='cancel_packet'?'理由を残して取消する':'リンクを更新する'}</button>
 {!canSave&&!success&&<p className="text-[12px]">対象を選び、理由・確認項目を入力してください。再送は前回の受付確認、訂正版は内容プレビューが必要です。</p>}
 </div></details>
}
