'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {clientFinanceCommand,previewClientDocument,previewClientDocumentMail,sendClientDocumentMail} from '@/lib/actions/client-finance'
import {useWorkflowRequest} from '@/lib/hooks/use-workflow-request'

export interface FinanceSnapshot {payment_conditions?:{mode:string;balance_due:string;upfront_jpy:string;shipment_required_jpy:string;total_jpy:string};type:string;number:string;customer_name:string;deal_name:string;due_date:string|null;total:string;subtotal:string;tax:string;lines:{name:string;variant:string;quantity:string;unit_jpy:string;gross:string}[]}
export interface FinancePacket {id:string;document_type:string;status:string;snapshot:FinanceSnapshot}
export interface FinanceReceipt {packet_id:string;amount_jpy:number}
export interface FinanceReport {id:string;packet_id:string;amount_jpy:number;paid_on:string;reference:string;status:string}
const field='w-full min-h-11 rounded-input border border-[#E2E1DA] bg-[#EFEFEA] px-3'
const button='min-h-11 rounded-full border border-[#E2E1DA] px-4 font-bold disabled:opacity-40'
export function FinanceSummary({snapshot:s}:{snapshot:FinanceSnapshot}){return <section className="rounded-card border border-[#E2E1DA] bg-white p-4 space-y-3">
 <p className="text-[12px]">{s.number} · {s.customer_name} 御中</p><h2 className="text-[15px] font-bold">{s.deal_name}</h2>
 <p className="text-[24px] font-extrabold num">¥{Number(s.total).toLocaleString('ja-JP')} <span className="text-[12px] font-normal">税込</span></p>
 {s.payment_conditions&&<p>支払条件：{s.payment_conditions.mode==='full_prepaid'?'全額前払い':s.payment_conditions.mode==='half_prepaid'?'半金前払い':'後払い'} · 発注前 ¥{Number(s.payment_conditions.upfront_jpy).toLocaleString('ja-JP')} · 発送前累計 ¥{Number(s.payment_conditions.shipment_required_jpy).toLocaleString('ja-JP')}<br/>残金は{s.payment_conditions.balance_due==='before_shipment'?'発送前':'納品後・請求書の支払期限まで'}（半金の1円端数は前払側へ）</p>}{s.due_date&&<p>支払期限 {s.due_date}</p>}
 <ul className="divide-y divide-[#E2E1DA]">{s.lines.map((l,i)=><li key={i} className="py-2">{l.name} · {l.variant}<p>{l.quantity}個 × ¥{Number(l.unit_jpy).toLocaleString('ja-JP')}（税抜単価）</p></li>)}</ul>
 <p className="text-[12px]">保存済み税抜 ¥{Number(s.subtotal).toLocaleString('ja-JP')} / 消費税 ¥{Number(s.tax).toLocaleString('ja-JP')}</p>
 </section>}

export function ClientFinanceResponse({packetId,token,snapshot,decision,confirmed,reports}:{packetId:string;token:string|null;snapshot:FinanceSnapshot;decision:string|null;confirmed:string;reports:{id:string;amount_jpy:string;paid_on:string;status:string}[]}){
 const router=useRouter(),request=useWorkflowRequest(`client-finance:${packetId}`,'client_finance')
 const [note,setNote]=useState(''),[amount,setAmount]=useState(''),[date,setDate]=useState(''),[reference,setReference]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[confirm,setConfirm]=useState(false)
 async function run(operation:string,input:Record<string,unknown>){setBusy(true);setError('');try{const payload={packet_id:packetId,token,...input},id=await request.requestId({operation,payload}),r=await clientFinanceCommand(id,operation,payload);if(r.error){if(r.canCorrect)request.complete();setError(r.error+(r.canCorrect?"。入力を訂正して保存できます":""));return}request.complete();setSuccess(operation==='respond_quote'?'回答を保存しました。営業担当が確認して次の請求書をご案内します':'入金申告を保存しました。BAOの実着金確認をお待ちください');router.refresh()}catch(e){setError(e instanceof Error?e.message:'保存を確認できません')}finally{setBusy(false)}}
 const blocked=busy||!request.ready||!!request.recovered
 return <div className="space-y-4 text-[14px]">
 <FinanceSummary snapshot={snapshot}/>
 <a className={`${button} inline-flex items-center`} href={`/api/client-documents/${packetId}/pdf${token?`?token=${encodeURIComponent(token)}`:''}`} target="_blank" rel="noreferrer">この版のPDFを確認</a>
 {(error||request.error)&&<p role="alert" className="rounded-card border border-[#FF5C34] p-3">{error||request.error}</p>}
 {(success||request.recovered)&&<div role="status" className="rounded-card bg-[#D7EFFF] text-[#33566F] p-3">{success||'前回の保存結果が見つかりました。下の回答・申告履歴を確認してください。'}{request.recovered&&<button className={`${button} ml-2`} onClick={()=>{request.complete();router.refresh()}}>履歴を確認して続ける</button>}</div>}
 {!request.ready&&!request.error&&<p role="status">前回の保存結果を確認中です…</p>}
 {snapshot.type==='quotation'?decision?<p>回答済み：{decision==='approved'?'承認・営業確認待ち':'修正依頼・営業対応待ち'}</p>:<section className="space-y-3"><h2 className="font-bold">この見積版への回答</h2><label className="block">確認事項・修正内容<textarea className={field} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><label className="flex items-center gap-2 min-h-11"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>数量・仕様・税込金額・支払条件を確認しました</label><p className="text-[12px]">承認には上の確認チェックが必要です。変更がある場合は修正依頼を選んでください。</p><div className="flex flex-wrap gap-2"><button disabled={blocked||!confirm} className={`${button} bg-[#E9F056] text-[#666C14]`} onClick={()=>void run('respond_quote',{decision:'approved',note})}>この版を承認する</button><button disabled={blocked||!note.trim()} className={button} onClick={()=>void run('respond_quote',{decision:'revision_requested',note})}>修正を依頼する</button></div></section>:<section className="space-y-3"><h2 className="font-bold">入金申告・BAO確認</h2><p>実着金確認済み ¥{Number(confirmed).toLocaleString('ja-JP')} / ご請求 ¥{Number(snapshot.total).toLocaleString('ja-JP')} · 未収 ¥{Math.max(0,Number(snapshot.total)-Number(confirmed)).toLocaleString('ja-JP')}</p><p className="text-[12px]">振込の申告は入金完了ではありません。銀行への送金はこの画面では行いません。</p>
 {Number(confirmed)>=Number(snapshot.total)?<p role="status">BAOの全額着金確認済みです。次の発注準備は営業担当が進めます。</p>:<form onSubmit={e=>{e.preventDefault();void run('report_payment',{amount_jpy:amount,paid_on:date,reference})}} className="space-y-3"><label className="block">振込金額（円）<input required inputMode="numeric" pattern="[1-9][0-9]*" className={field} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="block">振込日<input required type="date" className={field} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="block">振込名義・確認用情報<input required maxLength={500} className={field} value={reference} onChange={e=>setReference(e.target.value)}/></label><button disabled={blocked} className={`${button} bg-[#E9F056] text-[#666C14]`}>{busy?'保存中…':'入金を申告する'}</button></form>}
 <h3 className="font-bold">自分の申告履歴</h3>{reports.length?reports.map(r=><p key={r.id}>{r.paid_on} · ¥{Number(r.amount_jpy).toLocaleString('ja-JP')} · {r.status==='pending'?'BAO確認待ち':r.status==='confirmed'?'申告額の着金確認済み':'確認不成立・担当へ相談'}</p>):<p className="text-[12px]">申告はありません。振込後に金額・日付・名義を入力してください。</p>}</section>}
 </div>
}

export function StaffFinancePanel({dealId,documents,packets,reports,receipts}:{dealId:string;documents:{id:string;document_type:string;document_number:string}[];packets:FinancePacket[];reports:FinanceReport[];receipts?:FinanceReceipt[]}){
 const [mode,setMode]=useState('full_prepaid'),[balance,setBalance]=useState('before_shipment')
 const [mail,setMail]=useState<{id:string;from:string;to:string;subject:string;body:string;attachment:string;fingerprint:string;status:string|null}|null>(null)
 const router=useRouter(),request=useWorkflowRequest(`finance-staff:${dealId}`,'client_finance'),[doc,setDoc]=useState(''),[preview,setPreview]=useState<Record<string,unknown>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[link,setLink]=useState(''),[reportId,setReportId]=useState(''),[amount,setAmount]=useState(''),[date,setDate]=useState(''),[reference,setReference]=useState(''),[bankChecked,setBankChecked]=useState(false)
 const activeQuote=packets.find(p=>p.status==='active'&&p.document_type==='quotation')
 async function run(operation:string,input:Record<string,unknown>){setBusy(true);setError('');try{const id=await request.requestId({operation,input}),r=await clientFinanceCommand(id,operation,input);if(r.error){if(r.canCorrect)request.complete();setError(r.error+(r.canCorrect?"。入力を訂正して保存できます":""));return}if(r.result?.token)setLink(`/portal/documents/${r.result.packet_id}?token=${r.result.token}`);request.complete();setPreview(null);router.refresh()}catch(e){setError(e instanceof Error?e.message:'保存を確認できません')}finally{setBusy(false)}}
 const disabled=busy||!request.ready||!!request.recovered,pending=reports.filter(r=>r.status==='pending'),selected=pending.find(r=>r.id===reportId)
 return <div className="space-y-4 text-[14px]">
 <p className="text-[12px]">発行版の共有 → 顧客回答 → 請求書 → 入金申告 → BAO実着金確認。送付と承認・実着金は別記録です。</p>
 {(error||request.error)&&<p role="alert" className="border border-[#FF5C34] rounded-card p-3">{error||request.error}</p>}
 {request.recovered&&<p role="status">前回の保存結果を確認しました。<button className={button} onClick={()=>{if(request.recovered?.token)setLink(`/portal/documents/${request.recovered.packet_id}?token=${request.recovered.token}`);request.complete();router.refresh()}}>保存済み履歴を確認して続ける</button></p>}
 <section className="rounded-card border border-[#E2E1DA] bg-white p-4 space-y-3"><h2 className="font-bold">顧客へ共有する発行版</h2>{documents.length?<><label className="block">発行済み見積書・請求書<select className={field} value={doc} onChange={e=>{setDoc(e.target.value);setPreview(null)}}><option value="">帳票を選択</option>{documents.map(d=><option key={d.id} value={d.id}>{d.document_type==='quotation'?'見積書':'請求書'} {d.document_number}</option>)}</select></label>{documents.find(d=>d.id===doc)?.document_type==='quotation'&&<div className="space-y-2"><label className="block">顧客へ提示する支払条件<select className={field} value={mode} onChange={e=>{setMode(e.target.value);setBalance(e.target.value==='postpaid'?'after_delivery':'before_shipment');setPreview(null)}}><option value="full_prepaid">全額前払い</option><option value="half_prepaid">半金前払い</option><option value="postpaid">後払い</option></select></label>{mode==='half_prepaid'&&<label className="block">残金の期限<select className={field} value={balance} onChange={e=>{setBalance(e.target.value);setPreview(null)}}><option value="before_shipment">発送前</option><option value="after_delivery">納品後（請求書の支払期限）</option></select></label>}<p className="text-[12px]">条件は顧客がこの見積版を承認してから有効です。既存承認版は変更せず、新しい版で提示します。</p></div>}<button className={button} disabled={disabled||!doc} onClick={async()=>{setError('');setBusy(true);try{const r=await previewClientDocument(doc,activeQuote?.id||null,mode,balance);if(r.error)setError(r.error);else setPreview(r.preview!)}catch{setError('プレビューを取得できません。再試行してください')}finally{setBusy(false)}}}>顧客向け内容を確認</button>{preview&&<><FinanceSummary snapshot={preview as unknown as FinanceSnapshot}/><button className={`${button} bg-[#E9F056] text-[#666C14]`} disabled={disabled} onClick={()=>void run('publish_document',{document_id:doc,approval_packet_id:preview.type==='invoice'?activeQuote?.id||null:null,expected:preview})}>この発行版を共有する</button><p className="text-[12px]">共有先は登録顧客の自社アカウントです。メールはこの操作では送信しません。</p></>}</>:<p>発行済み見積書・請求書がありません。案件の帳票画面で発行して戻ってください。</p>}
 {link&&<p role="status" className="break-all">共有リンク（ログイン必須・7日有効）：<a className="underline" href={link}>{link}</a></p>}</section>
 <section className="space-y-2"><h2 className="font-bold">共有・工程反映</h2>{packets.length?packets.map(p=><article key={p.id} className="rounded-card border border-[#E2E1DA] p-3"><p>{p.snapshot.number} · {p.status==='active'?'有効':p.status==='cancelled'?'取消済み':'旧版'} · ¥{Number(p.snapshot.total).toLocaleString('ja-JP')}</p>{p.snapshot.payment_conditions&&<p>顧客合意条件：{p.snapshot.payment_conditions.mode==='full_prepaid'?'全額前払い':p.snapshot.payment_conditions.mode==='half_prepaid'?'半金前払い':'後払い'} · 発注前 ¥{Number(p.snapshot.payment_conditions.upfront_jpy).toLocaleString('ja-JP')} · 発送前累計 ¥{Number(p.snapshot.payment_conditions.shipment_required_jpy).toLocaleString('ja-JP')}</p>}{p.document_type==='invoice'&&receipts&&<p>実着金 ¥{receipts.filter(r=>r.packet_id===p.id).reduce((n,r)=>n+Number(r.amount_jpy),0).toLocaleString('ja-JP')} / 未収 ¥{Math.max(0,Number(p.snapshot.total)-receipts.filter(r=>r.packet_id===p.id).reduce((n,r)=>n+Number(r.amount_jpy),0)).toLocaleString('ja-JP')} · 支払期限 {p.snapshot.due_date||'未確認'}</p>}{p.status==='active'&&<button disabled={disabled} className={button} onClick={()=>void run(p.document_type==='quotation'?'advance_quote':'advance_paid',{packet_id:p.id})}>{p.document_type==='quotation'?'顧客承認を確認して見積確定へ':'合意条件・必要着金を確認して発注準備へ'}</button>}<p className="text-[12px]">{p.document_type==='quotation'?'顧客未承認・価格変更時は工程を進められません。':'申告だけでは進められません。合意した前払額のBAO実着金が必要です。後払いでも顧客承認と請求版が必要で、残額は未収として残します。'}</p></article>):<p>共有履歴はありません。上で発行版の内容を確認してください。</p>}</section>
 <section className="rounded-card border border-[#E2E1DA] bg-white p-4 space-y-3"><h2 className="font-bold">入金申告 {pending.length}件・BAO確認待ち</h2>{pending.length?<form className="space-y-3" onSubmit={e=>{e.preventDefault();if(selected)void run('confirm_receipt',{packet_id:selected.packet_id,report_id:selected.id,amount_jpy:amount,received_on:date,bank_reference:reference,bank_confirmed:bankChecked})}}><label className="block">確認する申告<select required className={field} value={reportId} onChange={e=>setReportId(e.target.value)}><option value="">申告を選択</option>{pending.map(r=><option key={r.id} value={r.id}>{r.paid_on} · ¥{r.amount_jpy.toLocaleString('ja-JP')} · {r.reference}</option>)}</select></label><label className="block">銀行で確認した着金額（円）<input required className={field} inputMode="numeric" pattern="[1-9][0-9]*" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="block">実着金日<input required type="date" className={field} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="block">銀行明細の一意な照合番号<input required maxLength={500} className={field} value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="flex gap-2 items-center min-h-11"><input type="checkbox" checked={bankChecked} onChange={e=>setBankChecked(e.target.checked)}/>実際の銀行明細で着金を確認した</label><button disabled={disabled||!bankChecked} className={button}>実着金を記録する</button><p className="text-[12px]">銀行確認チェックが必要です。部分着金は残額を残し、工程は自動で進めません。</p></form>:<p>未確認の申告はありません。顧客の申告後にこの一覧へ表示します。</p>}</section>
 <details className="rounded-card border border-[#E2E1DA] p-4"><summary className="min-h-11 cursor-pointer font-bold">共有版のPDF・メール送付</summary><p className="text-[12px]">顧客へ渡す固定版のPDFです。送信前に宛先・内容・添付を確認します。受付と到達は別です。</p>{packets.filter(p=>p.status==='active').map(p=><div key={p.id} className="flex flex-wrap gap-2 py-2"><a href={`/api/client-documents/${p.id}/pdf`} target="_blank" rel="noreferrer" className={`${button} inline-flex items-center`}>{p.snapshot.number} PDF</a><button className={button} disabled={disabled} onClick={async()=>{setBusy(true);setError('');try{const r=await previewClientDocumentMail(p.id);if(r.error)setError(r.error);else setMail({...r.preview!,id:p.id})}catch{setError('送信内容を確認できません。未送信です')}finally{setBusy(false)}}}>メール内容を確認</button></div>)}</details>
 {mail&&<section aria-label="メール送信前確認" className="rounded-card border border-[#E2E1DA] bg-white p-4 space-y-2"><h2 className="font-bold">メール送信前の確認</h2><p className="break-all">送信元 {mail.from}<br/>宛先 {mail.to}<br/>件名 {mail.subject}<br/>添付 {mail.attachment}</p><p className="whitespace-pre-wrap break-all">{mail.body}</p><p role="status">{mail.status==='accepted'?'メールサービス受付済み・到達は未確認':mail.status?'既存の送信履歴あり・再送停止':'未送信'}</p><button className={button} disabled={disabled||!!mail.status} onClick={async()=>{setBusy(true);setError('');try{const r=await sendClientDocumentMail(mail.id,mail.fingerprint);if(r.error)setError(r.error);setMail({...mail,status:r.status||'unknown'})}catch{setError('送信結果が不明です。再送せず履歴を確認してください');setMail({...mail,status:'unknown'})}finally{setBusy(false)}}}>確認した宛先へPDFを送付する</button><button className={button} disabled={busy} onClick={()=>setMail(null)}>確認を閉じる</button></section>}
 </div>
}
