'use client'
/* Private authenticated media uses short-lived URLs; Next image caching is inappropriate. */
/* eslint-disable @next/next/no-img-element */
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {createClient} from '@/lib/supabase/client'
import {useWorkflowRequest} from '@/lib/hooks/use-workflow-request'
import {registerFactoryQcUpload,factoryQcCommand} from '@/lib/actions/factory-qc'
import {qcKindNames,validQcBytes,type QcContext,type QcKind} from '@/lib/factory-workflow/qc-types'
import type {FactoryWorkflowContext} from '@/lib/factory-workflow/types'
const field='w-full min-h-11 rounded-input border border-[#E2E1DA] bg-[#EFEFEA] px-3',button='min-h-11 rounded-full border border-[#E2E1DA] px-4 font-bold disabled:opacity-40'
export function FactoryQcPanel({workflow:w,qc}:{workflow:FactoryWorkflowContext;qc:QcContext}){
 const router=useRouter(),staff=w.actor_role==='staff',request=useWorkflowRequest(`factory-qc:${w.order.id}`,'factory_qc',w.order.id),latest=qc.submissions[0],review=qc.reviews.find(r=>r.submission_id===latest?.id),missing=(Object.keys(qcKindNames) as QcKind[]).filter(kind=>!qc.assets.some(a=>a.kind===kind))
 const [kind,setKind]=useState<QcKind>('overall_photo'),[file,setFile]=useState<File|null>(null),[selected,setSelected]=useState<string[]>([]),[quantity,setQuantity]=useState(''),[date,setDate]=useState(''),[note,setNote]=useState(''),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[rejectionScope,setRejectionScope]=useState<'all'|'new_quantity'>('all'),[decision,setDecision]=useState<'approved'|'rejected'>('approved')
 const selectedMissing=(Object.keys(qcKindNames) as QcKind[]).filter(kind=>!qc.assets.some(a=>selected.includes(a.id)&&a.kind===kind))
 const blocked=busy||!request.ready||!!request.recovered||w.order.status!=='ordered',canSubmit=!latest||review?.decision==='rejected'||(review?.decision==='approved'&&latest.quantity<w.order.quantity)
 async function save(operation:'submit_qc'|'review_qc',input:Record<string,unknown>){setBusy(true);setError('');setSuccess('');try{const id=await request.requestId({operation,input}),r=await factoryQcCommand(id,w.order.id,operation,input);if(r.error){if("canCorrect" in r&&r.canCorrect)request.complete();setError(r.error+("canCorrect" in r&&r.canCorrect?"。入力を訂正して保存できます":""));return}request.complete();setSuccess(operation==='submit_qc'?'完工証跡を提出しました。BAOのQC判断をお待ちください':'BAOのQC判断を記録しました。出荷条件と残金着金を確認してください');setChecked(false);router.refresh()}catch(e){setError(e instanceof Error?e.message:'保存を確認できません')}finally{setBusy(false)}}
 async function upload(){if(!file)return;setBusy(true);setError('');setSuccess('');try{
 if(file.size===0||file.size>52428800||(kind==='video'?file.type!=='video/mp4':!['image/png','image/jpeg'].includes(file.type)))throw Error('PNG/JPEG写真・MP4動画、1ファイル50MiB以下を選択してください')
 const bytes=await file.arrayBuffer();if(!validQcBytes(new Uint8Array(bytes),file.type))throw Error('ファイルの形式を確認できません。写真・動画を開いて確認してください')
 const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join(''),id=await request.requestId({operation:'register_asset',kind,sha256:hash,size:file.size,mime:file.type}),ext=file.type==='video/mp4'?'mp4':file.type==='image/png'?'png':'jpg',path=`${w.order.id}/${id}.${ext}`
 // A lost upload response may already have created the immutable object. The
 // server verifies the same path/hash before deciding whether registration succeeded.
 await createClient().storage.from('factory-qc').upload(path,file,{upsert:false,contentType:file.type,cacheControl:'0',metadata:{sha256:hash}})
 const r=await registerFactoryQcUpload(id,w.order.id,kind,path,hash);if(r.error){setError(r.error);return}request.complete();setFile(null);setSuccess('証跡を保存しました。提出する版に使う写真・動画を選択してください');router.refresh()
 }catch(e){setError(e instanceof Error?e.message:'アップロード結果を確認できません。同じファイルで再試行してください')}finally{setBusy(false)}}
 function finance(){const panel=document.getElementById('factory-finance') as HTMLDetailsElement|null;if(panel){panel.open=true;panel.scrollIntoView({block:'start'})}}
 return <section className="space-y-4 text-[14px]" aria-label="製造期限・QC・出荷条件">
 <div className="rounded-card border border-[#E2E1DA] bg-white p-4"><h2 className="text-[15px] font-bold">製造期限・QC・出荷条件</h2><p>担当 {w.factory_name} / 完了予定 {w.production?.expected_completion_on||'未記録'}</p>{qc.days_remaining!==null&&<p className={qc.days_remaining<0?'border-l-2 border-[#FF5C34] pl-2 mt-2':'mt-2'}>{qc.days_remaining<0?`予定超過 ${-qc.days_remaining}暦日`:`完了予定まで ${qc.days_remaining}暦日`}</p>}<p>QC承認累計 {qc.approved_quantity??(review?.decision==='approved'?latest?.quantity||0:0)} / 発注 {w.order.quantity}個{qc.reserved_quantity!==undefined?` · 配送/入庫割当 ${qc.reserved_quantity}個`:''}</p><p className="font-bold mt-2">次の対応：{qc.ship_ready&&(qc.approved_quantity??latest?.quantity??0)<w.order.quantity&&(qc.reserved_quantity??0)>=(qc.approved_quantity??latest?.quantity??0)?'工場：残りの累計完工証跡を提出':qc.ship_ready?`承認済み ${qc.approved_quantity??latest?.quantity??0}個の支払条件確認済み・発送手配へ`:!latest?'工場の完工証跡提出':!review?'BAOのQC判断待ち':review.decision==='rejected'?'工場の修正証跡・再提出待ち':'必要な残金の工場着金確認待ち'}</p><p className="text-[12px]">完工報告はQC承認ではありません。QC不承認・未判断・必要残金未着金では出荷できません。</p>{review?.decision==='approved'&&!qc.ship_ready&&<button className={`${button} mt-2`} onClick={finance}>残金の支払記録・工場着金確認を開く</button>}</div>
 {(error||request.error)&&<p role="alert" className="rounded-card border border-[#FF5C34] p-3">{error||request.error}</p>}{(success||request.recovered)&&<p role="status" className="rounded-card bg-[#D7EFFF] text-[#33566F] p-3">{success||'前回の保存結果が見つかりました。証跡・提出履歴を確認してください。'}{request.recovered&&<button className={`${button} ml-2`} onClick={()=>{request.complete();router.refresh()}}>保存済み結果を確認して続ける</button>}</p>}
 {!staff&&canSubmit&&<details open={!qc.assets.length} className="rounded-card border border-[#E2E1DA] p-4"><summary className="min-h-11 font-bold cursor-pointer">写真・動画を追加（非公開）</summary><p className="text-[12px]">{missing.length?`不足：${missing.map(k=>qcKindNames[k]).join('・')}`:'3種類の証跡が登録されています。修正時は新しいファイルを追加してください。'}</p><label className="block mt-3">証跡の種類<select className={field} value={kind} onChange={e=>setKind(e.target.value as QcKind)}>{Object.entries(qcKindNames).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label className="block my-3">証跡ファイル（PNG/JPEG/MP4・50MiB以下）<input type="file" accept="image/png,image/jpeg,video/mp4" className="w-full min-h-11" disabled={busy} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className={button} disabled={blocked||!file} onClick={()=>void upload()}>{busy?'保存確認中…':'この証跡を保存する'}</button><p className="text-[12px] mt-2">応答が不明な場合は同じファイルで再試行してください。旧証跡の上書き・削除は行いません。</p></details>}
 <div className="grid gap-3 sm:grid-cols-2">{qc.assets.filter(a=>!staff||!latest||latest.asset_ids.includes(a.id)).map(a=><article key={a.id} className="rounded-card border border-[#E2E1DA] bg-white p-3"><p className="font-bold">{qcKindNames[a.kind]}</p>{a.mime.startsWith('image/')?<img src={`/api/factory-qc-assets/${a.id}`} alt={qcKindNames[a.kind]} className="max-h-48 w-full object-contain"/>:<video controls preload="metadata" className="max-h-48 w-full" src={`/api/factory-qc-assets/${a.id}`}/>}<a className="min-h-11 inline-flex items-center underline" href={`/api/factory-qc-assets/${a.id}`} target="_blank" rel="noreferrer">証跡を別画面で確認</a>{!staff&&canSubmit&&<label className="flex items-center gap-2 min-h-11"><input type="checkbox" checked={selected.includes(a.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,a.id]:ids.filter(id=>id!==a.id))}/>この提出版に使用する</label>}</article>)}</div>
 {!qc.assets.length&&<p>完工証跡は未登録です。工場が製品全体写真・梱包写真・動画を追加します。</p>}
 {!staff&&canSubmit&&<form className="rounded-card border border-[#E2E1DA] bg-white p-4 space-y-3" onSubmit={e=>{e.preventDefault();void save('submit_qc',{asset_ids:selected,quantity,completed_on:date,note,completion_confirmed:checked})}}><h3 className="font-bold">完工証跡をBAOへ提出</h3><label className="block">実際の累計完工数量（発注 {w.order.quantity}個まで）<input required type="number" min="1" max={w.order.quantity} className={field} value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label className="block">実際の完工日<input required type="date" className={field} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="block">完工・修正内容<textarea required maxLength={2000} className={field} value={note} onChange={e=>setNote(e.target.value)}/></label><label className="flex gap-2 items-center min-h-11"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>累計完工数量と選択した3種類の証跡を確認した</label><p className="text-[12px]">全体写真・梱包写真・動画を選び、数量・確認チェックを入力してください。前回承認分を含む累計を入力します。次の分は新しい証跡で提出し、承認済み数量だけを発送に使えます。</p>{selectedMissing.length>0&&<p className="text-[12px]">提出に不足：{selectedMissing.map(k=>qcKindNames[k]).join('・')}を選択してください。</p>}<button disabled={blocked||!checked||selectedMissing.length>0} className={`${button} bg-[#E9F056] text-[#666C14]`}>この完工版を提出する</button></form>}
 {latest&&<div className="rounded-card border border-[#E2E1DA] p-4"><h3 className="font-bold">最新提出 第{latest.version}版</h3><p>{latest.completed_on} / {latest.quantity}個 / {latest.note}</p><p>{review?review.decision==='approved'?'BAO QC承認済み':'BAO QC不承認・修正待ち':'BAO QC判断待ち'}</p>{review&&<p>{review.note}</p>}{staff&&!review&&<form className="space-y-3 mt-3" onSubmit={e=>{e.preventDefault();void save('review_qc',{submission_id:latest.id,decision,note,evidence_checked:checked,rejection_scope:rejectionScope})}}><label className="block">QC判断<select className={field} value={decision} onChange={e=>setDecision(e.target.value as 'approved'|'rejected')}><option value="approved">承認</option><option value="rejected">不承認・修正依頼</option></select></label>{decision==='rejected'&&(qc.approved_quantity??0)>0&&<label className="block">不承認の影響範囲<select className={field} value={rejectionScope} onChange={e=>setRejectionScope(e.target.value as 'all'|'new_quantity')}><option value="all">既承認分にも影響・発送停止</option><option value="new_quantity">今回の追加分だけ（既承認分に問題がないと確認）</option></select><span className="text-[12px]">判断できない場合は発送停止を選びます。発送済み商品の回収・返品は別途担当へ連絡してください。</span></label>}<label className="block">判断根拠・修正指示<textarea required maxLength={2000} className={field} value={note} onChange={e=>setNote(e.target.value)}/></label><label className="flex items-center gap-2 min-h-11"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>最新提出版の数量・全体写真・梱包写真・動画を確認した</label><button disabled={blocked||!checked} className={`${button} bg-[#E9F056] text-[#666C14]`}>この版のQC判断を保存する</button></form>}</div>}
 {qc.submissions.length>1&&<details className="rounded-card border border-[#E2E1DA] p-4"><summary className="min-h-11 cursor-pointer">旧提出・判断履歴 {qc.submissions.length-1}件</summary>{qc.submissions.slice(1).map(s=><p key={s.id}>第{s.version}版 / {s.completed_on} / {qc.reviews.find(r=>r.submission_id===s.id)?.decision==='rejected'?'不承認':'履歴'} / {s.note}</p>)}</details>}
 </section>
}
