'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {useWorkflowRequest} from '@/lib/hooks/use-workflow-request'
import {factoryWorkflowCommand} from '@/lib/actions/factory-workflow'
import {factoryPaymentNames,usdUnits,formatUsdUnits,type FactoryWorkflowContext} from '@/lib/factory-workflow/types'
const field='w-full min-h-11 rounded-input border border-[#E2E1DA] bg-[#EFEFEA] px-3'
const button='min-h-11 rounded-full border border-[#E2E1DA] px-4 font-bold disabled:opacity-40'
export function FactoryWorkflowPanel({context:c}:{context:FactoryWorkflowContext}){
 const router=useRouter(),request=useWorkflowRequest(`factory-production:${c.order.id}`,'factory_workflow',c.order.id),staff=c.actor_role==='staff',latest=c.terms[0],terms=c.terms.find(t=>t.id===c.agreement?.terms_id),active=c.order.status==='ordered',bankPresent=!!c.registered_bank.data?.raw?.trim()
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[mode,setMode]=useState<string>(latest?.payment_mode||''),[upfront,setUpfront]=useState(latest?.upfront_usd||''),[balance,setBalance]=useState<string>(latest?.balance_due||''),[days,setDays]=useState(latest?.lead_days.toString()||''),[note,setNote]=useState(''),[evidence,setEvidence]=useState(''),[checked,setChecked]=useState(false),[amount,setAmount]=useState(''),[date,setDate]=useState(''),[reference,setReference]=useState(''),[report,setReport]=useState('')
 const confirmed=c.acknowledgments.reduce((sum,r)=>sum+usdUnits(r.amount_usd),BigInt(0)),sent=c.transfers.reduce((sum,r)=>sum+usdUnits(r.amount_usd),BigInt(0)),canStart=!!terms&&confirmed>=usdUnits(terms.upfront_usd),blocked=busy||!request.ready||!!request.recovered||!active
 const pendingTransfers=c.transfers.filter(r=>c.acknowledgments.filter(a=>a.report_id===r.id).reduce((sum,a)=>sum+usdUnits(a.amount_usd),BigInt(0))<usdUnits(r.amount_usd)),transferOutstanding=!!terms&&sent<usdUnits(terms.total_usd)
 async function run(operation:string,input:Record<string,unknown>){setBusy(true);setError('');setSuccess('');try{const key=await request.requestId({operation,input}),r=await factoryWorkflowCommand(key,c.order.id,operation,input);if(r.error){if(r.canCorrect)request.complete();setError(r.error+(r.canCorrect?"。入力を訂正して保存できます":""));return}request.complete();setSuccess(operation==='report_transfer'?'送金実施の記録を保存しました。工場の着金確認をお待ちください':operation==='ack_receipt'?'工場の着金確認を保存しました。必要な前払額が揃ったら製造開始を記録してください':operation==='start_production'?'工場の製造開始を記録しました。営業が案件工程を確認します':'記録を保存しました。下の条件・履歴を確認してください');setChecked(false);router.refresh()}catch(e){setError(e instanceof Error?e.message:'保存を確認できません')}finally{setBusy(false)}}
 const next=!active?'取消済み・履歴確認':!c.agreement?latest?'営業の最終条件・銀行照合待ち':'工場の最終条件入力待ち':c.production?'製造中・完成証跡の準備':canStart?'工場の製造開始記録待ち':'工場の前払着金確認待ち'
 return <div className="space-y-4 text-[14px]">
 <section className="rounded-card border border-[#E2E1DA] bg-white p-4"><h2 className="font-bold">{c.order.order_no} · {c.order.snapshot.item_name||'発注商品'}</h2><p>{c.order.quantity}個 · 発注総額 USD {c.order.factory_total_usd}</p><p>担当工場 {c.factory_name}</p><p className="font-bold mt-2">次の対応：{next}</p><p className="text-[12px] mt-1">製造完了予定 {c.production?.expected_completion_on||'工場の開始日と合意日数の確定後に表示'} / 顧客希望納期 {c.order.expected_delivery_date||'未設定'}</p></section>
 {(error||request.error)&&<p role="alert" className="rounded-card border border-[#FF5C34] p-3">{error||request.error}</p>}
 {(success||request.recovered)&&<p role="status" className="rounded-card bg-[#D7EFFF] text-[#33566F] p-3">{success||'前回の保存結果が見つかりました。条件・履歴を確認してください。'}{request.recovered&&<button className={`${button} ml-2`} onClick={()=>{request.complete();router.refresh()}}>保存済み履歴を確認して続ける</button>}</p>}
 {!request.ready&&!request.error&&<p role="status">前回の保存結果を確認中…</p>}
 <details className="rounded-card border border-[#E2E1DA] p-4"><summary className="min-h-11 cursor-pointer font-bold">登録銀行情報・出所を確認</summary><p className="text-[12px] break-all">{c.registered_bank.source} / 工場登録情報更新 {c.registered_bank.updated_at}</p><p className="whitespace-pre-wrap break-all my-2">{c.registered_bank.data?.raw||'登録原文がありません。口座を推測せず営業担当へ確認してください。'}</p><p className="text-[12px]">銀行情報の新規登録・差替えや送金実行はこの画面では行いません。</p></details>
 {latest&&<section className="rounded-card bg-[#D7EFFF] text-[#33566F] p-4"><h2 className="font-bold">{c.agreement?'合意済み':'営業確認待ち'}条件 第{terms?.version||latest.version}版</h2><p>{factoryPaymentNames[(terms||latest).payment_mode]} · 前払 USD {(terms||latest).upfront_usd} / 総額 USD {(terms||latest).total_usd}</p><p>残金期限 {(terms||latest).balance_due==='before_shipment'?'出荷前':'納品後'} · 製造 {(terms||latest).lead_days}暦日</p><p className="whitespace-pre-wrap">{(terms||latest).note}</p></section>}
 {!c.agreement&&active&&(!staff?<form className="rounded-card border border-[#E2E1DA] bg-white p-4 space-y-3" onSubmit={e=>{e.preventDefault();void run('propose_terms',{total_usd:c.order.factory_total_usd,upfront_usd:upfront,payment_mode:mode,balance_due:balance,lead_days:days,note,expected_bank:c.registered_bank})}}><h2 className="font-bold">工場の最終条件を提示</h2><p className="text-[12px]">総額は発注書と同額です。変更が必要なら営業へ見積・発注の改訂を依頼してください。</p><label className="block">支払方法<select required className={field} value={mode} onChange={e=>setMode(e.target.value)}><option value="">選択してください</option><option value="full_prepaid">全額前払</option><option value="partial_prepaid">一部前払</option><option value="postpaid">納品後払</option></select></label><label className="block">製造前に必要な着金額（USD・後払は0を明示）<input required inputMode="decimal" pattern="[0-9]+([.][0-9]{1,4})?" className={field} value={upfront} onChange={e=>setUpfront(e.target.value)}/></label><label className="block">残金の支払時期<select required className={field} value={balance} onChange={e=>setBalance(e.target.value)}><option value="">選択してください</option><option value="before_shipment">出荷前</option><option value="after_delivery">納品後</option></select></label><label className="block">製造に必要な日数（暦日）<input required type="number" min="1" max="365" className={field} value={days} onChange={e=>setDays(e.target.value)}/></label><label className="block">条件・確認事項<textarea maxLength={2000} className={field} value={note} onChange={e=>setNote(e.target.value)}/></label><p className="text-[12px]">登録銀行原文が必要です。未登録・変更がある場合は営業へ確認してください。</p><button disabled={blocked||!bankPresent} className={`${button} bg-[#E9F056] text-[#666C14]`}>この最終条件を営業へ提示する</button></form>:latest?<form className="rounded-card border border-[#E2E1DA] bg-white p-4 space-y-3" onSubmit={e=>{e.preventDefault();void run('agree_terms',{terms_id:latest.id,expected_terms:latest,bank_verified:checked,bank_evidence:evidence,note})}}><h2 className="font-bold">最終条件と銀行の照合・同意</h2><label className="block">銀行登録元を照合した根拠（工場には非公開）<textarea required maxLength={2000} className={field} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><label className="block">取引条件への同意根拠<textarea required maxLength={2000} className={field} value={note} onChange={e=>setNote(e.target.value)}/></label><label className="min-h-11 flex items-center gap-2"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>登録銀行の原文・出所を照合した</label><p className="text-[12px]">上の条件版と銀行照合チェックが必要です。同意後の条件訂正は新見積・発注の整理が必要です。</p><button disabled={blocked||!checked||!bankPresent} className={`${button} bg-[#E9F056] text-[#666C14]`}>この条件と銀行確認を記録する</button></form>:<p>工場の条件提示をお待ちください。営業が工場の着金・同意を代行して記録することはできません。</p>)}
 {terms&&active&&<section className="rounded-card border border-[#E2E1DA] bg-white p-4 space-y-3"><h2 className="font-bold">{staff?'営業の手動送金実施記録':'工場の銀行着金確認'}</h2><p>工場着金確認済み USD {formatUsdUnits(confirmed)} / 製造前必要額 USD {terms.upfront_usd}</p><p className="text-[12px]">送金記録と工場着金確認は別です。銀行への送金処理は実行しません。</p>{(staff?transferOutstanding:pendingTransfers.length>0)?<form className="space-y-3" onSubmit={e=>{e.preventDefault();void run(staff?'report_transfer':'ack_receipt',staff?{amount_usd:amount,sent_on:date,reference,sent_confirmed:checked}:{report_id:report,amount_usd:amount,received_on:date,bank_reference:reference,bank_confirmed:checked})}}>
 {!staff&&<label className="block">営業の送金記録<select required className={field} value={report} onChange={e=>setReport(e.target.value)}><option value="">対象の記録を選択</option>{pendingTransfers.map(r=><option key={r.id} value={r.id}>{r.sent_on} · USD {r.amount_usd}</option>)}</select></label>}
 <label className="block">{staff?'実施した送金額':'銀行で確認した着金額'}（USD）<input required inputMode="decimal" pattern="[0-9]+([.][0-9]{1,4})?" className={field} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="block">{staff?'送金実施日':'銀行着金日'}<input required type="date" className={field} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="block">{staff?'送金証跡の一意な番号':'着金明細の一意な番号'}<input required maxLength={500} className={field} value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="flex items-center gap-2 min-h-11"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>{staff?'実際に手動送金を実施し証跡を確認した':'自社銀行明細で実際の着金を確認した'}</label><p className="text-[12px]">実確認チェックと未記録の残額が必要です。全額記録済み・未確認送金がない場合は追加保存できません。手数料や別通貨換算を推測しないでください。</p><button className={`${button} ${!staff&&!canStart&&!c.production?'bg-[#E9F056] text-[#666C14]':''}`} disabled={blocked||!checked||(staff?!transferOutstanding:!report||!pendingTransfers.some(r=>r.id===report))}>{staff?'送金実施を記録する':'銀行着金を確認して記録する'}</button></form>:<p className="text-[12px]">{staff?'合意総額の送金記録が揃っています。追加送金を推測して記録しません。':'未確認の送金記録はありません。追加送金が記録された場合に着金確認できます。'}</p>}</section>}
 {terms&&active&&!c.production&&!staff&&<form className="rounded-card border border-[#E2E1DA] bg-white p-4 space-y-3" onSubmit={e=>{e.preventDefault();void run('start_production',{started_on:date,note})}}><h2 className="font-bold">実際の製造開始を記録</h2><p className="text-[12px]">工場の前払着金確認が揃うまで開始できません。合意済み後払は前払0です。</p><label className="block">実際の製造開始日<input required type="date" className={field} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="block">開始の確認根拠<textarea required maxLength={2000} className={field} value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={blocked||!canStart} className={`${button} ${canStart?'bg-[#E9F056] text-[#666C14]':''}`}>製造開始を記録する</button></form>}
 {c.production&&staff&&<div><p>工場記録：開始 {c.production.started_on} / 完了予定 {c.production.expected_completion_on}</p>{['in_production','shipped','delivered'].includes(c.deal_status)?<p>案件への製造開始反映済みです。</p>:<><button disabled={blocked||c.deal_status!=='data_confirmed'} className={button} onClick={()=>void run('advance_production',{})}>全工場の開始を確認して案件工程へ反映</button><p className="text-[12px]">入稿確認済みで、全有効発注の工場開始記録がある場合だけ反映できます。</p></>}</div>}
 <details className="rounded-card border border-[#E2E1DA] p-4"><summary className="min-h-11 cursor-pointer font-bold">送金・着金履歴 {c.transfers.length}件 / {c.acknowledgments.length}件</summary>{c.transfers.map(r=><p key={r.id}>営業送金記録 {r.sent_on} · USD {r.amount_usd} · {r.reference}</p>)}{c.acknowledgments.map(r=><p key={r.id}>工場着金確認 {r.received_on} · USD {r.amount_usd} · {r.bank_reference}</p>)}{!c.transfers.length&&<p>送金記録はありません。支払済みとは表示しません。</p>}</details>
 </div>
}
