'use client'
import {useState} from 'react'
import {haiyuanSeaBase,haiyuanRoundedWeight} from '@/lib/calc/haiyuan-reference'
export function HaiyuanReference(){
 const [kg,setKg]=useState(''),[cbm,setCbm]=useState(''),[category,setCategory]=useState<'ordinary'|'sensitive'>('ordinary')
 const [route,setRoute]=useState<'dq'|'sea-ddp'|'air-ddp'>('dq'),[weights,setWeights]=useState('')
 const rounded=haiyuanRoundedWeight(weights.trim()?weights.trim().split(/[\s,、]+/).map(Number):[],route)
 const result=haiyuanSeaBase(Number(kg),Number(cbm),category),control='min-h-11 w-full min-w-0 rounded-input bg-[#EFEFEA] px-3'
 return <details className="rounded-card border border-[#E2E1DA] p-3"><summary className="min-h-11 cursor-pointer font-bold">海源・海運の基本送料を確認</summary><p className="text-xs my-3">2025-06-15料金表の基本部分だけ。1票にまとめる全商品の実重量・容積を合算してください。普通／敏感貨物は別送が原則。証書による例外は発送前に海源へ確認してください。追加料・特殊貨物・佐川加算は個別見積です。</p><div className="grid gap-3 sm:grid-cols-3"><label>1票の実重量（kg）<input className={control} type="number" min="0" step="any" value={kg} onChange={e=>setKg(e.target.value)}/></label><label>1票の容積（CBM）<input className={control} type="number" min="0" step="any" value={cbm} onChange={e=>setCbm(e.target.value)}/></label><label>票全体の区分<select aria-label="票全体の区分" className={control} value={category} onChange={e=>setCategory(e.target.value as typeof category)}><option value="ordinary">普通貨物・20 CNY/kg</option><option value="sensitive">敏感貨物・24 CNY/kg</option></select></label></div>{result?<p role="status" aria-label="海運基本送料の計算結果" className="mt-3 rounded-input bg-[#D7EFFF] text-[#33566F] p-3">基本部分 {result.baseCny.toLocaleString('ja-JP',{maximumFractionDigits:6})} CNY（端数処理前）／課金重量 {result.billableKg.toLocaleString('ja-JP',{maximumFractionDigits:6})} kg。max（実重量, CBM×167, 21 kg）。送料総額は未確定です。</p>:<p className="mt-3 text-xs">正の実重量と容積を入力すると基本部分を計算します。</p>}<div className="mt-4 border-t border-[#E2E1DA] pt-3"><h3 className="font-bold">物流確認済み重量の丸め</h3><p className="my-2 text-xs">実重量と容積重量の比較を海源が確認した計費重量を入力。DQは票全体を切上げ、包税海運／空運は箱ごとに切上げます。上の概算には自動適用しません。</p><label>丸めを確認する輸送経路<select className={control} value={route} onChange={e=>setRoute(e.target.value as typeof route)}><option value="dq">DQ快船・票全体</option><option value="sea-ddp">海運包税・箱ごと</option><option value="air-ddp">空運包税・箱ごと</option></select></label><label className="mt-3 block">確認済み計費重量（kg・箱ごとに改行）<textarea className={control} rows={3} value={weights} onChange={e=>setWeights(e.target.value)}/></label>{rounded!==null?<p role="status" aria-label="計費重量の丸め結果" className="mt-3 rounded-input bg-[#D7EFFF] p-3 text-[#33566F]">丸め後 {rounded.toLocaleString('ja-JP')} kg／{route==='dq'?'票全体':'箱ごと'}。料金総額は別途確認。</p>:<p className="mt-2 text-xs">各箱の正の重量を入力してください。</p>}<p className="mt-3 text-xs">DQ 7.5/KG・空運28／33/KGは料金表内の通貨未確認。DQ配送費の込み／別、佐川加算+1／+1.5は資料間で不一致のため個別見積。発送先・サイズ超過も発送前に確認してください。</p><p className="mt-2 text-xs">食品検査証書と日本の食品届は別です。自己申告時の先方手数料免除は対象費用を確認し、税金・検査費や届出義務の免除とは扱いません。</p></div><p className="mt-3 text-xs">air／DQ・食品検査費・国内送料には適用しません。見積費目には自動転記しません。海源が確認した総額をCNY費目へ入力し、FXとともに価格版を確認してください。</p></details>
}
