'use client'
import {useState,useTransition} from 'react'
import {useRouter} from 'next/navigation'
import {useWorkflowRequest} from '@/lib/hooks/use-workflow-request'
import {previewPricingRevision,savePricingRevision,fetchPricingReferenceFx} from '@/lib/actions/pricing-revision'
import {calculatePricingRevision,costKindNames,requiredCostKinds,type PricingRevisionInput} from '@/lib/calc/pricing-revision'
import type {BuilderQuote} from './quote-builder'
const control='min-w-0 min-h-11 w-full rounded-input bg-[#EFEFEA] px-3 border border-transparent focus:border-[#351E28]'
const button='min-h-11 rounded-full border border-[#E2E1DA] px-4 font-bold disabled:opacity-50'
export function PricingRevisionEditor({quote:q,dealId,onClose}:{quote:BuilderQuote;dealId:string;onClose:()=>void}){
 const router=useRouter(),recovery=useWorkflowRequest(`pricing/${dealId}/${q.id}`,'pricing_revision',dealId)
 const [pending,start]=useTransition(),[error,setError]=useState(''),[preview,setPreview]=useState<Record<string,unknown>|null>(null)
 const [input,setInput]=useState<PricingRevisionInput>({mode:'ratio',value:q.cost_ratio,tax_rate:null,fx:{rate:q.exchange_rate,reference:'',as_of:'',confirmed:false},cost_lines:requiredCostKinds.map(kind=>({key:kind,kind,name:costKindNames[kind],amount:kind==='plate'?q.plate_fee_usd:kind==='color'?q.pantone_color_fee_usd:kind==='domestic_freight'?q.domestic_china_freight_usd:kind==='international_freight'?q.china_freight_usd:q.other_fees_usd,currency:'USD',confirmed:false}))})
 const edit=(next:PricingRevisionInput)=>{setInput(next);setPreview(null);setError('')}
 const number=(v:string)=>v.trim()===''?null:Number(v)
 let draft:ReturnType<typeof calculatePricingRevision>|null=null,issue=''
 try{draft=calculatePricingRevision(q.quantity,q.factory_unit_price_usd,input)}catch(e){issue=e instanceof Error?e.message:'入力を確認してください'}
 const locked=pending||(recovery.unfinished&&!!preview),success=recovery.recovered
 return <div className="fixed inset-0 z-50 bg-[rgba(53,30,40,.35)] flex items-center justify-center p-3"><section role="dialog" aria-modal="true" aria-label="価格改訂の確認" className="w-full max-w-[860px] max-h-[90dvh] overflow-auto rounded-card bg-white p-4 text-[13px] whitespace-normal text-left">
 <div className="flex justify-between gap-3 mb-3"><h2 className="text-[15px] font-bold">価格を改訂して確認</h2><button type="button" className={button} onClick={onClose} disabled={pending}>閉じる</button></div>
 <p className="mb-3">旧価格・採用・発行済みPDFは変更しません。新しい未採用版を保存します。サンプル費は独立手配・後日請求へ記録し、量産原価に含めません。</p>
 {success?<div><p role="status">前回の価格版を保存済みです。見積履歴に戻って比較・採用してください。</p><button type="button" className={button} onClick={()=>{recovery.complete();router.refresh();onClose()}}>見積履歴へ戻る</button></div>:<>
 <fieldset disabled={locked} className="space-y-4 min-w-0">
 <div className="grid sm:grid-cols-3 gap-3"><label>入力する価格<select className={control} value={input.mode} onChange={e=>edit({...input,mode:e.target.value as PricingRevisionInput['mode'],value:null})}><option value="ratio">掛率（原価÷税抜売価）</option><option value="selling_price">税抜売単価（JPY/個）</option></select></label><label>{input.mode==='ratio'?'掛率（0より大きく1以下）':'税抜売単価（円・整数）'}<input className={control} type="number" step={input.mode==='ratio'?'any':'1'} value={input.value??''} onChange={e=>edit({...input,value:number(e.target.value)})}/></label><label>消費税率（%・0も明示）<input className={control} type="number" step="any" value={input.tax_rate??''} onChange={e=>edit({...input,tax_rate:number(e.target.value)})}/></label></div>
 <p>掛率は粗利率や原価の倍率とは別です。売価＝原価÷掛率。円単価は切上げ、税込総額は税抜総額に税率を適用して切上げます。</p>
 <h3 className="font-bold">見積用の参考FX</h3><p className="text-xs">日次参考値です。週末も取得元の基準日時を確認し、銀行の実決済レートと区別してください。取得しても旧見積・発行済みPDFは更新されません。</p><button type="button" className={button} onClick={()=>start(async()=>{try{const r=await fetchPricingReferenceFx();if(r.error)setError(r.error);else if(r.fx)edit({...input,fx:r.fx})}catch{setError('参考レートの取得結果を確認できません。再試行するか、確認済みの手入力レートを使用してください')}})}>公開日次参考レートを取得</button><a href="https://www.exchangerate-api.com" target="_blank" rel="noreferrer" className="underline text-xs ml-2">Rates By Exchange Rate API</a><div className="grid sm:grid-cols-2 gap-3"><label>レート（JPY/USD）<input className={control} type="number" step="any" value={input.fx.rate??''} onChange={e=>edit({...input,fx:{...input.fx,rate:number(e.target.value),confirmed:false}})}/></label><label>人民元レート（JPY/CNY・CNY費目を使う場合）<input className={control} type="number" step="any" value={input.fx.cny_jpy_rate??''} onChange={e=>edit({...input,fx:{...input.fx,cny_jpy_rate:number(e.target.value),confirmed:false}})}/></label><label>確認した取得元・根拠<input className={control} maxLength={500} value={input.fx.reference} onChange={e=>edit({...input,fx:{...input.fx,reference:e.target.value,confirmed:false}})}/></label><label>基準日時（タイムゾーン付ISO）<input className={control} placeholder="2026-10-01T00:00:00Z" value={input.fx.as_of} onChange={e=>edit({...input,fx:{...input.fx,as_of:e.target.value,confirmed:false}})}/></label><button className={button} type="button" onClick={()=>edit({...input,fx:{...input.fx,as_of:new Date().toISOString(),confirmed:false}})}>現在のUTC日時を入力</button></div><label className="flex gap-2 min-h-11 items-center"><input type="checkbox" checked={input.fx.confirmed} onChange={e=>edit({...input,fx:{...input.fx,confirmed:e.target.checked}})}/>レート・根拠・基準日時を確認しました</label>
 <h3 className="font-bold">量産費目（この数量の総額）</h3><p>不明額は空欄のままにし、確認まで保存しません。旧その他費用を追加費目へ分けた場合は、その他費用の行を0と確認してください。USD／JPY／CNY費目に対応。CNYは確認済みJPY/CNYで換算します。工場単価はUSD固定、未知の海源料金・税／DDPは自動補完しません。</p>
 {input.cost_lines.map((l,index)=><div key={l.key} className="grid sm:grid-cols-[2fr_1fr_1fr_1fr] gap-2 border-t border-[#E2E1DA] pt-3"><label>費目名<input className={control} value={l.name} readOnly={l.kind!=='custom'} onChange={e=>edit({...input,cost_lines:input.cost_lines.map((x,n)=>n===index?{...x,name:e.target.value,confirmed:false}:x)})}/></label><label>{l.name}の総額<input className={control} type="number" step="any" value={l.amount??''} onChange={e=>edit({...input,cost_lines:input.cost_lines.map((x,n)=>n===index?{...x,amount:number(e.target.value),confirmed:false}:x)})}/></label><label>{l.name}の通貨<select className={control} value={l.currency} onChange={e=>edit({...input,cost_lines:input.cost_lines.map((x,n)=>n===index?{...x,currency:e.target.value as 'USD'|'JPY'|'CNY',confirmed:false}:x)})}><option>USD</option><option>JPY</option><option>CNY</option></select></label><label className="min-h-11 flex items-center gap-2"><input type="checkbox" checked={l.confirmed} onChange={e=>edit({...input,cost_lines:input.cost_lines.map((x,n)=>n===index?{...x,confirmed:e.target.checked}:x)})}/>{l.name}を確認{l.kind==='custom'&&<button type="button" aria-label={`${l.name||'追加費目'}を削除`} onClick={()=>edit({...input,cost_lines:input.cost_lines.filter((_,n)=>n!==index)})}>削除</button>}</label></div>)}
 <button type="button" className={button} onClick={()=>edit({...input,cost_lines:[...input.cost_lines,{key:crypto.randomUUID(),kind:'custom',name:'',amount:null,currency:'USD',confirmed:false}]})}>追加費目を入力</button>
 </fieldset>
 {draft&&<p className="mt-4 rounded-card bg-[#D7EFFF] text-[#33566F] p-3">入力概算: 税抜単価 ¥{draft.selling_price_jpy.toLocaleString()} · 税抜合計 ¥{draft.total_billing_jpy.toLocaleString()} · 税込 ¥{draft.total_billing_tax_jpy.toLocaleString()} · 掛率 {draft.cost_ratio.toPrecision(6)}</p>}
 {(error||recovery.error)&&<p role="alert" className="mt-3">{error||recovery.error}</p>}
 {recovery.unfinished&&<div><p role="status">保存結果が未確認です。同じ入力で再試行するか、再読込して保存結果を確認してください。再入力する場合も元の内容を使い、変更前に見積履歴を確認してください。</p>{!preview&&<button type="button" className={button} onClick={()=>{recovery.complete();setError('')}}>見積履歴を確認済み・別の価格改訂を始める</button>}</div>}
 {preview?<div className="mt-4"><p className="font-bold">DB確認済み: 数量 {String(preview.quantity)}個 · 工場単価 {String(preview.factory_unit_price_usd)} USD · 税抜単価 ¥{String(preview.selling_price_jpy)} · 税抜総額 ¥{String(preview.total_billing_jpy)} · 税込総額 ¥{String(preview.total_billing_tax_jpy)}</p><button type="button" className={`${button} bg-[#E9F056] mt-3`} disabled={pending||!recovery.ready} onClick={()=>start(async()=>{try{const id=await recovery.requestId({quote_id:q.id,input,expected:preview});const r=await savePricingRevision(id,q.id,input,preview);if(r.error){setError(r.error);if(r.error.includes('元の見積が変わりました')){recovery.complete();setPreview(null)}return}recovery.complete();router.refresh();onClose()}catch{setError('保存結果を確認できません。同じ入力で再試行してください')}})}>この内容で新しい価格版を保存</button></div>:<div className="mt-4"><p role="status">{issue||'保存前にDBで原価・価格を確認してください'}</p><button type="button" className={`${button} bg-[#E9F056] mt-3`} disabled={pending||!!issue||!recovery.ready} onClick={()=>start(async()=>{try{const r=await previewPricingRevision(q.id,input);setPreview(r.preview);setError(r.error||'')}catch{setError('確認内容を取得できません。再試行してください')}})}>価格・費目を確認</button></div>}
 </>}
 </section></div>
}
