'use client'
import {useState,useTransition} from 'react'
import {useRouter} from 'next/navigation'
import {useWorkflowRequest} from '@/lib/hooks/use-workflow-request'
import {sampleCommand,previewSampleInvoice,previewSampleMail,sendSampleMail} from '@/lib/actions/sample-ledger'
import {sampleKindNames,sampleStatusNames,type SampleLedger,type SampleOperation,type SampleInvoiceSnapshot,type SampleMailPreview} from '@/lib/samples/types'
const control='min-h-11 min-w-0 w-full rounded-input bg-[#EFEFEA] px-3 border border-transparent focus:border-[#351E28]'
const button='min-h-11 rounded-full border border-[#E2E1DA] px-4 text-[13px] font-bold disabled:opacity-50'
const main=button+' bg-[#E9F056] text-[#666C14]'
const money=(n:string|number)=>`¥${Number(n).toLocaleString('ja-JP')}`
type Job={op:SampleOperation;input:Record<string,unknown>;expected:SampleInvoiceSnapshot|null}
export function SampleWorkbench({dealId,ledger:l}:{dealId:string;ledger:SampleLedger}){
 const router=useRouter(),recovery=useWorkflowRequest(`samples/${dealId}`,'sample_ledger',dealId)
 const [pending,start]=useTransition(),[tab,setTab]=useState('rounds'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState<SampleOperation|null>(null),[roundId,setRoundId]=useState(''),[search,setSearch]=useState('')
 const [job,setJob]=useState<Job|null>(null),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<SampleInvoiceSnapshot|null>(null),[invoiceInput,setInvoiceInput]=useState<Record<string,unknown>>({cost_ids:[],tax_rate:'',issue_date:'',due_date:'',payment_details:'',previous_invoice_id:''})
 const [mail,setMail]=useState<SampleMailPreview|null>(null)
 const billed=new Set(l.allocations.filter(a=>!a.released_at).map(a=>a.cost_id)),unbilled=l.costs.filter(c=>!c.voided_at&&!billed.has(c.id)),locked=pending||recovery.unfinished
 const matches=(...values:unknown[])=>values.map(String).join(' ').toLowerCase().includes(search.trim().toLowerCase())
 const visibleRounds=l.rounds.filter(r=>matches(r.round_number,sampleStatusNames[r.status],r.due_date,l.products.find(p=>p.id===r.product_id)?.description,l.variants.find(v=>v.id===r.variant_id)?.variant_label,l.factories.find(f=>f.id===r.factory_id)?.factory_name))
 const visibleCosts=unbilled.filter(c=>matches(sampleKindNames[c.kind],c.carrier,c.basis,l.rounds.find(r=>r.id===c.round_id)?.round_number))
 const visibleInvoices=l.invoices.filter(i=>matches(i.document_number,i.status==='cancelled'?'取消済み':'発行済み',i.snapshot.due_date,i.snapshot.customer_name))
 const clear=()=>{setError('');setNotice('');setPreview(null);setMail(null)}
 const run=(j:Job)=>{setJob(j);start(async()=>{try{const id=await recovery.requestId(j),r=await sampleCommand(id,dealId,j.op,j.input,j.expected);if(r.error){setError(r.error);return}recovery.complete();setJob(null);setForm(null);setPreview(null);setSelected([]);setSearch('');setNotice(j.op==='issue_invoice'?'請求書を確定しました。PDF・送付文面を確認してください':j.op==='cancel_invoice'?'取消を記録しました。未請求一覧から新しい請求書を作成できます':'記録を保存しました。次の作業を一覧で確認してください');router.refresh()}catch{setError('保存結果を確認できません。同じ要求で再試行するか再読込してください')}})}
 const open=(op:SampleOperation,id='')=>{clear();setRoundId(id);setForm(op)}
 const mutateForm=(f:HTMLFormElement)=>{const d=Object.fromEntries(new FormData(f).entries()) as Record<string,unknown>;if(form==='add_cost'){d.round_id=roundId;d.confirmed=d.confirmed==='on';d.fx={rate:d.rate,reference:d.fx_reference,as_of:d.as_of,confirmed:d.fx_confirmed==='on'};for(const k of ['rate','fx_reference','as_of','fx_confirmed'])delete d[k]}else if(form==='record_payment'||form==='set_status'||form==='record_estimate')d.round_id=roundId;if((form==='add_cost'||form==='record_estimate')&&((d.kind==='shipping'&&!['UPS','FedEx'].includes(String(d.carrier)))||(d.kind!=='shipping'&&d.carrier))){setError('送料の場合はUPS/FedExを選択し、製作費・版代は配送会社を選択なしにしてください');return}if(form==='add_cost'&&d.currency==='USD'){const fx=d.fx as Record<string,unknown>;if(!fx.confirmed||!Number.isFinite(Number(fx.rate))||Number(fx.rate)<=0||!String(fx.reference).trim()||!/(Z|[+-]\d{2}:\d{2})$/.test(String(fx.as_of))||!Number.isFinite(Date.parse(String(fx.as_of)))){setError('USD費用は手入力FXのレート・根拠・タイムゾーン付き日時を入力して確認してください');return}}if(form)run({op:form,input:d,expected:null})}
 return <div className="text-[13px] space-y-4">
 <p>量産見積とは別の手配・費用台帳です。顧客前払を待たず記録し、確定した未請求費用を後でまとめて請求します。</p>
 <nav aria-label="サンプル作業" className="flex flex-wrap gap-2">{[['rounds','手配・工場支払'],['costs',`未請求費用 ${unbilled.length}件`],['invoices','請求書履歴']].map(([key,label])=><button key={key} className={button+(tab===key?' bg-[#351E28] text-[#C9A2B8]':' bg-white')} disabled={locked} aria-pressed={tab===key} onClick={()=>{setTab(key);setForm(null);clear()}}>{label}</button>)}</nav>
 <label className="block max-w-[560px]">サンプル・工場・費目を検索<input type="search" className={control} value={search} onChange={e=>setSearch(e.target.value)} placeholder="商品・工場・回数・費目・請求番号"/></label>
 {(error||recovery.error)&&<p role="alert" className="border border-[#FF5C34] rounded-card p-3">{error||recovery.error}</p>}
 {pending&&<p role="status">処理中です。記録・履歴の確認が終わるまでお待ちください。</p>}
 {notice&&<p role="status">{notice}</p>}
 {recovery.recovered?<section className="rounded-card border border-[#E2E1DA] p-4"><p role="status">前回の保存を確認しました。記録ID {String(recovery.recovered.id)}。履歴から内容を確認してください。</p><button className={button} onClick={()=>{recovery.complete();setJob(null);router.refresh()}}>保存済み記録を確認した</button></section>:recovery.unfinished&&<section className="rounded-card border border-[#FF5C34] p-4"><p role="status">保存結果が未確認のため別の操作を止めています。入力を変えず再試行するか、再読込して保存結果を確認してください。</p>{job?<button className={main} disabled={pending} onClick={()=>run(job)}>同じ要求で再試行</button>:<button className={button} onClick={()=>{recovery.complete();setJob(null);router.refresh()}}>履歴を確認済み・未保存の要求を解除</button>}</section>}
 {!recovery.ready&&!recovery.error&&<p role="status">前回の保存結果を確認中…</p>}
 {search&&!(tab==='rounds'?visibleRounds.length:tab==='costs'?visibleCosts.length:visibleInvoices.length)&&<p role="status">検索条件に合う記録はありません。検索語を消して一覧を確認してください。</p>}
 {tab==='rounds'&&<>
 <div className="flex justify-between items-center gap-3"><h2 className="text-[15px] font-bold">手配ラウンド</h2>{!form&&<button className={main} disabled={locked||!recovery.ready||!l.variants.length||!l.factories.length} onClick={()=>open('create_round')}>次のサンプルを手配記録</button>}</div>
 {(!l.variants.length||!l.factories.length)&&<p>手配には案件の商品仕様と登録済み工場が必要です。案件の仕様・工場登録を先に確認してください。</p>}
 {!l.rounds.length&&<p className="rounded-card border border-[#E2E1DA] p-4">手配記録はまだありません。商品・仕様・工場・数量・期限を選び、1回目を記録してください。</p>}
 {visibleRounds.map(r=><article key={r.id} className="rounded-card border border-[#E2E1DA] bg-white p-4 space-y-2">
 <div className="flex flex-wrap justify-between gap-2"><h3 className="font-bold">{r.round_number}回目 · {l.products.find(p=>p.id===r.product_id)?.description||'商品'} / {l.variants.find(v=>v.id===r.variant_id)?.variant_label||'仕様'}</h3><span className="rounded-full bg-[#D7EFFF] text-[#33566F] px-3 py-1">{sampleStatusNames[r.status]}</span></div>
 <p>担当工場 {l.factories.find(f=>f.id===r.factory_id)?.factory_name} · {r.quantity}個 · 希望期限 {r.due_date}</p><p>{r.note}</p>
 <p className="text-[#84787D]">{({requested:'次の作業：担当工場の製作開始を確認して状態を記録',manufacturing:'次の作業：担当工場の発送を確認して状態を記録',shipping:'次の作業：サンプル到着を確認して状態を記録',arrived:'次の作業：仕上がりを確認してOKまたは修正要を記録',approved:'次の作業：未請求費用を確認',revision_requested:'次の作業：修正内容を確認して次のラウンドを手配'} as Record<string,string>)[r.status]}</p>
 <div className="flex flex-wrap gap-2"><button className={button} disabled={locked} onClick={()=>open('record_estimate',r.id)}>概算費用を記録</button><button className={button} disabled={locked} onClick={()=>open('add_cost',r.id)}>確定費用を記録</button><button className={button} disabled={locked} onClick={()=>open('record_payment',r.id)}>工場への支払を記録</button>{!['approved','revision_requested'].includes(r.status)&&<button className={button} disabled={locked} onClick={()=>open('set_status',r.id)}>状態を記録</button>}</div>
 <details><summary className="min-h-11 flex items-center cursor-pointer underline">費用・工場支払の履歴</summary>{l.estimates.filter(e=>e.round_id===r.id).map(e=><p key={e.id}>概算 {sampleKindNames[e.kind]} {e.carrier} · {e.amount} {e.currency} · {e.basis}（請求対象外）</p>)}{l.costs.filter(c=>c.round_id===r.id).map(c=><p key={c.id}>{sampleKindNames[c.kind]} {c.carrier} · 実費 {c.amount} {c.currency} / 概算 {c.estimate??'未記録'} · 顧客負担 {money(c.customer_charge_jpy)} · {c.voided_at?'費用取消済み':billed.has(c.id)?'請求済み':'未請求'}</p>)}{l.payments.filter(p=>p.round_id===r.id).map(p=><p key={p.id}>工場支払記録 {p.paid_on} · {p.amount} {p.currency} · {p.reference}</p>)}<p>支払記録は手動実施の証跡です。工場着金確認・顧客入金・顧客請求とは別です。</p></details>
 </article>)}
 </>}
 {form&&<section className="rounded-card border border-[#E2E1DA] p-4 bg-white"><div className="flex justify-between gap-2"><h2 className="text-[15px] font-bold">{form==='create_round'?'新しい手配ラウンド':form==='record_estimate'?'概算費用（請求対象外）':form==='add_cost'?'確定実費と顧客負担':form==='record_payment'?'手動で実施した工場支払の記録':'確認済み状態の記録'}</h2><button className={button} disabled={locked} onClick={()=>setForm(null)}>閉じる</button></div><form onSubmit={e=>{e.preventDefault();mutateForm(e.currentTarget)}}><fieldset disabled={locked||!recovery.ready} className="grid sm:grid-cols-2 gap-3 mt-4 min-w-0">
 {form==='create_round'&&<><label>対象仕様<select name="variant_id" required className={control} onChange={e=>{const v=l.variants.find(v=>v.id===e.target.value);const hidden=e.currentTarget.form?.elements.namedItem('product_id') as HTMLInputElement;if(hidden)hidden.value=v?.product_id||''}} defaultValue=""><option value="">仕様を選ぶ</option>{l.variants.map(v=><option value={v.id} key={v.id}>{l.products.find(p=>p.id===v.product_id)?.description} / {v.variant_label}</option>)}</select></label><input name="product_id" type="hidden"/><label>担当工場<select name="factory_id" required className={control} defaultValue=""><option value="">工場を選ぶ</option>{l.factories.map(f=><option key={f.id} value={f.id}>{f.factory_name}</option>)}</select></label><label>サンプル数量（個）<input name="quantity" type="number" min="1" step="1" required className={control}/></label><label>希望期限<input name="due_date" type="date" required className={control}/></label><label className="sm:col-span-2">手配内容・修正内容<textarea name="note" maxLength={2000} className={control}/></label></>}
 {(form==='add_cost'||form==='record_estimate')&&<><label>費目<select name="kind" className={control}><option value="manufacturing">製作費</option><option value="plate">版代</option><option value="shipping">サンプル送料</option></select></label><label>配送会社（送料の場合のみ）<select name="carrier" className={control}><option value="">送料以外は選択なし</option><option>UPS</option><option>FedEx</option></select></label>{form==='add_cost'&&<label>概算額（未記録なら空欄）<input name="estimate" type="number" min="0" step="any" className={control}/></label>}<label>{form==='record_estimate'?'概算額（0も明示）':'確定実費（0も明示）'}<input name="amount" type="number" min="0" step="any" required className={control}/></label><label>実費通貨<select name="currency" className={control}><option>JPY</option><option>USD</option></select></label>{form==='add_cost'&&<label>顧客負担額（税抜円・0も明示）<input name="customer_charge_jpy" type="number" min="0" step="1" required className={control}/></label>}<label className="sm:col-span-2">{form==='record_estimate'?'概算費用の根拠':'実費・負担額の確認根拠'}<textarea name="basis" maxLength={2000} required className={control}/></label>{form==='add_cost'&&<details className="sm:col-span-2"><summary className="min-h-11 cursor-pointer flex items-center underline">USD費用の手入力FX確認（USDの場合は必須）</summary><div className="grid sm:grid-cols-2 gap-3"><label>レート（JPY/USD）<input name="rate" type="number" step="any" min="0" className={control}/></label><label>為替の根拠<input name="fx_reference" className={control}/></label><label>為替基準日時（タイムゾーン付ISO）<input name="as_of" placeholder="2026-10-01T00:00:00Z" className={control}/></label><label className="min-h-11 flex items-center gap-2"><input name="fx_confirmed" type="checkbox"/>手入力FXを確認</label></div></details>}{form==='add_cost'&&<label className="sm:col-span-2 min-h-11 flex items-center gap-2"><input name="confirmed" type="checkbox" required/>概算ではなく、実費・顧客負担額を確認しました</label>}<p className="sm:col-span-2">量産価格へ加算しません。保存後の費用は上書きできません。誤りは未請求一覧で理由付き取消を記録し、正しい費用を新規記録してください。</p></>}
 {form==='record_payment'&&<><label>実施した支払額<input name="amount" type="number" min="0.01" step="any" required className={control}/></label><label>支払通貨<select name="currency" className={control}><option>USD</option><option>JPY</option></select></label><label>支払日<input name="paid_on" type="date" required className={control}/></label><label>支払証跡・参照番号<input name="reference" maxLength={2000} required className={control}/></label><p className="sm:col-span-2">実際の送金は行いません。実施済み支払の証跡だけを記録します。</p></>}
 {form==='set_status'&&<label>確認した状態<select name="status" className={control}>{(l.rounds.find(r=>r.id===roundId)?.status==='arrived'?['approved','revision_requested']:l.rounds.find(r=>r.id===roundId)?.status==='requested'?['manufacturing']:l.rounds.find(r=>r.id===roundId)?.status==='manufacturing'?['shipping']:['arrived']).map(s=><option key={s} value={s}>{sampleStatusNames[s]}</option>)}</select></label>}
 <button type="submit" className={main+' sm:col-span-2'}>この内容を記録</button></fieldset></form></section>}
 {tab==='costs'&&<>
 <h2 className="text-[15px] font-bold">未請求の確定費用 · 選択 {selected.length}件</h2>{!unbilled.length&&<p>未請求費用はありません。手配タブで確定実費を記録すると、ここから請求できます。</p>}
 <fieldset disabled={locked} className="space-y-3 min-w-0">{visibleCosts.map(c=><label key={c.id} className="flex items-start gap-3 p-4 rounded-card border border-[#E2E1DA] bg-white"><input type="checkbox" className="mt-1" checked={selected.includes(c.id)} onChange={e=>{const next=e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id);setSelected(next);setPreview(null)}}/><span>{l.rounds.find(r=>r.id===c.round_id)?.round_number}回目 · {sampleKindNames[c.kind]} {c.carrier}<br/>実費 {c.amount} {c.currency} · 顧客負担 {money(c.customer_charge_jpy)}<br/><span className="text-[#84787D]">{c.basis}</span></span></label>)}
 {!!unbilled.length&&<div className="grid sm:grid-cols-2 gap-3">{[['tax_rate','消費税率（%・0も明示）','number'],['issue_date','請求発行日','date'],['due_date','支払期限','date']].map(([key,label,type])=><label key={key}>{label}<input className={control} type={type} min={type==='number'?0:undefined} max={type==='number'?100:undefined} step="any" value={String(invoiceInput[key]||'')} onChange={e=>{setInvoiceInput({...invoiceInput,[key]:e.target.value});setPreview(null)}}/></label>)}<label>再発行元（取消済み請求のみ）<select className={control} value={String(invoiceInput.previous_invoice_id||'')} onChange={e=>{setInvoiceInput({...invoiceInput,previous_invoice_id:e.target.value});setPreview(null)}}><option value="">新規請求</option>{l.invoices.filter(i=>i.status==='cancelled').map(i=><option key={i.id} value={i.id}>{i.document_number}</option>)}</select></label><label className="sm:col-span-2">請求書に記載する振込案内<textarea maxLength={2000} className={control} value={String(invoiceInput.payment_details||'')} onChange={e=>{setInvoiceInput({...invoiceInput,payment_details:e.target.value});setPreview(null)}}/></label></div>}
 </fieldset>
 {!!unbilled.length&&<details><summary className="min-h-11 flex items-center underline cursor-pointer">誤記費用を理由付きで取消</summary><form className="grid sm:grid-cols-2 gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run({op:'void_cost',input:{cost_id:f.get('cost_id'),reason:f.get('reason')},expected:null})}}><label>未請求費用<select name="cost_id" className={control} disabled={locked}>{unbilled.map(c=><option value={c.id} key={c.id}>{l.rounds.find(r=>r.id===c.round_id)?.round_number}回目 {sampleKindNames[c.kind]} {money(c.customer_charge_jpy)}</option>)}</select></label><label>費用取消理由<input name="reason" maxLength={2000} required className={control} disabled={locked}/></label><button className={button} disabled={locked||!recovery.ready}>費用取消を記録</button><p>元の費用履歴は残し、請求対象から除外します。請求済み費用は先に請求書を取消してください。</p></form></details>}
 {!!unbilled.length&&!preview&&<><p>費用を選び、税率・発行日・支払期限・振込案内を入力して確認してください。プレビューでは費用を予約しません。</p><button className={main} disabled={locked||!selected.length||!recovery.ready} onClick={()=>start(async()=>{try{const i={...invoiceInput,cost_ids:selected},r=await previewSampleInvoice(dealId,i);setPreview(r.preview||null);setError(r.error||'')}catch{setError('プレビューを読み込めません。再試行してください')}})}>選択した費用の請求を確認</button></>}
 {preview&&<section className="rounded-card bg-[#D7EFFF] text-[#33566F] p-4 space-y-3"><h3 className="font-bold">請求確定前の確認</h3><p>{preview.customer_name} · {preview.lines.length}費目 · 発行日 {preview.issue_date} · 支払期限 {preview.due_date}</p>{preview.lines.map(line=><p key={line.cost_id}>{line.round_number}回目 · {line.product_description} / {line.variant_label} · {line.quantity}個 · {sampleKindNames[line.kind]} {line.carrier} · {money(line.customer_charge_jpy)}</p>)}<p>税抜 {money(preview.subtotal)} · 消費税 {preview.tax_rate}% {money(preview.tax)} · 税込 {money(preview.total)}</p><p>税の円未満は切上げ。実費・顧客負担額は確定時の値を保持し、再取得時に為替を変えません。</p><button className={main} disabled={locked||!recovery.ready} onClick={()=>run({op:'issue_invoice',input:{...invoiceInput,cost_ids:selected},expected:preview})}>この内容で請求書を確定</button></section>}
 </>}
 {tab==='invoices'&&<><h2 className="text-[15px] font-bold">請求書・取消履歴</h2>{!l.invoices.length&&<p>請求書はまだありません。未請求費用を選んでプレビューしてください。</p>}{visibleInvoices.map(i=><article key={i.id} className="rounded-card border border-[#E2E1DA] p-4 bg-white space-y-3"><h3 className="font-bold break-all">{i.document_number}</h3><p>{i.status==='cancelled'?'取消済み':l.mailReceipts.find(r=>r.invoice_id===i.id)?.status==='accepted'?'発行済み・メール受付済み（到達未確認）':l.mailReceipts.some(r=>r.invoice_id===i.id)?'発行済み・送信履歴を確認':'発行済み・未送信'} · {money(i.snapshot.total)} · 支払期限 {i.snapshot.due_date}</p>{i.cancellation_reason&&<p>取消理由 {i.cancellation_reason}</p>}{i.previous_invoice_id&&<p>再発行元 {l.invoices.find(b=>b.id===i.previous_invoice_id)?.document_number||i.previous_invoice_id}</p>}<div className="flex flex-wrap gap-2"><a href={`/api/sample-invoices/${i.id}/pdf`} className={button+' inline-flex items-center'} target="_blank" rel="noreferrer">保存済みPDFを確認</a>{i.status==='issued'&&<button className={button} disabled={locked} onClick={()=>start(async()=>{try{const r=await previewSampleMail(i.id);setMail(r.preview||null);setError(r.error||'')}catch{setError('送付文面を取得できません')}})}>送付文面・添付を確認</button>}</div>{i.status==='issued'&&<details><summary className="min-h-11 flex items-center cursor-pointer underline">理由を記録して取消</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run({op:'cancel_invoice',input:{invoice_id:i.id,reason:f.get('reason')},expected:null})}}><label>取消理由<input name="reason" maxLength={2000} required disabled={locked} className={control}/></label><p>送付済みの場合は先に相手と訂正を確認してください。旧PDFと履歴は残ります。</p><button className={button} disabled={locked||!recovery.ready}>取消を確定</button></form></details>}</article>)}</>}
 {!!l.legacy.length&&<details><summary className="min-h-11 cursor-pointer flex items-center underline">旧サンプル記録 {l.legacy.length}件（請求状態未確認）</summary><p>旧記録は新台帳へ自動移行・再請求しません。元資料と請求履歴を確認してください。保存済み額を再計算しません。</p>{l.legacy.map(s=><p key={s.id}>{s.round_number}回目 · 旧状態 {s.sample_status||'未記録'} · 製作費 {s.sample_production_fee_usd??'未記録'} USD · 送料 {s.sample_shipping_fee_usd??'未記録'} USD · 版代 {s.plate_fee_usd??'未記録'} USD · 保存済み円小計 {s.subtotal_jpy==null?'未記録':money(s.subtotal_jpy)}</p>)}</details>}
 {mail&&<section aria-label="サンプル請求メールプレビュー" className="rounded-card border border-[#E2E1DA] p-4 space-y-2"><h2 className="font-bold">送付文面の確認</h2><p className="break-all">送信元 {mail.from} · 宛先 {mail.to}</p><p className="break-all">件名 {mail.subject}</p><p className="whitespace-pre-wrap">{mail.body}</p><p className="break-all">添付 {mail.attachment}</p><p role="status">{mail.delivery}。API受付は到達・顧客入金の証拠ではありません。</p>{!mail.status&&<button className={main} disabled={pending} onClick={()=>start(async()=>{try{const r=await sendSampleMail(mail.id,mail.fingerprint);setError(r.error||'');if(r.status){setMail({...mail,status:r.status,delivery:r.status==='accepted'?'メールサービス受付済み（到達は未確認）':'送信結果未確認・再送停止'});router.refresh()}}catch{setError('送信結果を確認できません。履歴確認まで再送しないでください');setMail({...mail,status:'unknown',delivery:'送信結果未確認・再送停止'})}})}>この宛先へPDF添付を送信</button>}<button className={button} disabled={pending} onClick={()=>setMail(null)}>確認を閉じる</button></section>}
 </div>
}
