import {test,expect} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID as uuid} from 'node:crypto'
import {mkdir} from 'node:fs/promises'
const url=process.env.LOCAL_SUPABASE_URL!
if(url!=='http://127.0.0.1:55321')throw Error('Synthetic localhost only')
const admin=createClient(url,process.env.LOCAL_SUPABASE_SERVICE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
test('actual Auth chat: separate factory/client, plain text, unread, lost response recovery, no inherited write',async({page,context})=>{
 const checked=async(r:PromiseLike<any>)=>{const v=await r;if(v.error)throw Error(v.error.message);return v.data},sessions=new Map<string,any>(),clients=new Map<string,typeof admin>()
 const company=uuid(),foreign=uuid(),factory=uuid(),deal=uuid(),product=uuid(),variant=uuid()
 await checked(admin.from('clients').insert([{id:company,company_name:'Synthetic chat client'},{id:foreign,company_name:'Synthetic other client'}]));await checked(admin.from('factories').insert({id:factory,factory_name:'Synthetic chat factory',basic_info_completed:true}))
 for(const name of ['sales','client','foreign','factory','logistics']){const role=name==='foreign'?'client':name,email=`chat-${name}-${uuid()}@example.test`,password=uuid()+uuid(),u=await checked(admin.auth.admin.createUser({email,password,email_confirm:true}));await checked(admin.from('profiles').update({role,client_id:name==='client'?company:name==='foreign'?foreign:null,factory_id:name==='factory'?factory:null}).eq('id',u.user.id));const db=createClient(url,process.env.LOCAL_SUPABASE_ANON_KEY!,{auth:{persistSession:false,autoRefreshToken:false}}),login=await checked(db.auth.signInWithPassword({email,password}));sessions.set(name,login.session);clients.set(name,db)}
 await checked(admin.from('deals').insert({id:deal,deal_code:`CHAT-${deal.slice(0,8)}`,deal_name:'Synthetic case chat',client_id:company,sales_user_id:sessions.get('sales').user.id,simple_status:'data_confirmed',waiting_on:'us'}));await checked(admin.from('deal_products').insert({id:product,deal_id:deal,product_no:1,description:'Synthetic chat product'}));await checked(admin.from('deal_product_variants').insert({id:variant,product_id:product,variant_label:'Synthetic chat variant',variant_order:0}));await checked(clients.get('sales')!.rpc('sample_command',{p_request_id:uuid(),p_deal_id:deal,p_operation:'create_round',p_input:{product_id:product,variant_id:variant,factory_id:factory,quantity:2,due_date:'2026-10-20',note:'Synthetic chat eligible sample'},p_expected:null}))
 const staff=clients.get('sales')!,client=clients.get('client')!,factoryDb=clients.get('factory')!,room=await checked(staff.rpc('open_case_chat',{p_deal:deal,p_role:'client',p_peer:company})),factoryRoom=await checked(staff.rpc('open_case_chat',{p_deal:deal,p_role:'factory',p_peer:factory}))
 const key=uuid(),initial={p_request_id:key,p_room:room,p_content:'Synthetic staff hello'},sent=await checked(staff.rpc('send_case_chat',initial));expect(await checked(staff.rpc('send_case_chat',initial))).toEqual(sent);await checked(staff.rpc('send_case_chat',{p_request_id:uuid(),p_room:factoryRoom,p_content:'Synthetic factory private'}))
 const partner=uuid(),quote=uuid();await checked(admin.from('logistics_partners').insert({id:partner,partner_kind:'shipping',company_name:'Synthetic chat logistics',is_active:true}));await checked(admin.from('deal_quotes').insert({id:quote,deal_id:deal,variant_id:variant,factory_id:factory,status:'approved',quantity:2,factory_unit_price_usd:1,selling_price_jpy:300,total_billing_jpy:600,total_billing_tax_jpy:660,exchange_rate:150,cost_ratio:.5}));const order=(await checked(staff.rpc('create_factory_order_atomic',{p_quote_id:quote,p_factory_id:factory,p_order_no:`SYNTH-CHAT-${uuid()}`}))).orderId;await checked(admin.from('shipment_plans').insert({order_id:order,deal_id:deal,client_id:company,factory_id:factory,quantity:2,logistics_actor_id:sessions.get('logistics').user.id,partner_id:partner,snapshot:{synthetic_assignment:true},created_by:sessions.get('sales').user.id}));const logisticsRoom=await checked(staff.rpc('open_case_chat',{p_deal:deal,p_role:'logistics',p_peer:sessions.get('logistics').user.id}));await checked(staff.rpc('send_case_chat',{p_request_id:uuid(),p_room:logisticsRoom,p_content:'Synthetic logistics private'}));expect((await client.rpc('read_case_chat',{p_room:logisticsRoom})).error).not.toBeNull();expect((await factoryDb.rpc('read_case_chat',{p_room:logisticsRoom})).error).not.toBeNull();
 expect((await checked(client.rpc('list_case_chats',{}))).find((r:any)=>r.id===room).unread).toBe(1);expect((await factoryDb.rpc('read_case_chat',{p_room:room})).error).not.toBeNull();expect((await client.rpc('read_case_chat',{p_room:factoryRoom})).error).not.toBeNull();expect((await checked(clients.get('foreign')!.rpc('list_case_chats',{})))).toHaveLength(0);expect((await checked(clients.get('logistics')!.rpc('list_case_chats',{})))).toHaveLength(1);expect((await client.from('chat_messages').insert({room_id:room,content_original:'bypass'})).error).not.toBeNull();expect((await client.rpc('mark_case_chat_read',{p_room:room,p_sequence:999})).error).not.toBeNull()
 await context.route('**/*',r=>['127.0.0.1','localhost'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());const role=async(name:string)=>{await context.clearCookies();await context.addCookies([{name:'sb-127-auth-token',value:'base64-'+Buffer.from(JSON.stringify(sessions.get(name))).toString('base64url'),domain:'127.0.0.1',path:'/'}])}
 await role('client');await page.setViewportSize({width:390,height:844});await page.goto('/portal/messages');await expect(page.getByRole('heading',{name:'案件の会話',exact:true})).toBeVisible();await page.getByLabel('会話相手',{exact:true}).selectOption(room);await expect(page.getByText('Synthetic staff hello',{exact:true})).toBeVisible();await expect.poll(async()=> (await checked(client.rpc('list_case_chats',{}))).find((r:any)=>r.id===room).unread).toBe(0)
 const text='Synthetic <script>no execution</script> customer reply';await page.getByRole('textbox').fill(text);await expect(page.getByRole('button',{name:'この相手に送信'})).toBeEnabled();let resolve!:()=>void;const lost=new Promise<void>(r=>resolve=r)
 await page.route('**/*',async r=>{if(r.request().method()==='POST'&&r.request().headers()['next-action']){await r.fetch();await r.abort('failed');resolve()}else await r.fallback()});await page.getByRole('button',{name:'この相手に送信'}).click();await lost;await page.unroute('**/*');const pending=await page.evaluate(()=>Object.entries(sessionStorage).filter(([k])=>k.startsWith('baoflow-request:')).map(([,v])=>JSON.parse(v)));expect(pending).toHaveLength(1);expect(Object.keys(pending[0]).sort()).toEqual(['id','signature']);await page.reload();await page.getByLabel('会話相手',{exact:true}).selectOption(room);await expect(page.getByRole('status').filter({hasText:'前回の送信を確認しました'})).toBeVisible();await expect(page.getByText(text,{exact:true})).toBeVisible();expect(await checked(admin.from('chat_messages').select('id').eq('room_id',room).eq('content_original',text))).toHaveLength(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await mkdir('artifacts/chat-stage12',{recursive:true});await page.screenshot({path:'artifacts/chat-stage12/client-390.png',fullPage:false})
 await role('factory');await page.goto('/factory/messages');await page.getByLabel('会話相手',{exact:true}).selectOption(factoryRoom);await expect(page.getByText('Synthetic factory private',{exact:true})).toBeVisible();await expect(page.getByText(text,{exact:true})).toHaveCount(0);await page.screenshot({path:'artifacts/chat-stage12/factory-390.png',fullPage:false})
 await role('logistics');await page.goto('/logistics/messages');await page.getByLabel('会話相手',{exact:true}).selectOption(logisticsRoom);await expect(page.getByText('Synthetic logistics private',{exact:true})).toBeVisible();await page.getByRole('textbox').fill('Synthetic assigned logistics reply');await page.getByRole('button',{name:'この相手に送信'}).click();await expect(page.getByRole('status').filter({hasText:'送信しました'})).toBeVisible();await page.screenshot({path:'artifacts/chat-stage12/logistics-390.png',fullPage:false});expect((await clients.get('logistics')!.rpc('read_case_chat',{p_room:factoryRoom})).error).not.toBeNull();
 await role('sales');await page.goto(`/deals/${deal}`);await page.getByRole('button',{name:'会話・連絡記録を開く',exact:true}).click();await page.getByLabel('会話相手',{exact:true}).selectOption(room);await expect(page.getByText(text,{exact:true})).toBeVisible();await page.screenshot({path:'artifacts/chat-stage12/staff-case-390.png',fullPage:false});
 await page.goto(`/deals/${deal}/quote-builder`);await page.locator(`[data-quote-id="${quote}"]`).getByRole('button',{name:'価格を改訂して確認',exact:true}).click();const dialog=page.getByRole('dialog',{name:'価格改訂の確認',exact:true});await dialog.getByRole('button',{name:'公開日次参考レートを取得'}).click();await expect(dialog.getByLabel('確認した取得元・根拠',{exact:true})).toHaveValue(/ExchangeRate-API/);await expect(dialog.getByLabel('基準日時（タイムゾーン付ISO）',{exact:true})).toHaveValue(/T.*Z$/);expect(Number(await dialog.getByLabel('人民元レート（JPY\/CNY・CNY費目を使う場合）',{exact:true}).inputValue())).toBeGreaterThan(0);await expect(dialog.getByLabel('レート・根拠・基準日時を確認しました',{exact:true})).not.toBeChecked();await dialog.getByLabel('消費税率（%・0も明示）',{exact:true}).fill('10');for(const name of ['版代','色指定費','中国国内送料','国際送料','その他費用']){await dialog.getByLabel(name+'の総額',{exact:true}).fill('0');await dialog.getByLabel(name+'を確認',{exact:true}).check()}await dialog.getByRole('combobox',{name:'国際送料の通貨',exact:true}).selectOption('CNY');await dialog.getByLabel('国際送料の総額',{exact:true}).fill('5');await dialog.getByLabel('国際送料を確認',{exact:true}).check();await dialog.getByLabel('レート・根拠・基準日時を確認しました',{exact:true}).check();await dialog.getByRole('button',{name:'価格・費目を確認',exact:true}).click();await expect(dialog).toContainText('DB確認済み');await page.screenshot({path:'artifacts/chat-stage12/fx-reference-preview-390.png',fullPage:false});await dialog.getByRole('button',{name:'閉じる',exact:true}).click();
 const sameKey=uuid(),retry={p_request_id:sameKey,p_room:room,p_content:'Synthetic concurrent same request'};const simultaneous=await Promise.all([staff.rpc('send_case_chat',retry),staff.rpc('send_case_chat',retry)]);expect(simultaneous.every(r=>!r.error)).toBe(true);expect(simultaneous[0].data).toEqual(simultaneous[1].data);expect(await checked(admin.from('chat_messages').select('id').eq('id',sameKey))).toHaveLength(1);
 await checked(admin.from('profiles').update({client_id:foreign}).eq('id',sessions.get('client').user.id));expect((await client.rpc('send_case_chat',{p_request_id:uuid(),p_room:room,p_content:'Former client'})).error).not.toBeNull();expect((await checked(client.rpc('list_case_chats',{})))).toHaveLength(0)
 console.log('PASS actual Auth/PostgREST chat separation, customer/factory UI, unread and durable lost-response recovery')
})
