import {test,expect} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {mkdir,writeFile} from 'node:fs/promises'
const url=process.env.LOCAL_SUPABASE_URL!
if(url!=='http://127.0.0.1:55321')throw Error('Synthetic localhost only')
const admin=createClient(url,process.env.LOCAL_SUPABASE_SERVICE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
test('real invoice correction / immutable refund / renewed link / explicit resend; role isolation and Mailpit',async({page,context})=>{
 const checked=async(r:PromiseLike<any>)=>{const v=await r;if(v.error)throw Error(v.error.message);return v.data}
 const factory=randomUUID(),party=randomUUID(),other=randomUUID(),deal=randomUUID(),product=randomUUID(),variant=randomUUID(),quote=randomUUID(),sessions=new Map<string,any>(),clients=new Map<string,typeof admin>()
 await checked(admin.from('factories').insert({id:factory,factory_name:'Synthetic payment-terms factory'}))
 await checked(admin.from('clients').insert([{id:party,company_name:'Synthetic settlement customer',email:'settlement-customer@example.test'},{id:other,company_name:'Synthetic unrelated customer'}]))
 for(const role of ['sales','client','foreign','factory','logistics']){
 const email=`finance-${role}-${randomUUID()}@example.test`,password=randomUUID()+randomUUID(),u=await checked(admin.auth.admin.createUser({email,password,email_confirm:true}));await checked(admin.from('profiles').update({role:role==='foreign'?'client':role,client_id:role==='client'?party:role==='foreign'?other:null}).eq('id',u.user.id))
 const db=createClient(url,process.env.LOCAL_SUPABASE_ANON_KEY!,{auth:{persistSession:false,autoRefreshToken:false}}),login=await checked(db.auth.signInWithPassword({email,password}));sessions.set(role,login.session);clients.set(role,db)
 }
 await checked(admin.from('deals').insert({id:deal,deal_code:`FIN-${deal.slice(0,8)}`,deal_name:'Synthetic settlement workflow',client_id:party,client_name_text:'Synthetic settlement customer',sales_user_id:sessions.get('sales').user.id,simple_status:'quoting',waiting_on:'us'}))
 await checked(admin.from('deal_products').insert({id:product,deal_id:deal,product_no:1,description:'Synthetic product'}));await checked(admin.from('deal_product_variants').insert({id:variant,product_id:product,variant_label:'Synthetic specification',variant_order:0}))
 const q={id:quote,deal_id:deal,variant_id:variant,status:'approved',quantity:2,selling_price_jpy:500,total_billing_jpy:1000,total_billing_tax_jpy:1100,factory_unit_price_usd:1,exchange_rate:150,cost_ratio:0.5}
 await checked(admin.from('deal_quotes').insert(q))
 const snapshot={deal:{id:deal,client_id:party,deal_name:'Synthetic settlement workflow',deal_code:'FIN-SYNTH',client_name_text:'Synthetic settlement customer'},quotes:[q],products:[{id:product,description:'Synthetic product'}],variants:[{id:variant,product_id:product,variant_label:'Synthetic specification'}],fees:[],company:{name:'Synthetic issuer',registration_number:'T0000000000000'},banks:[{bank_name:'Synthetic bank',account_number:'0000000'}]}
 const issueSyntheticDocument=async(type:string)=>{const id=randomUUID();await checked(admin.from('documents').insert({id,deal_id:deal,document_type:type,document_number:`SYNTH-${id}`,version:1,issued_at:new Date().toISOString(),issued_by_user_id:sessions.get('sales').user.id,metadata:{snapshot,payment_due_date:'2026-10-31'}}));return id}
 const sales=clients.get('sales')!,customer=clients.get('client')!,cmd=(db:typeof admin,operation:string,input:unknown,id=randomUUID())=>checked(db.rpc('client_finance_command',{p_request_id:id,p_operation:operation,p_input:input}))
 const publish=async(id:string,approval:string|null=null)=>{const expected=await checked(sales.rpc('preview_client_document_with_terms',{p_document_id:id,p_approval_packet_id:approval,p_mode:'half_prepaid',p_balance:'before_shipment'}));return cmd(sales,'publish_document',{document_id:id,approval_packet_id:approval,expected})}
 const quotedoc=await issueSyntheticDocument('quotation')
 await context.route('**/*',route=>['127.0.0.1','localhost'].includes(new URL(route.request().url()).hostname)?route.continue():route.abort())
 const role=async(name:string)=>{await context.clearCookies();await context.addCookies([{name:'sb-127-auth-token',value:'base64-'+Buffer.from(JSON.stringify(sessions.get(name))).toString('base64url'),domain:'127.0.0.1',path:'/'}])}
 await role('sales');await page.goto(`/deals/${deal}/settlement`);await page.getByLabel('発行済み見積書・請求書').selectOption(quotedoc);await page.getByLabel('顧客へ提示する支払条件').selectOption('half_prepaid');await page.getByLabel('残金の期限').selectOption('before_shipment');await page.getByRole('button',{name:'顧客向け内容を確認'}).click();await expect(page.getByText('支払条件：半金前払い',{exact:false})).toBeVisible();await page.getByRole('button',{name:'この発行版を共有する'}).click();await expect.poll(async()=>(await checked(admin.from('client_document_packets').select('id').eq('document_id',quotedoc))).length).toBe(1);const shared=(await checked(admin.from('client_document_packets').select('id').eq('document_id',quotedoc)))[0],sharedLink=(await checked(admin.from('client_document_links').select('token').eq('packet_id',shared.id)))[0],quotation={packet_id:shared.id,token:sharedLink.token}
 await role('client');await page.goto(`/portal/documents/${quotation.packet_id}?token=${quotation.token}`);await expect(page.getByText('支払条件：半金前払い',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'この版を承認する'})).toBeDisabled();await page.getByLabel('数量・仕様・税込金額・支払条件を確認しました').check();await expect(page.getByRole('button',{name:'この版を承認する'})).toBeEnabled();await page.getByRole('button',{name:'この版を承認する'}).click();await expect(page.getByText('回答済み：承認・営業確認待ち')).toBeVisible()
 await cmd(sales,'advance_quote',{packet_id:quotation.packet_id});const invoice=await publish(await issueSyntheticDocument('invoice'),quotation.packet_id)
 await page.goto(`/portal/documents/${invoice.packet_id}?token=${invoice.token}`);await page.getByLabel('振込金額（円）').fill('550');await page.getByLabel('振込日',{exact:true}).fill('2026-10-01');await page.getByLabel('振込名義・確認用情報').fill('Synthetic remittance')
 await expect(page.getByRole('button',{name:'入金を申告する'})).toBeEnabled()
 let resolve!:()=>void;const lost=new Promise<void>(r=>resolve=r)
 await page.route('**/*',async route=>{if(route.request().method()==='POST'&&route.request().headers()['next-action']){await route.fetch();await route.abort('failed');resolve()}else await route.fallback()})
 await page.getByRole('button',{name:'入金を申告する'}).click();await lost;await page.unroute('**/*')
 const pending=await page.evaluate(()=>Object.entries(sessionStorage).filter(([k])=>k.startsWith('baoflow-request:')).map(([,v])=>JSON.parse(v)))
 expect(pending).toHaveLength(1);expect(Object.keys(pending[0]).sort()).toEqual(['id','signature'])
 await page.reload();await expect(page.getByRole('status').filter({hasText:'前回の保存結果が見つかりました'})).toBeVisible();await page.getByRole('button',{name:'履歴を確認して続ける'}).click()
 await mkdir('artifacts/client-payment-conditions-stage8',{recursive:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/client-payment-conditions-stage8/client-report-recovered-390.png'})
 expect(await checked(admin.from('client_payment_reports').select('id').eq('packet_id',invoice.packet_id))).toHaveLength(1)
 expect((await checked(admin.from('deals').select('simple_status').eq('id',deal).single())).simple_status).toBe('quote_confirmed')
 expect((await sales.rpc('create_factory_order_atomic',{p_quote_id:quote,p_factory_id:factory,p_order_no:`SYNTH-BLOCKED-${randomUUID()}`})).error).not.toBeNull()
 const report=(await checked(admin.from('client_payment_reports').select('*').eq('packet_id',invoice.packet_id)))[0]
 await role('sales');await page.goto(`/deals/${deal}/settlement`);await page.getByLabel('確認する申告').selectOption(report.id);await page.getByLabel('銀行で確認した着金額（円）').fill('550');await page.getByLabel('実着金日').fill('2026-10-01');await page.getByLabel('銀行明細の一意な照合番号').fill(`SYNTH-${randomUUID()}`);await expect(page.getByRole('button',{name:'実着金を記録する'})).toBeDisabled();await page.getByLabel('実際の銀行明細で着金を確認した').check();await page.getByRole('button',{name:'実着金を記録する'}).click();await expect(page.getByText('入金申告 0件・BAO確認待ち')).toBeVisible()

 const replacementDoc=await issueSyntheticDocument('invoice');await page.reload()
 const correction=page.locator('details').filter({hasText:'訂正・期限切れリンク・再送・返金記録'});await correction.locator('summary').click()
 await correction.getByLabel('対象の有効版').selectOption(invoice.packet_id);await correction.getByLabel('対応',{exact:true}).selectOption('reissue_invoice');await correction.getByLabel('対応理由').fill('Synthetic same-obligation correction');await correction.getByLabel('新しく発行した請求書').selectOption(replacementDoc);await correction.getByRole('button',{name:'訂正版を確認',exact:true}).click();await expect(correction.getByText('支払条件：半金前払い',{exact:false})).toBeVisible();await correction.getByLabel('同じ請求の置換であり二重請求ではない').check();await correction.getByRole('button',{name:'旧版を残して訂正版を共有する'}).click()
 await expect.poll(async()=>(await checked(admin.from('client_document_packets').select('id').eq('document_id',replacementDoc))).length).toBe(1)
 const replacement=(await checked(admin.from('client_document_packets').select('id').eq('document_id',replacementDoc)))[0]
 expect((await checked(customer.rpc('client_finance_context',{p_packet_id:replacement.id}))).confirmed_jpy).toBe('550');expect((await checked(admin.from('client_payment_receipts').select('packet_id').eq('packet_id',invoice.packet_id)))[0].packet_id).toBe(invoice.packet_id)
 await role('client');await page.goto(`/portal/documents/${invoice.packet_id}`);await expect(page.getByText('旧版・支払や承認には使用しないでください。',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'入金を申告する'})).toHaveCount(0);expect((await context.request.get(`/api/client-documents/${invoice.packet_id}/pdf`)).status()).toBe(200);expect((await context.request.get(`/api/client-documents/${invoice.packet_id}/pdf?token=wrong`)).status()).toBe(404)
 await role('sales');await page.goto(`/deals/${deal}/settlement`);await correction.locator('summary').click();await correction.getByLabel('対象の有効版').selectOption(replacement.id);await correction.getByLabel('対応',{exact:true}).selectOption('record_refund');await correction.getByLabel('対応理由').fill('Synthetic actual manual refund');await correction.getByLabel('実際に返金した金額（円）').fill('100');await correction.getByLabel('銀行で実施した返金日').fill('2026-10-01');await correction.getByLabel('銀行明細の一意な照合番号').fill(`SYNTH-REFUND-${randomUUID()}`);await correction.getByLabel('銀行明細で実施済みの返金を確認した').check();await correction.getByRole('button',{name:'実施済み返金を記録する'}).click();await expect(correction.getByText('差引着金 ¥450',{exact:false})).toBeVisible()
 expect((await checked(customer.rpc('client_finance_context',{p_packet_id:replacement.id}))).confirmed_jpy).toBe('450');await expect(cmd(sales,'advance_paid',{packet_id:replacement.id})).rejects.toThrow()
 await checked(admin.from('client_document_links').update({revoked_at:new Date().toISOString()}).eq('packet_id',replacement.id));await page.reload();await correction.locator('summary').click();await correction.getByLabel('対象の有効版').selectOption(replacement.id);await correction.getByRole('button',{name:'リンクを更新する',exact:true}).click();await expect(correction.getByRole('status').filter({hasText:'保存済み。共有リンク'})).toBeVisible()
 await page.getByText('共有版のPDF・メール送付',{exact:true}).click();await page.getByRole('button',{name:'メール内容を確認',exact:true}).first().click();const mail=page.getByRole('region',{name:'メール送信前確認'});await mail.getByRole('button',{name:'確認した宛先へPDFを送付する'}).click();await expect(mail).toContainText('メールサービス受付済み')
 // First visible active packet is the replacement invoice (latest issued).
 const originalMail=await checked(admin.from('client_document_mail_receipts').select('provider_id').eq('packet_id',replacement.id).single());expect(originalMail.provider_id).toBeTruthy()
 await page.getByRole('button',{name:'確認を閉じる'}).click();await correction.getByLabel('対応',{exact:true}).selectOption('resend');await correction.getByLabel('対応理由').fill('Synthetic recipient explicitly requested another copy');await correction.getByRole('button',{name:'再送内容を確認',exact:true}).click();await expect(correction).toContainText('settlement-customer@example.test');await correction.getByLabel('顧客の明示的な再送依頼と宛先・添付を確認した').check();await correction.getByRole('button',{name:'確認したPDFを再送する'}).click();await expect(correction.getByRole('status').filter({hasText:'メールサービス受付済み'})).toBeVisible()
 const outcomes=await checked(admin.from('client_finance_requests').select('result').eq('operation','finish_document_resend').contains('payload',{packet_id:replacement.id}));expect(outcomes).toHaveLength(1);const captured=await(await fetch(`http://127.0.0.1:55324/api/v1/message/${outcomes[0].result.provider_id}`)).json();expect(captured.To[0].Address).toBe('settlement-customer@example.test');expect(captured.Text).toContain('1,100');expect(captured.Text).toContain('2026-10-31');const pdf=await context.request.get(`/api/client-documents/${replacement.id}/pdf`),attached=Buffer.from(await(await fetch(`http://127.0.0.1:55324/api/v1/message/${outcomes[0].result.provider_id}/part/${captured.Attachments[0].PartID}`)).arrayBuffer());expect(attached.equals(await pdf.body())).toBe(true)
 await mkdir('artifacts/client-corrections-stage10',{recursive:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'artifacts/client-corrections-stage10/staff-corrections-390.png'})
 for(const name of ['foreign','factory','logistics']){await role(name);expect((await context.request.get(`/api/client-documents/${replacement.id}/pdf`)).status()).toBe(404);expect((await clients.get(name)!.rpc('staff_client_finance_summary',{p_deal_id:deal})).error).not.toBeNull()}
})
