import {test,expect} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {mkdir,writeFile} from 'node:fs/promises'
import {frozenFxNote} from '../../src/lib/calc/fx-reference'
const url=process.env.LOCAL_SUPABASE_URL!
if(url!=='http://127.0.0.1:55321')throw Error('Synthetic localhost only')
const admin=createClient(url,process.env.LOCAL_SUPABASE_SERVICE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
test('real multi-product quantity/factory RFQ price renegotiation → customer reapproval → invoice cash carry',async({page,context})=>{
 const checked=async(r:PromiseLike<any>)=>{const v=await r;if(v.error)throw Error(v.error.message);return v.data}
 const factory=randomUUID(),party=randomUUID(),other=randomUUID(),deal=randomUUID(),product=randomUUID(),variant=randomUUID(),quote=randomUUID(),sessions=new Map<string,any>(),clients=new Map<string,typeof admin>()
 await checked(admin.from('factories').insert({id:factory,factory_name:'Synthetic payment-terms factory',basic_info_completed:true,contact_email:'factory-a@example.test'}))
 await checked(admin.from('clients').insert([{id:party,company_name:'Synthetic settlement customer',email:'settlement-customer@example.test'},{id:other,company_name:'Synthetic unrelated customer'}]))
 for(const role of ['sales','client','foreign','factory','logistics']){
 const email=`finance-${role}-${randomUUID()}@example.test`,password=randomUUID()+randomUUID(),u=await checked(admin.auth.admin.createUser({email,password,email_confirm:true}));await checked(admin.from('profiles').update({role:role==='foreign'?'client':role,client_id:role==='client'?party:role==='foreign'?other:null}).eq('id',u.user.id))
 const db=createClient(url,process.env.LOCAL_SUPABASE_ANON_KEY!,{auth:{persistSession:false,autoRefreshToken:false}}),login=await checked(db.auth.signInWithPassword({email,password}));sessions.set(role,login.session);clients.set(role,db)
 }
 await checked(admin.from('deals').insert({id:deal,deal_code:`FIN-${deal.slice(0,8)}`,deal_name:'Synthetic settlement workflow',client_id:party,client_name_text:'Synthetic settlement customer',sales_user_id:sessions.get('sales').user.id,simple_status:'quoting',waiting_on:'us'}))
 await checked(admin.from('deal_products').insert({id:product,deal_id:deal,product_no:1,description:'Synthetic product'}));await checked(admin.from('deal_product_variants').insert({id:variant,product_id:product,variant_label:'Synthetic specification',variant_order:0}))
 const q={id:quote,deal_id:deal,variant_id:variant,status:'approved',quantity:2,selling_price_jpy:500,total_billing_jpy:1000,total_billing_tax_jpy:1100,factory_unit_price_usd:1,exchange_rate:150,cost_ratio:0.5}
 await checked(admin.from('deal_quotes').insert(q))
 const snapshot={deal:{id:deal,client_id:party,deal_name:'Synthetic settlement workflow',deal_code:'FIN-SYNTH',client_name_text:'Synthetic settlement customer'},quotes:[q],products:[{id:product,description:'Synthetic product'}],variants:[{id:variant,product_id:product,variant_label:'Synthetic specification'}],fees:[],company:{name:'Synthetic issuer',registration_number:'T0000000000000'},banks:[{bank_name:'Synthetic bank',account_number:'0000000'}]}
 const issueSyntheticDocument=async(type:string)=>{const id=randomUUID();await checked(admin.from('documents').insert({id,deal_id:deal,document_type:type,document_number:`SYNTH-${id}`,version:1,issued_at:new Date().toISOString(),issued_by_user_id:sessions.get('sales').user.id,metadata:{snapshot,payment_due_date:'2026-10-31'}}));return id}
 const sales=clients.get('sales')!,customer=clients.get('client')!,cmd=(db:typeof admin,operation:string,input:unknown,id=randomUUID())=>checked(db.rpc('client_finance_command',{p_request_id:id,p_operation:operation,p_input:input}))
 const publish=async(id:string,approval:string|null=null)=>{const expected=await checked(sales.rpc('preview_client_document_with_terms',{p_document_id:id,p_approval_packet_id:approval,p_mode:'half_prepaid',p_balance:'before_shipment'}));return cmd(sales,'publish_document',{document_id:id,approval_packet_id:approval,expected})}
 const quotedoc=await issueSyntheticDocument('quotation')
 await context.route('**/*',route=>['127.0.0.1','localhost'].includes(new URL(route.request().url()).hostname)?route.continue():route.abort())
 const role=async(name:string)=>{await context.clearCookies();await context.addCookies([{name:'sb-127-auth-token',value:'base64-'+Buffer.from(JSON.stringify(sessions.get(name))).toString('base64url'),domain:'127.0.0.1',path:'/'}])}
 await role('sales');await page.goto(`/deals/${deal}/settlement`);await page.getByLabel('発行済み見積書・請求書').selectOption(quotedoc);await page.getByLabel('顧客へ提示する支払条件').selectOption('half_prepaid');await page.getByLabel('残金の期限').selectOption('before_shipment');await page.getByRole('button',{name:'顧客向け内容を確認'}).click();await expect(page.getByText('支払条件：半金前払い',{exact:false})).toBeVisible();await page.getByRole('button',{name:'この発行版を共有する'}).click();await expect.poll(async()=>(await checked(admin.from('client_document_packets').select('id').eq('document_id',quotedoc))).length).toBe(1);const shared=(await checked(admin.from('client_document_packets').select('id').eq('document_id',quotedoc)))[0],sharedLink=(await checked(admin.from('client_document_links').select('token').eq('packet_id',shared.id)))[0],quotation={packet_id:shared.id,token:sharedLink.token}
 await role('client');await page.goto(`/portal/documents/${quotation.packet_id}?token=${quotation.token}`);await expect(page.getByText('支払条件：半金前払い',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'この版を承認する'})).toBeDisabled();await page.getByLabel('数量・仕様・税込金額・支払条件を確認しました').check();await expect(page.getByRole('button',{name:'この版を承認する'})).toBeEnabled();await page.getByRole('button',{name:'この版を承認する'}).click();await expect(page.getByText('回答済み：承認・営業確認待ち')).toBeVisible()
 await cmd(sales,'advance_quote',{packet_id:quotation.packet_id});const invoice=await publish(await issueSyntheticDocument('invoice'),quotation.packet_id)
 await page.goto(`/portal/documents/${invoice.packet_id}?token=${invoice.token}`);await page.getByLabel('振込金額（円）').fill('550');await page.getByLabel('振込日',{exact:true}).fill('2026-10-01');await page.getByLabel('振込名義・確認用情報').fill('Synthetic remittance')
 await expect(page.getByRole('button',{name:'入金を申告する'})).toBeEnabled()
 let resolve!:()=>void;const lost=new Promise<void>(r=>resolve=r)
 await page.route('**/*',async route=>{if(route.request().method()==='POST'&&route.request().headers()['next-action']){await route.fetch();await route.abort('failed');resolve()}else await route.fallback()})
 await page.getByRole('button',{name:'入金を申告する'}).click();await lost;await page.unroute('**/*')
 const pending=await page.evaluate(()=>Object.entries(sessionStorage).filter(([k])=>k.startsWith('baoflow-request:')).map(([,v])=>JSON.parse(v)))
 expect(pending).toHaveLength(1);expect(Object.keys(pending[0]).sort()).toEqual(['id','signature'])
 await page.reload();await expect(page.getByRole('status').filter({hasText:'前回の保存結果が見つかりました'})).toBeVisible();await page.getByRole('button',{name:'履歴を確認して続ける'}).click()
 await mkdir('artifacts/release-final-audit',{recursive:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/release-final-audit/client-report-recovered-390.png'})
 expect(await checked(admin.from('client_payment_reports').select('id').eq('packet_id',invoice.packet_id))).toHaveLength(1)
 expect((await checked(admin.from('deals').select('simple_status').eq('id',deal).single())).simple_status).toBe('quote_confirmed')
 expect((await sales.rpc('create_factory_order_atomic',{p_quote_id:quote,p_factory_id:factory,p_order_no:`SYNTH-BLOCKED-${randomUUID()}`})).error).not.toBeNull()
 const report=(await checked(admin.from('client_payment_reports').select('*').eq('packet_id',invoice.packet_id)))[0]
 await role('sales');await page.goto(`/deals/${deal}/settlement`);await page.getByLabel('確認する申告').selectOption(report.id);await page.getByLabel('銀行で確認した着金額（円）').fill('550');await page.getByLabel('実着金日').fill('2026-10-01');await page.getByLabel('銀行明細の一意な照合番号').fill(`SYNTH-${randomUUID()}`);await expect(page.getByRole('button',{name:'実着金を記録する'})).toBeDisabled();await page.getByLabel('実際の銀行明細で着金を確認した').check();await page.getByRole('button',{name:'実着金を記録する'}).click();await expect(page.getByText('入金申告 0件・BAO確認待ち')).toBeVisible()


 const product2=randomUUID(),variant2=randomUUID(),factory2=randomUUID();await checked(admin.from('factories').insert({id:factory2,factory_name:'Synthetic second renegotiation factory',basic_info_completed:true,contact_email:'factory-b@example.test'}));await checked(admin.from('deal_products').insert({id:product2,deal_id:deal,product_no:2,description:'Synthetic second product'}));await checked(admin.from('deal_product_variants').insert({id:variant2,product_id:product2,variant_label:'Synthetic second specification',variant_order:0}));await checked(admin.from('deal_quotes').insert([{deal_id:deal,variant_id:variant,quantity:4,status:'drafting'},{deal_id:deal,variant_id:variant2,quantity:5,status:'drafting'},{deal_id:deal,variant_id:variant2,quantity:8,status:'drafting'}]))
 const rfq=await checked(sales.rpc('create_rfq_atomic',{p_request_id:randomUUID(),p_deal_id:deal,p_product_ids:[product,product2],p_factory_ids:[factory,factory2],p_pending_factories:[]}));expect(rfq.invitations).toHaveLength(2)
 const anonymous=createClient(url,process.env.LOCAL_SUPABASE_ANON_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
 for(const invitation of rfq.invitations){await checked(anonymous.rpc('ext_submit_rfq',{p_token:invitation.formToken,p_payload:{products:[{product_id:product,variant_id:variant,unit_price_usd:1,moq:1,pcs_per_carton:2,carton_w_cm:10,carton_h_cm:20,carton_d_cm:30,gross_weight_kg:1,production_lead_days:5},{product_id:product2,variant_id:variant2,unit_price_usd:0.5,moq:1,pcs_per_carton:4,carton_w_cm:10,carton_h_cm:20,carton_d_cm:30,gross_weight_kg:1,production_lead_days:7}]}}))}
 const answers=await checked(admin.from('deal_quotes').select('*').eq('deal_id',deal).eq('source_type','rfq_response'));expect(answers).toHaveLength(8)
 const candidates=[answers.find((q:any)=>q.variant_id===variant&&q.factory_id===factory&&q.quantity===4),answers.find((q:any)=>q.variant_id===variant2&&q.factory_id===factory2&&q.quantity===8)],chosen=[]
 for(const [i,candidate] of candidates.entries()){
  expect(candidate).toBeTruthy();const input={mode:'selling_price',value:i===0?700:400,tax_rate:10,fx:{rate:150,cny_jpy_rate:20,reference:'ExchangeRate-API daily reference',as_of:new Date(Math.floor(Date.now()/86400000)*86400000).toISOString(),confirmed:true},cost_lines:['plate','color','domestic_freight','international_freight','other'].map(kind=>({key:kind,kind,name:kind,amount:0,currency:'USD',confirmed:true}))}
  if(i===0)input.cost_lines.push({key:'cny-inspection',kind:'custom',name:'Synthetic inspection RMB',amount:75,currency:'CNY',confirmed:true});const expected=await checked(sales.rpc('preview_quote_pricing_v2',{p_quote_id:candidate.id,p_input:input})),saved=await checked(sales.rpc('save_quote_pricing_v2',{p_request_id:randomUUID(),p_quote_id:candidate.id,p_input:input,p_expected:expected}));expect((await checked(sales.rpc('select_quote_atomic',{p_quote_id:saved.quote_id}))).success).toBe(true);chosen.push(saved.quote_id)
 }
 const oldPrice=await checked(admin.from('deal_quotes').select('selling_price_jpy,total_billing_tax_jpy').eq('id',quote).single());expect(oldPrice.selling_price_jpy).toBe(500);expect(oldPrice.total_billing_tax_jpy).toBe(1100)
 async function currentDocument(type:string){const id=randomUUID(),currentQuotes=await checked(admin.from('deal_quotes').select('*').eq('deal_id',deal).eq('status','approved')),products=await checked(admin.from('deal_products').select('*').eq('deal_id',deal)),variants=await checked(admin.from('deal_product_variants').select('*').in('product_id',[product,product2]));expect(currentQuotes).toHaveLength(2);await checked(admin.from('documents').insert({id,deal_id:deal,document_type:type,document_number:`SYNTH-REPRICE-${id}`,version:2,issued_at:new Date().toISOString(),issued_by_user_id:sessions.get('sales').user.id,metadata:{notes:frozenFxNote(currentQuotes),snapshot:{...snapshot,quotes:currentQuotes,products,variants},payment_due_date:'2026-10-31'}}));return id}
 const newQuoteDoc=await currentDocument('quotation');await page.reload();await page.getByLabel('発行済み見積書・請求書').selectOption(newQuoteDoc);await page.getByLabel('再見積の理由').fill('Synthetic changed quantity and factory price');await page.getByLabel('発注前の再見積であり、旧請求の着金引継ぎを顧客に再確認する').check();await page.getByRole('button',{name:'顧客向け内容を確認',exact:true}).click();await page.getByRole('button',{name:'この発行版を共有する',exact:true}).click();await expect.poll(async()=>(await checked(admin.from('client_document_packets').select('id').eq('document_id',newQuoteDoc))).length).toBe(1)
 const newQuote=(await checked(admin.from('client_document_packets').select('id,snapshot').eq('document_id',newQuoteDoc)))[0];expect(newQuote.snapshot.total).toBe('6600');expect(newQuote.snapshot.payment_carry_jpy).toBe('550')
 await role('client');await page.goto(`/portal/documents/${invoice.packet_id}`);await expect(page.getByText('価格・条件を再確認中です。',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'入金を申告する'})).toHaveCount(0)
 await page.goto(`/portal/documents/${newQuote.id}`);await expect(page.getByText('差引着金 ¥550',{exact:false})).toBeVisible();await page.getByLabel('数量・仕様・新金額・支払条件・着金引継ぎを確認しました').check();await page.getByRole('button',{name:'この版を承認する',exact:true}).click();await expect(page.getByText('回答済み：承認・営業確認待ち')).toBeVisible()
 const newInvoiceDoc=await currentDocument('invoice');await role('sales');await page.goto(`/deals/${deal}/settlement`);const correction=page.locator('details').filter({hasText:'訂正・期限切れリンク・再送・返金記録'});await correction.locator('summary').click();await correction.getByLabel('対象の有効版').selectOption(invoice.packet_id);await correction.getByLabel('対応',{exact:true}).selectOption('reissue_priced_invoice');await correction.getByLabel('対応理由').fill('Synthetic new price approved; old funds allocated once');await correction.getByLabel('新しく発行した請求書').selectOption(newInvoiceDoc);await correction.getByRole('button',{name:'訂正版を確認',exact:true}).click();await expect(correction.getByText('¥6,600 税込',{exact:true})).toBeVisible();await correction.getByLabel('顧客の新価格承認と差引着金の一度だけの引継ぎ・差額未収を確認した').check();await correction.getByRole('button',{name:'着金を引継いで再承認済み請求へ差替える'}).click();await expect.poll(async()=>(await checked(admin.from('client_document_packets').select('id').eq('document_id',newInvoiceDoc))).length).toBe(1)
 const newInvoice=(await checked(admin.from('client_document_packets').select('id').eq('document_id',newInvoiceDoc)))[0],finalContext=await checked(customer.rpc('client_finance_context',{p_packet_id:newInvoice.id}));expect(finalContext.snapshot.total).toBe('6600');expect(finalContext.confirmed_jpy).toBe('550');expect(finalContext.paid_in_full).toBe(false);expect(finalContext.snapshot.lines).toHaveLength(2);expect((await checked(admin.from('client_payment_receipts').select('packet_id').eq('packet_id',invoice.packet_id)))).toHaveLength(1);expect((await checked(admin.from('client_document_packets').select('status').eq('id',invoice.packet_id).single())).status).toBe('superseded')
 await role('client');await page.goto(`/portal/documents/${newInvoice.id}`);await expect(page.getByText('未収 ¥6,050',{exact:false})).toBeVisible();await mkdir('artifacts/release-final-audit',{recursive:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.getByText('前回の保存結果を確認中です…',{exact:true})).toHaveCount(0);await page.screenshot({path:'artifacts/release-final-audit/client-new-invoice-390.png'})
 await page.goto('/portal/documents');await page.getByRole('combobox').selectOption('active');await expect(page.locator('article')).toHaveCount(2);await page.getByRole('combobox').selectOption('superseded');await expect(page.locator('article')).toHaveCount(2);await expect(page.locator('article').first()).toContainText('履歴閲覧のみ');
 await role('sales');await page.goto(`/deals/${deal}/settlement`);await page.getByText('共有版のPDF・メール送付',{exact:true}).click();await page.getByRole('button',{name:'メール内容を確認',exact:true}).first().click();const mail=page.getByRole('region',{name:'メール送信前確認'});await expect(mail).toContainText('未収 ¥6,050');await mail.getByRole('button',{name:'確認した宛先へPDFを送付する'}).click();await expect(mail).toContainText('メールサービス受付済み');const sent=await checked(admin.from('client_document_mail_receipts').select('provider_id').eq('packet_id',newInvoice.id).single()),captured=await(await fetch(`http://127.0.0.1:55324/api/v1/message/${sent.provider_id}`)).json();expect(captured.To[0].Address).toBe('settlement-customer@example.test');expect(captured.Text).toContain('6,600');expect(captured.Text).toContain('550');expect(captured.Text).toContain('6,050');expect(captured.Text).toContain('2026-10-31');const pdf=await context.request.get(`/api/client-documents/${newInvoice.id}/pdf`),attachment=Buffer.from(await(await fetch(`http://127.0.0.1:55324/api/v1/message/${sent.provider_id}/part/${captured.Attachments[0].PartID}`)).arrayBuffer());expect(attachment.equals(await pdf.body())).toBe(true);await writeFile('tmp/pdfs/client-repriced-invoice.pdf',attachment)
 for(const name of ['foreign','factory','logistics']){await role(name);expect((await clients.get(name)!.rpc('preview_client_price_reissue',{p_packet_id:invoice.packet_id,p_document_id:newInvoiceDoc,p_approval_packet_id:newQuote.id})).error).not.toBeNull()}
})
