import {test,expect} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {mkdir} from 'node:fs/promises'
const url=process.env.LOCAL_SUPABASE_URL!
if(url!=='http://127.0.0.1:55321')throw Error('Synthetic localhost only')
const admin=createClient(url,process.env.LOCAL_SUPABASE_SERVICE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
test('real PO → factory final terms → staff bank agreement/transfer → factory receipt → production start',async({page,context})=>{
 const checked=async(r:PromiseLike<any>)=>{const v=await r;if(v.error)throw Error(v.error.message);return v.data}
 const factory=randomUUID(),otherFactory=randomUUID(),customer=randomUUID(),deal=randomUUID(),product=randomUUID(),variant=randomUUID(),quote=randomUUID(),sessions=new Map<string,any>(),clients=new Map<string,typeof admin>()
 await checked(admin.from('factories').insert([{id:factory,factory_name:'Synthetic production factory',bank_info:{raw:'Synthetic registered bank / dummy account 0000000'},basic_info_completed:true},{id:otherFactory,factory_name:'Synthetic unrelated factory',basic_info_completed:true}]))
 await checked(admin.from('clients').insert({id:customer,company_name:'Synthetic production customer'}))
 for(const role of ['sales','factory','foreign','client','logistics']){const email=`production-${role}-${randomUUID()}@example.test`,password=randomUUID()+randomUUID(),u=await checked(admin.auth.admin.createUser({email,password,email_confirm:true}));await checked(admin.from('profiles').update({role:role==='foreign'?'factory':role,factory_id:role==='factory'?factory:role==='foreign'?otherFactory:null,client_id:role==='client'?customer:null}).eq('id',u.user.id));const db=createClient(url,process.env.LOCAL_SUPABASE_ANON_KEY!,{auth:{persistSession:false,autoRefreshToken:false}}),login=await checked(db.auth.signInWithPassword({email,password}));sessions.set(role,login.session);clients.set(role,db)}
 await checked(admin.from('deals').insert({id:deal,deal_code:`PRD-${deal.slice(0,8)}`,deal_name:'Synthetic production workflow',client_id:customer,client_name_text:'Synthetic production customer',sales_user_id:sessions.get('sales').user.id,simple_status:'data_confirmed',waiting_on:'us'}))
 await checked(admin.from('deal_products').insert({id:product,deal_id:deal,product_no:1,description:'Synthetic production product'}));await checked(admin.from('deal_product_variants').insert({id:variant,product_id:product,variant_label:'Synthetic specification',variant_order:0}))
 await checked(admin.from('deal_quotes').insert({id:quote,deal_id:deal,variant_id:variant,factory_id:factory,status:'approved',quantity:100,factory_unit_price_usd:1,selling_price_jpy:300,total_billing_jpy:30000,total_billing_tax_jpy:33000,exchange_rate:150,cost_ratio:0.5}))
 const sales=clients.get('sales')!,order=(await checked(sales.rpc('create_factory_order_atomic',{p_quote_id:quote,p_factory_id:factory,p_order_no:`SYNTH-PO-${randomUUID()}`}))).orderId
 await context.route('**/*',route=>['127.0.0.1','localhost'].includes(new URL(route.request().url()).hostname)?route.continue():route.abort())
 const role=async(name:string)=>{await context.clearCookies();await context.addCookies([{name:'sb-127-auth-token',value:'base64-'+Buffer.from(JSON.stringify(sessions.get(name))).toString('base64url'),domain:'127.0.0.1',path:'/'}])}
 await role('factory');await page.goto(`/factory/orders/${order}`);await page.getByRole('combobox',{name:'支払方法',exact:true}).selectOption('partial_prepaid');await page.getByLabel('製造前に必要な着金額（USD・後払は0を明示）').fill('50');await page.getByRole('combobox',{name:'残金の支払時期',exact:true}).selectOption('before_shipment');await page.getByLabel('製造に必要な日数（暦日）').fill('20');await page.getByLabel('条件・確認事項').fill('Synthetic factory terms');await page.getByRole('button',{name:'この最終条件を営業へ提示する'}).click();await expect(page.getByText('営業確認待ち条件 第1版')).toBeVisible()
 await role('sales');await page.goto(`/deals/${deal}/production?order=${order}`);await page.getByLabel('銀行登録元を照合した根拠（工場には非公開）').fill('Synthetic registration original and verification');await page.getByLabel('取引条件への同意根拠').fill('Synthetic agreed half upfront and remainder before shipment');await expect(page.getByRole('button',{name:'この条件と銀行確認を記録する'})).toBeDisabled();await page.getByLabel('登録銀行の原文・出所を照合した').check();await page.getByRole('button',{name:'この条件と銀行確認を記録する'}).click();await expect(page.getByText('合意済み条件 第1版')).toBeVisible()
 await page.getByLabel('実施した送金額（USD）').fill('50');await page.getByLabel('送金実施日').fill('2026-10-01');await page.getByLabel('送金証跡の一意な番号').fill(`SYNTH-${randomUUID()}`);await page.getByLabel('実際に手動送金を実施し証跡を確認した').check();await page.getByRole('button',{name:'送金実施を記録する'}).click();await expect(page.getByRole('status').filter({hasText:'送金実施の記録を保存しました'})).toBeVisible()
 const report=(await checked(admin.from('factory_transfer_reports').select('*').eq('order_id',order)))[0];expect(await checked(admin.from('factory_production_starts').select('*').eq('order_id',order))).toHaveLength(0)
 await role('factory');await page.goto(`/factory/orders/${order}`);await expect(page.getByRole('button',{name:'製造開始を記録する'})).toBeDisabled();await mkdir('artifacts/factory-production-stage5',{recursive:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'artifacts/factory-production-stage5/factory-before-receipt-390.png'})
 await page.getByRole('combobox',{name:'営業の送金記録',exact:true}).selectOption(report.id);await page.getByLabel('銀行で確認した着金額（USD）').fill('50');await page.getByLabel('銀行着金日').fill('2026-10-01');await page.getByLabel('着金明細の一意な番号').fill(`SYNTH-BANK-${randomUUID()}`);await page.getByLabel('自社銀行明細で実際の着金を確認した').check();await page.getByRole('button',{name:'銀行着金を確認して記録する'}).click();await expect(page.getByRole('status').filter({hasText:'工場の着金確認を保存しました'})).toBeVisible()
 await page.getByLabel('実際の製造開始日').fill('2026-10-01');await page.getByLabel('開始の確認根拠').fill('Synthetic actual manufacturing start');await page.getByRole('button',{name:'製造開始を記録する'}).click();await expect(page.getByRole('status').filter({hasText:'工場の製造開始を記録しました'})).toBeVisible();await expect(page.getByText('製造完了予定 2026-10-21',{exact:false})).toBeVisible();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'artifacts/factory-production-stage5/factory-started-390.png'})
 await role('sales');await page.goto(`/deals/${deal}/production?order=${order}`);await page.getByRole('button',{name:'全工場の開始を確認して案件工程へ反映'}).click();await expect(page.getByText('案件への製造開始反映済みです。')).toBeVisible();expect((await checked(admin.from('deals').select('simple_status').eq('id',deal).single())).simple_status).toBe('in_production')
 for(const name of ['foreign','client','logistics']){expect((await clients.get(name)!.rpc('factory_order_context',{p_order_id:order})).error).not.toBeNull();expect((await clients.get(name)!.from('factory_final_terms').select('*').eq('order_id',order)).data).toEqual([])}
 expect((await clients.get('factory')!.from('factory_terms_agreements').select('*').eq('order_id',order)).data).toEqual([])
 const publicContext=await checked(clients.get('factory')!.rpc('factory_order_context',{p_order_id:order}));expect(publicContext.agreement.bank_evidence).toBeUndefined();expect(publicContext.agreement.note).toBeUndefined()
 await role('sales');await page.goto(`/deals/${deal}/production?order=${randomUUID()}`);await expect(page.getByRole('alert').filter({hasText:'指定の発注はこの案件に属していません'})).toBeVisible();await expect(page.getByRole('button',{name:'送金実施を記録する'})).toHaveCount(0)
})
