import {test,expect} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {mkdir,writeFile} from 'node:fs/promises'
const url=process.env.LOCAL_SUPABASE_URL!
if(url!=='http://127.0.0.1:55321')throw Error('Synthetic localhost only')
const admin=createClient(url,process.env.LOCAL_SUPABASE_SERVICE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
test('real partial QC 40 then 100 → three shipments 20/20/60 → partial customer receipt → delivery PDF/Mailpit',async({page,context})=>{
 const checked=async(r:PromiseLike<any>)=>{const v=await r;if(v.error)throw Error(v.error.message);return v.data}
 const factory=randomUUID(),otherFactory=randomUUID(),customer=randomUUID(),deal=randomUUID(),product=randomUUID(),variant=randomUUID(),quote=randomUUID(),sessions=new Map<string,any>(),clients=new Map<string,typeof admin>()
 await checked(admin.from('factories').insert([{id:factory,factory_name:'Synthetic production factory',bank_info:{raw:'Synthetic registered bank / dummy account 0000000'},basic_info_completed:true},{id:otherFactory,factory_name:'Synthetic unrelated factory',basic_info_completed:true}]))
 await checked(admin.from('clients').insert({id:customer,company_name:'Synthetic production customer',email:'shipment-customer@example.test',default_delivery_address:'Synthetic customer default address'}))
 for(const role of ['sales','factory','foreign','client','logistics','otherLogistics','otherClient']){const email=`production-${role}-${randomUUID()}@example.test`,password=randomUUID()+randomUUID(),u=await checked(admin.auth.admin.createUser({email,password,email_confirm:true}));await checked(admin.from('profiles').update({role:role==='foreign'?'factory':role==='otherLogistics'?'logistics':role==='otherClient'?'client':role,factory_id:role==='factory'?factory:role==='foreign'?otherFactory:null,client_id:role==='client'?customer:null}).eq('id',u.user.id));const db=createClient(url,process.env.LOCAL_SUPABASE_ANON_KEY!,{auth:{persistSession:false,autoRefreshToken:false}}),login=await checked(db.auth.signInWithPassword({email,password}));sessions.set(role,login.session);clients.set(role,db)}
 await checked(admin.from('deals').insert({id:deal,deal_code:`PRD-${deal.slice(0,8)}`,deal_name:'Synthetic production workflow',client_id:customer,client_name_text:'Synthetic production customer',sales_user_id:sessions.get('sales').user.id,simple_status:'data_confirmed',waiting_on:'us'}))
 await checked(admin.from('deal_products').insert({id:product,deal_id:deal,product_no:1,description:'Synthetic production product',shipping_address_full:'Synthetic saved product destination',shipping_recipient_name:'Synthetic recipient',shipping_phone:'000000000'}));await checked(admin.from('deal_product_variants').insert({id:variant,product_id:product,variant_label:'Synthetic specification',variant_order:0}))
 await checked(admin.from('deal_quotes').insert({id:quote,deal_id:deal,variant_id:variant,factory_id:factory,status:'approved',quantity:100,factory_unit_price_usd:1,selling_price_jpy:300,total_billing_jpy:30000,total_billing_tax_jpy:33000,exchange_rate:150,cost_ratio:0.5}))
 const partner=randomUUID();await checked(admin.from('logistics_partners').insert({id:partner,partner_kind:'shipping',company_name:'Synthetic Haiyuan logistics',contact_email:'shipment-logistics@example.test',is_active:true}));const settings=await checked(admin.from('system_settings').select('id').limit(1));if(settings.length)await checked(admin.from('system_settings').update({company_info_phase1:{name:'Synthetic BAO issuer',address:'Synthetic issuer address'}}).eq('id',settings[0].id));else await checked(admin.from('system_settings').insert({company_info_phase1:{name:'Synthetic BAO issuer',address:'Synthetic issuer address'}}));const sales=clients.get('sales')!,order=(await checked(sales.rpc('create_factory_order_atomic',{p_quote_id:quote,p_factory_id:factory,p_order_no:`SYNTH-PO-${randomUUID()}`}))).orderId
 await context.route('**/*',route=>['127.0.0.1','localhost'].includes(new URL(route.request().url()).hostname)?route.continue():route.abort())
 const role=async(name:string)=>{await context.clearCookies();await context.addCookies([{name:'sb-127-auth-token',value:'base64-'+Buffer.from(JSON.stringify(sessions.get(name))).toString('base64url'),domain:'127.0.0.1',path:'/'}])}
 await role('factory');await page.goto(`/factory/orders/${order}`);await page.getByRole('combobox',{name:'支払方法',exact:true}).selectOption('partial_prepaid');await page.getByLabel('製造前に必要な着金額（USD・後払は0を明示）').fill('50');await page.getByRole('combobox',{name:'残金の支払時期',exact:true}).selectOption('before_shipment');await page.getByLabel('製造に必要な日数（暦日）').fill('20');await page.getByLabel('条件・確認事項').fill('Synthetic factory terms');await page.getByRole('button',{name:'この最終条件を営業へ提示する'}).click();await expect(page.getByText('営業確認待ち条件 第1版')).toBeVisible()
 await role('sales');await page.goto(`/deals/${deal}/production?order=${order}`);await page.getByLabel('銀行登録元を照合した根拠（工場には非公開）').fill('Synthetic registration original and verification');await page.getByLabel('取引条件への同意根拠').fill('Synthetic agreed half upfront and remainder before shipment');await expect(page.getByRole('button',{name:'この条件と銀行確認を記録する'})).toBeDisabled();await page.getByLabel('登録銀行の原文・出所を照合した').check();await page.getByRole('button',{name:'この条件と銀行確認を記録する'}).click();await expect(page.getByText('合意済み条件 第1版')).toBeVisible()
 await page.getByLabel('実施した送金額（USD）').fill('50');await page.getByLabel('送金実施日').fill('2026-10-01');await page.getByLabel('送金証跡の一意な番号').fill(`SYNTH-${randomUUID()}`);await page.getByLabel('実際に手動送金を実施し証跡を確認した').check();await page.getByRole('button',{name:'送金実施を記録する'}).click();await expect(page.getByRole('status').filter({hasText:'送金実施の記録を保存しました'})).toBeVisible()
 const report=(await checked(admin.from('factory_transfer_reports').select('*').eq('order_id',order)))[0];expect(await checked(admin.from('factory_production_starts').select('*').eq('order_id',order))).toHaveLength(0)
 await role('factory');await page.goto(`/factory/orders/${order}`);await expect(page.getByRole('button',{name:'製造開始を記録する'})).toBeDisabled();await mkdir('artifacts/partial-qc-stage9/preconditions',{recursive:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'artifacts/partial-qc-stage9/preconditions/factory-before-receipt-390.png'})
 await page.getByRole('combobox',{name:'営業の送金記録',exact:true}).selectOption(report.id);await page.getByLabel('銀行で確認した着金額（USD）').fill('50');await page.getByLabel('銀行着金日').fill('2026-10-01');await page.getByLabel('着金明細の一意な番号').fill(`SYNTH-BANK-${randomUUID()}`);await page.getByLabel('自社銀行明細で実際の着金を確認した').check();await page.getByRole('button',{name:'銀行着金を確認して記録する'}).click();await expect(page.getByRole('status').filter({hasText:'工場の着金確認を保存しました'})).toBeVisible()
 await page.getByLabel('実際の製造開始日').fill('2026-10-01');await page.getByLabel('開始の確認根拠').fill('Synthetic actual manufacturing start');await page.getByRole('button',{name:'製造開始を記録する'}).click();await expect(page.getByRole('status').filter({hasText:'工場の製造開始を記録しました'})).toBeVisible();await expect(page.getByRole('region',{name:'製造期限・QC・出荷条件'})).toContainText('2026-10-21');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'artifacts/partial-qc-stage9/preconditions/factory-started-390.png'})
 await role('sales');await page.goto(`/deals/${deal}/production?order=${order}`);await page.getByText('工場条件・支払・製造開始の記録',{exact:true}).click();await page.getByRole('button',{name:'全工場の開始を確認して案件工程へ反映'}).click();await expect(page.getByText('案件への製造開始反映済みです。')).toBeVisible();expect((await checked(admin.from('deals').select('simple_status').eq('id',deal).single())).simple_status).toBe('in_production')
 for(const name of ['foreign','client','logistics']){expect((await clients.get(name)!.rpc('factory_order_context',{p_order_id:order})).error).not.toBeNull();expect((await clients.get(name)!.from('factory_final_terms').select('*').eq('order_id',order)).data).toEqual([])}
 expect((await clients.get('factory')!.from('factory_terms_agreements').select('*').eq('order_id',order)).data).toEqual([])
 const publicContext=await checked(clients.get('factory')!.rpc('factory_order_context',{p_order_id:order}));expect(publicContext.agreement.bank_evidence).toBeUndefined();expect(publicContext.agreement.note).toBeUndefined()
 await role('factory');await page.goto(`/factory/orders/${order}`)
 const png=Buffer.from(await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=32;canvas.height=32;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#D7EFFF';ctx.fillRect(0,0,32,32);ctx.fillStyle='#351E28';ctx.fillRect(8,8,16,16);return canvas.toDataURL('image/png').split(',')[1]}),'base64')
 const video=Buffer.from(await page.evaluate(async()=>{if(!MediaRecorder.isTypeSupported('video/mp4'))throw Error('Local Chrome MP4 recorder unavailable');const c=document.createElement('canvas');c.width=32;c.height=32;const ctx=c.getContext('2d')!;ctx.fillStyle='#D7EFFF';ctx.fillRect(0,0,32,32);const stream=c.captureStream(4),recorder=new MediaRecorder(stream,{mimeType:'video/mp4'}),parts:Blob[]=[];recorder.ondataavailable=e=>parts.push(e.data);const done=new Promise<void>(r=>{recorder.onstop=()=>r()});recorder.start();await new Promise(r=>setTimeout(r,350));recorder.stop();await done;stream.getTracks().forEach(t=>t.stop());return Array.from(new Uint8Array(await new Blob(parts).arrayBuffer()))}))
 const upload=async(kind:string,bytes:Buffer)=>{const count=await page.getByText('証跡を別画面で確認',{exact:true}).count();const summary=page.getByText('写真・動画を追加（非公開）',{exact:true});const details=summary.locator('..');if(await details.getAttribute('open')===null)await summary.click();await page.getByRole('combobox',{name:'証跡の種類',exact:true}).selectOption(kind);await page.getByLabel('証跡ファイル（PNG/JPEG/MP4・50MiB以下）').setInputFiles({name:`synthetic.${kind==='video'?'mp4':'png'}`,mimeType:kind==='video'?'video/mp4':'image/png',buffer:bytes});await page.getByRole('button',{name:'この証跡を保存する'}).click();await expect(page.getByText('証跡を別画面で確認',{exact:true})).toHaveCount(count+1);await expect(page.getByRole('status').filter({hasText:'証跡を保存しました'})).toBeVisible()}
 await upload('overall_photo',png);await upload('packing_photo',png);await upload('video',video)
 const assets=await checked(admin.from('factory_qc_assets').select('*').eq('order_id',order));expect(assets).toHaveLength(3)
 for(const id of assets.map((a:any)=>a.id)){const own=await context.request.get(`/api/factory-qc-assets/${id}`);expect(own.status()).toBe(200)}
 await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>v.videoWidth)).toBeGreaterThan(0)
 const submit=async(quantity='40')=>{for(const cb of await page.getByLabel('この提出版に使用する',{exact:true}).all())await cb.check();await page.getByLabel('実際の累計完工数量（発注 100個まで）').fill(quantity);await page.getByLabel('実際の完工日').fill('2026-10-01');await page.getByLabel('完工・修正内容').fill('Synthetic full order QC evidence');await page.getByLabel('累計完工数量と選択した3種類の証跡を確認した').check();await page.getByRole('button',{name:'この完工版を提出する'}).click();await expect(page.getByText('BAO QC判断待ち',{exact:true})).toBeVisible()}
 await submit();await mkdir('artifacts/partial-qc-stage9/preconditions',{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'artifacts/partial-qc-stage9/preconditions/factory-pending-390.png'})
 await role('sales');await page.goto(`/deals/${deal}/production?order=${order}`);await page.getByRole('combobox',{name:'QC判断',exact:true}).selectOption('rejected');await page.getByLabel('判断根拠・修正指示').fill('Synthetic packing proof correction');await page.getByLabel('最新提出版の数量・全体写真・梱包写真・動画を確認した').check();await page.getByRole('button',{name:'この版のQC判断を保存する'}).click();await expect(page.getByText('BAO QC不承認・修正待ち',{exact:true})).toBeVisible()
 expect((await sales.rpc('set_deal_simple_status',{p_deal_id:deal,p_to:'shipped',p_note:'Synthetic prohibited shipment',p_expected:'in_production'})).error).not.toBeNull()
 await role('factory');await page.goto(`/factory/orders/${order}`);const revisedPng=Buffer.from(await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=32;canvas.height=32;const g=canvas.getContext('2d')!;g.fillStyle='#E9F056';g.fillRect(0,0,32,32);return canvas.toDataURL('image/png').split(',')[1]}),'base64');await upload('packing_photo',revisedPng);await submit()
 await role('sales');await page.goto(`/deals/${deal}/production?order=${order}`);await page.getByLabel('判断根拠・修正指示').fill('Synthetic revised evidence verified');await page.getByLabel('最新提出版の数量・全体写真・梱包写真・動画を確認した').check();await page.getByRole('button',{name:'この版のQC判断を保存する'}).click();await expect(page.getByText('必要な残金の工場着金確認待ち',{exact:false})).toBeVisible()
 expect((await sales.rpc('set_deal_simple_status',{p_deal_id:deal,p_to:'shipped',p_note:'Synthetic unpaid balance',p_expected:'in_production'})).error).not.toBeNull()
 const balanceReport=await checked(sales.rpc('factory_workflow_command',{p_request_id:randomUUID(),p_order_id:order,p_operation:'report_transfer',p_input:{amount_usd:'50',sent_on:'2026-10-01',reference:`SYNTH-BALANCE-${randomUUID()}`,sent_confirmed:true}}));await checked(clients.get('factory')!.rpc('factory_workflow_command',{p_request_id:randomUUID(),p_order_id:order,p_operation:'ack_receipt',p_input:{report_id:balanceReport.report_id,amount_usd:'50',received_on:'2026-10-01',bank_reference:`SYNTH-BALANCE-BANK-${randomUUID()}`,bank_confirmed:true}}))
 await page.reload();await expect(page.getByText('承認済み 40個の支払条件確認済み・発送手配へ',{exact:false})).toBeVisible();// Stage7 must record actual dispatch first.
 expect((await sales.rpc('set_deal_simple_status',{p_deal_id:deal,p_to:'shipped',p_note:'Synthetic bypass before plan',p_expected:'in_production'})).error).not.toBeNull();expect((await sales.rpc('set_deal_simple_status',{p_deal_id:deal,p_to:'delivered',p_note:'Synthetic completion before plan',p_expected:'in_production'})).error).not.toBeNull();
 await page.goto(`/deals/${deal}/shipping?order=${order}`);await expect(page.getByRole('heading',{name:'発送・物流・顧客受領',exact:true})).toBeVisible()
 await page.getByLabel('今回発送する数量',{exact:true}).fill('20');await page.getByLabel('登録配送業者',{exact:true}).selectOption(partner);await page.getByLabel('確認済み物流担当アカウント',{exact:true}).selectOption(sessions.get('logistics').user.id);await page.getByLabel('食品検査・届出条件',{exact:true}).selectOption('true');await page.getByLabel('食品条件の確認根拠',{exact:true}).fill('Synthetic food test report and import notice');await page.getByLabel('確認済み中国受取住所',{exact:true}).fill('Synthetic verified China destination');await page.getByLabel('中国住所の出典・確認担当',{exact:true}).fill('Synthetic logistics document / verified assigned actor');await page.getByLabel('数量・配送方法・食品条件・中国受取先・納品先・担当者を確認した',{exact:true}).check();await page.getByRole('button',{name:'この固定版で発送計画を保存する'}).click();await expect(page.getByText('次の対応：工場：工場から中国国内発送',{exact:true})).toBeVisible()
 const ship=await checked(admin.from('shipment_plans').select('*').eq('order_id',order).single());expect(ship.snapshot.destination_address).toBe('Synthetic saved product destination')
 expect((await sales.rpc('set_deal_simple_status',{p_deal_id:deal,p_to:'shipped',p_note:'Synthetic premature dispatch',p_expected:'in_production'})).error).not.toBeNull()
 const stamp=async()=>await page.evaluate(()=>{const d=new Date(),pad=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}${d.getSeconds()?':'+pad(d.getSeconds()):''}`})
 const milestone=async(rejectFuture=false)=>{const before=(await checked(admin.from('shipment_milestones').select('id').eq('plan_id',ship.id))).length;await page.getByLabel('実際の発生時刻（端末の現地時刻）',{exact:true}).fill(rejectFuture?'2099-01-01T12:00':await stamp());await page.getByLabel('追跡番号・便識別子',{exact:true}).fill('SYNTH-TRACK-001');await page.getByLabel('確認した情報源・書類番号',{exact:true}).fill('Synthetic carrier notice');await page.getByLabel('受領・輸送・検査の確認内容',{exact:true}).fill('Synthetic actual milestone evidence');await page.getByLabel('予定ではなく実際の事実と対象数量を確認した',{exact:true}).check();await page.getByRole('button',{name:'この実輸送状態を記録する'}).click();if(rejectFuture){await expect(page.getByRole('alert').filter({hasText:'入力を訂正して保存できます'})).toBeVisible();expect((await checked(admin.from('shipment_milestones').select('id').eq('plan_id',ship.id))).length).toBe(before);return}await expect.poll(async()=>(await checked(admin.from('shipment_milestones').select('id').eq('plan_id',ship.id))).length).toBe(before+1);await page.reload()}
 await role('factory');await page.goto(`/factory/orders/${order}/shipping`);await milestone(true);await milestone();await expect(page.getByText('次の対応：担当物流：中国物流拠点で受領',{exact:true})).toBeVisible()

 const raceInput={...ship.snapshot,quantity:'20',partner_id:ship.partner_id,logistics_actor_id:ship.logistics_actor_id,confirmed:true}
 const raced=await Promise.all([0,1].map(()=>sales.rpc('shipment_command',{p_request_id:randomUUID(),p_order_id:order,p_operation:'prepare',p_input:raceInput})));expect(raced.filter(r=>!r.error)).toHaveLength(1);expect(raced.find(r=>r.error)!.error!.message).toContain('Allocation exceeds QC approved cumulative quantity');const extraPlan=raced.find(r=>!r.error)!.data.plan_id
 await checked(clients.get('factory')!.rpc('shipment_command',{p_request_id:randomUUID(),p_order_id:order,p_operation:'milestone',p_input:{plan_id:extraPlan,kind:'factory_dispatched',source:'Synthetic concurrent allocation dispatch',note:'Synthetic other approved 20 actual dispatch',tracking_number:'SYNTH-SPLIT-20B',occurred_at:new Date().toISOString(),confirmed:true}}))
 const secondInput={...ship.snapshot,quantity:'60',partner_id:ship.partner_id,logistics_actor_id:ship.logistics_actor_id,confirmed:true}
 expect((await sales.rpc('shipment_command',{p_request_id:randomUUID(),p_order_id:order,p_operation:'prepare',p_input:secondInput})).error).not.toBeNull()
 expect((await checked(clients.get('factory')!.rpc('factory_qc_context',{p_order_id:order}))).approved_quantity).toBe(40)
 await role('factory');await page.goto(`/factory/orders/${order}`);await expect(page.getByText('工場：残りの累計完工証跡を提出',{exact:false})).toBeVisible()
 const nextPng=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=32;c.height=32;const g=c.getContext('2d')!;g.fillStyle='#351E28';g.fillRect(0,0,32,32);return c.toDataURL('image/png').split(',')[1]}),'base64');await upload('packing_photo',nextPng);await submit('100')
 await role('sales');await page.goto(`/deals/${deal}/production?order=${order}`);await page.getByRole('combobox',{name:'QC判断',exact:true}).selectOption('rejected');await page.getByLabel('不承認の影響範囲').selectOption('new_quantity');await page.getByLabel('判断根拠・修正指示').fill('Synthetic second batch packing correction; previous approved quantity verified unaffected');await page.getByLabel('最新提出版の数量・全体写真・梱包写真・動画を確認した').check();await page.getByRole('button',{name:'この版のQC判断を保存する'}).click()
 await expect(page.getByText('BAO QC不承認・修正待ち',{exact:true})).toBeVisible();expect((await checked(sales.rpc('factory_qc_context',{p_order_id:order}))).approved_quantity).toBe(40)
 expect((await sales.rpc('shipment_command',{p_request_id:randomUUID(),p_order_id:order,p_operation:'prepare',p_input:secondInput})).error).not.toBeNull()
 await role('factory');await page.goto(`/factory/orders/${order}`);const corrected=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=32;c.height=32;const g=c.getContext('2d')!;g.fillStyle='#D7EFFF';g.fillRect(0,0,32,32);g.fillStyle='#E9F056';g.fillRect(0,0,16,16);return c.toDataURL('image/png').split(',')[1]}),'base64');await upload('packing_photo',corrected);await submit('100')
 await role('sales');await page.goto(`/deals/${deal}/production?order=${order}`);await page.getByLabel('判断根拠・修正指示').fill('Synthetic second batch revised media checked');await page.getByLabel('最新提出版の数量・全体写真・梱包写真・動画を確認した').check();await page.getByRole('button',{name:'この版のQC判断を保存する'}).click();await expect.poll(async()=>(await checked(sales.rpc('factory_qc_context',{p_order_id:order}))).approved_quantity).toBe(100)
 const second=await checked(sales.rpc('shipment_command',{p_request_id:randomUUID(),p_order_id:order,p_operation:'prepare',p_input:secondInput}));const plans=await checked(admin.from('shipment_plans').select('*').eq('order_id',order).order('quantity'));expect(plans.map((p:any)=>p.quantity)).toEqual([20,20,60])
 const command=(db:typeof admin,operation:string,input:unknown)=>checked(db.rpc('shipment_command',{p_request_id:randomUUID(),p_order_id:order,p_operation:operation,p_input:input}))
 await command(clients.get('factory')!,'milestone',{plan_id:second.plan_id,kind:'factory_dispatched',source:'Synthetic dispatch confirmation',note:'Synthetic second batch actual dispatch',tracking_number:'SYNTH-SPLIT-60',occurred_at:new Date().toISOString(),confirmed:true});await command(sales,'advance_shipped',{plan_id:ship.id});expect((await checked(admin.from('deals').select('simple_status').eq('id',deal).single())).simple_status).toBe('shipped')
 for(const p of plans){for(const kind of ['china_received','inspection_ready','inspection_cleared','international_departed','japan_arrived','out_for_delivery','carrier_delivered'])await command(clients.get('logistics')!,'milestone',{plan_id:p.id,kind,source:'Synthetic carrier and inspection report',note:'Synthetic actual split milestone',tracking_number:`SYNTH-SPLIT-${p.quantity}`,occurred_at:new Date().toISOString(),confirmed:true})}
 const documents=[]
 for(const p of plans){const display=await checked(clients.get('client')!.rpc('shipment_context',{p_order_id:order})),planLabel=`第${display.plans.findIndex((v:any)=>v.id===p.id)+1}便 ${p.quantity}個`;await role('client');await page.goto(`/portal/shipments/${order}`);await page.getByRole('button',{name:planLabel}).click();await expect(page.getByText(`顧客実受領 0 / ${p.quantity}個`,{exact:true})).toBeVisible()
 for(const quantity of p.quantity===20?[10,10]:[60]){await page.getByLabel('今回受領した数量',{exact:true}).fill(String(quantity));await page.getByLabel('実受領日',{exact:true}).fill('2026-10-01');await page.getByLabel('受領確認・不足の内容',{exact:true}).fill('Synthetic split actual customer receipt');await page.getByLabel('自社で実際に受領した数量を確認した',{exact:true}).check();await page.getByRole('button',{name:'今回の実受領を記録する'}).click();await expect(page.getByRole('status').filter({hasText:'実受領を記録しました'})).toBeVisible();await page.reload();await page.getByRole('button',{name:planLabel}).click()}
 await role('sales');await page.goto(`/deals/${deal}/shipping?order=${order}`);await page.getByRole('button',{name:planLabel}).click();await page.getByRole('button',{name:'顧客受領版の納品書を発行する'}).click();await expect(page.getByRole('link',{name:/納品書 .* PDFを開く/})).toBeVisible();const d=await checked(admin.from('shipment_delivery_documents').select('*').eq('plan_id',p.id).single());documents.push(d);const pdf=await context.request.get(`/api/delivery-notes/${d.id}/pdf`);expect(pdf.status()).toBe(200);const bytes=await pdf.body();await mkdir('tmp/pdfs',{recursive:true});await writeFile(`tmp/pdfs/stage9-delivery-${p.quantity}-${p.id}.pdf`,bytes);await page.getByRole('button',{name:'納品書メールの送付内容を確認する'}).click();await page.getByRole('button',{name:'確認した宛先へ送信する'}).click();await expect(page.getByRole('status').filter({hasText:'メール送信受付'})).toBeVisible()
 const sent=await checked(admin.from('shipment_mail_receipts').select('*').eq('event_key',p.id+':delivery').single()),capture=await(await fetch(`http://127.0.0.1:55324/api/v1/message/${sent.provider_id}`)).json();expect(capture.To[0].Address).toBe('shipment-customer@example.test');expect(capture.Text).toContain(`${p.quantity}個`);const attached=Buffer.from(await(await fetch(`http://127.0.0.1:55324/api/v1/message/${sent.provider_id}/part/${capture.Attachments[0].PartID}`)).arrayBuffer());expect(attached.equals(bytes)).toBe(true)
 if(p.quantity===20)expect((await sales.rpc('shipment_command',{p_request_id:randomUUID(),p_order_id:order,p_operation:'advance_delivered',p_input:{plan_id:p.id}})).error).not.toBeNull()
 }
 await page.getByRole('button',{name:'全受領・納品書を確認して案件完了'}).click();await expect.poll(async()=>(await checked(admin.from('deals').select('simple_status').eq('id',deal).single())).simple_status).toBe('delivered');await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'artifacts/partial-qc-stage9/staff-split-complete-390.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 for(const name of ['foreign','otherLogistics','otherClient']){await role(name);expect((await clients.get(name)!.rpc('shipment_context',{p_order_id:order})).error).not.toBeNull();for(const d of documents)expect((await context.request.get(`/api/delivery-notes/${d.id}/pdf`)).status()).toBe(404)}
})
