import {test,expect} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {mkdir,writeFile} from 'node:fs/promises'
const url=process.env.LOCAL_SUPABASE_URL!
if(url!=='http://127.0.0.1:55321')throw Error('Synthetic localhost only')
const admin=createClient(url,process.env.LOCAL_SUPABASE_SERVICE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
test('real samples: rounds/costs/payment → batch invoice/PDF/Mailpit → cancel/reissue/role isolation',async({page,context})=>{
 const sessions=new Map<string,any>(),clients=new Map<string,typeof admin>()
 const client=randomUUID(),factory=randomUUID(),deal=randomUUID(),product=randomUUID(),variant=randomUUID(),product2=randomUUID(),variant2=randomUUID()
 const checked=async(r:PromiseLike<any>)=>{const v=await r;if(v.error)throw Error(v.error.message);return v.data}
 await checked(admin.from('clients').insert({id:client,company_name:'Synthetic sample customer',email:'sample-client@example.test'}))
 await checked(admin.from('factories').insert({id:factory,factory_name:'Synthetic sample factory',basic_info_completed:true,contact_email:'factory@example.test'}))
 const settings=await checked(admin.from('system_settings').select('id').limit(1).maybeSingle()),issuer={name:'Synthetic sample issuer',address:'Synthetic address',registration_number:'T0000000000000'}
 await checked(settings?admin.from('system_settings').update({company_info_phase1:issuer}).eq('id',settings.id):admin.from('system_settings').insert({company_info_phase1:issuer}))
 for(const role of ['sales','client','factory','logistics']){
  const email=`sample-${role}-${randomUUID()}@example.test`,password=randomUUID()+randomUUID(),u=await checked(admin.auth.admin.createUser({email,password,email_confirm:true}))
  await checked(admin.from('profiles').update({role,client_id:role==='client'?client:null,factory_id:role==='factory'?factory:null}).eq('id',u.user.id))
  const db=createClient(url,process.env.LOCAL_SUPABASE_ANON_KEY!,{auth:{persistSession:false,autoRefreshToken:false}}),logged=await checked(db.auth.signInWithPassword({email,password}));sessions.set(role,logged.session);clients.set(role,db)
 }
 await checked(admin.from('deals').insert({id:deal,deal_code:`SYN-${deal.slice(0,8)}`,deal_name:'Synthetic sample workflow',client_id:client,client_name_text:'Synthetic sample customer',sales_user_id:sessions.get('sales').user.id,simple_status:'quoting',waiting_on:'us'}))
 await checked(admin.from('deal_products').insert({id:product,deal_id:deal,product_no:1,description:'Synthetic pouch'}))
 await checked(admin.from('deal_product_variants').insert({id:variant,product_id:product,variant_label:'Synthetic 100g',variant_order:0}))
 await checked(admin.from('deal_products').insert({id:product2,deal_id:deal,product_no:2,description:'Synthetic second product'}));await checked(admin.from('deal_product_variants').insert({id:variant2,product_id:product2,variant_label:'Synthetic second variant',variant_order:0}))
 await context.route('**/*',route=>['127.0.0.1','localhost'].includes(new URL(route.request().url()).hostname)?route.continue():route.abort())
 const role=async(name:string)=>{await context.clearCookies();await context.addCookies([{name:'sb-127-auth-token',value:'base64-'+Buffer.from(JSON.stringify(sessions.get(name))).toString('base64url'),domain:'127.0.0.1',path:'/'}])}
 await role('sales');await page.goto(`/deals/${deal}/samples`);await expect(page.getByRole('heading',{name:'サンプル手配・費用請求',exact:true})).toBeVisible()
 const createRound=async(lostResponse=false)=>{await page.getByRole('button',{name:'次のサンプルを手配記録',exact:true}).click();await page.getByRole('combobox',{name:'対象仕様',exact:true}).selectOption(lostResponse?variant2:variant);await page.getByRole('combobox',{name:'担当工場',exact:true}).selectOption(factory);await page.getByLabel('サンプル数量（個）',{exact:true}).fill('2');await page.getByLabel('希望期限',{exact:true}).fill('2026-10-20');await page.getByLabel('手配内容・修正内容',{exact:true}).fill('Synthetic request');let resolve!:()=>void;const lost=new Promise<void>(r=>resolve=r);if(lostResponse)await page.route('**/*',async route=>{if(route.request().method()==='POST'&&route.request().headers()['next-action']){await route.fetch();await route.abort('failed');resolve()}else await route.fallback()});await page.getByRole('button',{name:'この内容を記録',exact:true}).click();if(lostResponse){await lost;await page.unroute('**/*');const stored=await page.evaluate(()=>Object.entries(sessionStorage).filter(([k])=>k.startsWith('baoflow-request:')).map(([,v])=>JSON.parse(v)));expect(stored).toHaveLength(1);expect(Object.keys(stored[0]).sort()).toEqual(['id','signature']);await page.reload();await expect(page.getByRole('status').filter({hasText:'前回の保存を確認しました'})).toBeVisible();await page.getByRole('button',{name:'保存済み記録を確認した',exact:true}).click()}else await expect(page.getByRole('status').filter({hasText:'記録を保存しました'})).toBeVisible()}
 await createRound();await createRound(true);expect(await checked(admin.from('sample_rounds').select('id').eq('deal_id',deal))).toHaveLength(2)
 const addCost=async(index:number,shipping=false)=>{await page.getByRole('button',{name:'確定費用を記録',exact:true}).nth(index).click();await page.getByRole('combobox',{name:'費目',exact:true}).selectOption(shipping?'shipping':'manufacturing');if(shipping)await page.getByRole('combobox',{name:'配送会社（送料の場合のみ）',exact:true}).selectOption('FedEx');await page.getByLabel('概算額（未記録なら空欄）',{exact:true}).fill('1700');await page.getByLabel('確定実費（0も明示）',{exact:true}).fill('1500');await page.getByLabel('顧客負担額（税抜円・0も明示）',{exact:true}).fill('750');await page.getByLabel('実費・負担額の確認根拠',{exact:true}).fill('Synthetic actual expense and half customer share');await page.getByLabel('概算ではなく、実費・顧客負担額を確認しました',{exact:true}).check();await page.getByRole('button',{name:'この内容を記録',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'記録を保存しました'})).toBeVisible()}
 await page.getByRole('button',{name:'概算費用を記録',exact:true}).first().click();await page.getByLabel('概算額（0も明示）',{exact:true}).fill('1700');await page.getByLabel('概算費用の根拠',{exact:true}).fill('Synthetic estimate before expense');await page.getByRole('button',{name:'この内容を記録',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'記録を保存しました'})).toBeVisible();expect(await checked(admin.from('sample_costs').select('id'))).not.toBeNull();
 await addCost(0);await addCost(1,true)
 await page.getByRole('button',{name:'工場への支払を記録',exact:true}).first().click();await page.getByLabel('実施した支払額',{exact:true}).fill('20');await page.getByLabel('支払日',{exact:true}).fill('2026-10-01');await page.getByLabel('支払証跡・参照番号',{exact:true}).fill('Synthetic payment evidence');await page.getByRole('button',{name:'この内容を記録',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'記録を保存しました'})).toBeVisible()
 await expect(page.getByRole('button',{name:'次のサンプルを手配記録',exact:true})).toBeEnabled();await page.getByLabel('サンプル・工場・費目を検索',{exact:true}).fill('no-synthetic-match');await expect(page.getByRole('status').filter({hasText:'検索条件に合う記録はありません'})).toBeVisible();await page.getByLabel('サンプル・工場・費目を検索',{exact:true}).fill('');await mkdir('artifacts/sample-stage12',{recursive:true});await page.setViewportSize({width:1366,height:900});await page.screenshot({path:'artifacts/sample-stage12/rounds-1366.png',fullPage:false});await page.setViewportSize({width:390,height:844});await expect(page.locator('summary').filter({hasText:'メニューを開く / 閉じる'})).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'artifacts/sample-stage12/rounds-390.png',fullPage:false})
 await page.getByRole('button',{name:'未請求費用 2件',exact:true}).click();for(const cb of await page.locator('label').filter({hasText:'顧客負担 ¥750'}).getByRole('checkbox').all())await cb.check()
 await page.getByLabel('消費税率（%・0も明示）',{exact:true}).fill('10');await page.getByLabel('請求発行日',{exact:true}).fill('2026-10-01');await page.getByLabel('支払期限',{exact:true}).fill('2026-10-31');await page.getByLabel('請求書に記載する振込案内',{exact:true}).fill('Synthetic payment details')
 await page.getByRole('button',{name:'選択した費用の請求を確認',exact:true}).click();await expect(page.getByRole('heading',{name:'請求確定前の確認'})).toBeVisible();expect(await checked(admin.from('sample_invoices').select('id').eq('deal_id',deal))).toHaveLength(0);await page.screenshot({path:'artifacts/sample-stage12/invoice-confirm-390.png',fullPage:false})
 await page.getByRole('button',{name:'この内容で請求書を確定',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'請求書を確定しました'})).toBeVisible();await page.getByRole('button',{name:'請求書履歴',exact:true}).click()
 const invoice=(await checked(admin.from('sample_invoices').select('*').eq('deal_id',deal)))[0];expect(invoice.snapshot.subtotal).toBe('1500');expect(invoice.snapshot.total).toBe('1650');expect(invoice.snapshot.lines.map((l:any)=>l.round_number)).toEqual([1,2]);expect(invoice.snapshot.lines[1].carrier).toBe('FedEx')
 const pdf=await context.request.get(`/api/sample-invoices/${invoice.id}/pdf`);expect(pdf.status()).toBe(200);const bytes=await pdf.body();expect(bytes.subarray(0,5).toString()).toBe('%PDF-');await mkdir('tmp/pdfs',{recursive:true});await writeFile('tmp/pdfs/sample-invoice.pdf',bytes)
 await page.getByRole('button',{name:'送付文面・添付を確認',exact:true}).click();const mail=page.getByRole('region',{name:'サンプル請求メールプレビュー'});await expect(mail).toContainText('sample-client@example.test');await page.getByRole('button',{name:'この宛先へPDF添付を送信',exact:true}).click();await expect(mail).toContainText('メールサービス受付済み（到達は未確認）')
 const receipt=await checked(admin.from('sample_mail_receipts').select('*').eq('invoice_id',invoice.id).single());expect(receipt.status).toBe('accepted');const captured=await(await fetch(`http://127.0.0.1:55324/api/v1/message/${receipt.provider_id}`)).json();expect(captured.To[0].Address).toBe('sample-client@example.test');expect(captured.Text).toContain('1,650');expect(captured.Text).toContain('2026-10-31');expect(captured.Subject).toContain(invoice.document_number)
 const a=captured.Attachments[0],attached=Buffer.from(await(await fetch(`http://127.0.0.1:55324/api/v1/message/${receipt.provider_id}/part/${a.PartID}`)).arrayBuffer());expect(attached.equals(bytes)).toBe(true)
 await page.reload();await page.getByRole('button',{name:'請求書履歴',exact:true}).click();await expect(page.getByText('発行済み・メール受付済み（到達未確認）',{exact:false})).toBeVisible();await page.getByRole('button',{name:'送付文面・添付を確認',exact:true}).click();await expect(page.getByRole('button',{name:'この宛先へPDF添付を送信',exact:true})).toHaveCount(0)
 await page.getByText('理由を記録して取消',{exact:true}).click();await page.getByLabel('取消理由',{exact:true}).fill('Synthetic correction after customer agreement');await page.getByRole('button',{name:'取消を確定',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'取消を記録しました'})).toBeVisible()
 for(const name of ['client','factory','logistics']){const db=clients.get(name)!;const denied=await db.rpc('sample_command',{p_request_id:randomUUID(),p_deal_id:deal,p_operation:'create_round',p_input:{},p_expected:null});expect(denied.error).not.toBeNull();expect(await checked(db.from('sample_rounds').select('id').eq('deal_id',deal))).toHaveLength(0);await role(name);expect((await context.request.get(`/api/sample-invoices/${invoice.id}/pdf`)).status()).toBe(name==='client'?200:404);if(name==='client'){const own=await checked(db.rpc('client_sample_invoices',{}));expect(own).toHaveLength(1);expect(own[0].snapshot.lines[0].cost_id).toBeUndefined();await page.goto('/portal/samples');await expect(page.getByText('取消済み・履歴用',{exact:true})).toBeVisible();await page.screenshot({path:'artifacts/sample-stage12/client-own-sample-390.png',fullPage:false})}}
 await role('sales');const sales=clients.get('sales')!,input={cost_ids:invoice.snapshot.lines.map((l:any)=>l.cost_id),tax_rate:'10',issue_date:'2026-10-01',due_date:'2026-10-31',payment_details:'Synthetic payment details',previous_invoice_id:invoice.id};const p=await checked(sales.rpc('preview_sample_invoice',{p_deal_id:deal,p_input:input}));await checked(sales.rpc('sample_command',{p_request_id:randomUUID(),p_deal_id:deal,p_operation:'issue_invoice',p_input:input,p_expected:p}));expect(await checked(admin.from('sample_invoices').select('id').eq('deal_id',deal))).toHaveLength(2)
 const rounds=await checked(sales.from('sample_rounds').select('*').eq('deal_id',deal));const ri={product_id:product,variant_id:variant,factory_id:factory,quantity:2,due_date:'2026-10-20',note:'Synthetic concurrent order'};const parallel=await Promise.all([randomUUID(),randomUUID()].map(p_request_id=>sales.rpc('sample_command',{p_request_id,p_deal_id:deal,p_operation:'create_round',p_input:ri,p_expected:null})));expect(parallel.every(r=>!r.error)).toBe(true);expect(parallel.map(r=>r.data.round_number).sort()).toEqual([3,4]);
 const c=await checked(sales.rpc('sample_command',{p_request_id:randomUUID(),p_deal_id:deal,p_operation:'add_cost',p_input:{round_id:rounds[0].id,kind:'plate',carrier:null,amount:'10',currency:'JPY',customer_charge_jpy:'10',basis:'Synthetic race expense',confirmed:true},p_expected:null}));const raceInput={...input,cost_ids:[c.id],previous_invoice_id:''},racePreview=await checked(sales.rpc('preview_sample_invoice',{p_deal_id:deal,p_input:raceInput}));const race=await Promise.all([randomUUID(),randomUUID()].map(p_request_id=>sales.rpc('sample_command',{p_request_id,p_deal_id:deal,p_operation:'issue_invoice',p_input:raceInput,p_expected:racePreview})));expect(race.filter(r=>!r.error)).toHaveLength(1);expect(race.filter(r=>r.error)).toHaveLength(1)
 await checked(admin.from('deal_samples').insert({deal_id:deal,round_number:1,sample_production_fee_usd:12,sample_shipping_fee_usd:3,subtotal_jpy:1234,sample_status:'requested'}));await page.goto(`/deals/${deal}/samples`);await page.getByText('旧サンプル記録 1件（請求状態未確認）',{exact:true}).click();await expect(page.getByText('保存済み円小計 ¥1,234',{exact:false})).toBeVisible();
 console.log('PASS real synthetic sample ledger/PDF/Mailpit/cancellation/reissue/role isolation and 390px overflow check')
})
