-- Local candidate. No legacy backfill; new explicit export plans are separate from warehouse inbound.
create table shipment_plans(id uuid primary key default gen_random_uuid(),order_id uuid not null references factory_purchase_orders(id),deal_id uuid not null references deals(id),client_id uuid not null references clients(id),factory_id uuid not null references factories(id),quantity integer not null check(quantity>0),logistics_actor_id uuid not null references profiles(id),partner_id uuid not null references logistics_partners(id),snapshot jsonb not null,created_by uuid not null references profiles(id),created_at timestamptz not null default now());
create index shipment_plan_order on shipment_plans(order_id);
create table shipment_milestones(id uuid primary key default gen_random_uuid(),plan_id uuid not null references shipment_plans(id),kind text not null check(kind in('factory_dispatched','china_received','inspection_ready','inspection_cleared','international_departed','japan_arrived','out_for_delivery','carrier_delivered')),source text not null,note text not null,tracking_number text not null,occurred_at timestamptz not null,created_by uuid not null references profiles(id),created_at timestamptz not null default now(),unique(plan_id,kind));
create table shipment_customer_receipts(id uuid primary key default gen_random_uuid(),plan_id uuid not null references shipment_plans(id),quantity integer not null check(quantity>0),received_on date not null,note text not null,created_by uuid not null references profiles(id),created_at timestamptz not null default now());
create index shipment_receipt_plan on shipment_customer_receipts(plan_id);
create table shipment_delivery_documents(id uuid primary key default gen_random_uuid(),plan_id uuid not null unique references shipment_plans(id),document_number text not null unique,snapshot jsonb not null,created_by uuid not null references profiles(id),created_at timestamptz not null default now());
create table shipment_workflow_requests(id uuid primary key,order_id uuid not null references factory_purchase_orders(id),created_by uuid not null references profiles(id),operation text not null,payload jsonb not null,result jsonb not null,created_at timestamptz not null default now());
create table shipment_mail_receipts(id uuid primary key default gen_random_uuid(),plan_id uuid not null references shipment_plans(id),event_key text not null unique,payload jsonb not null,status text not null check(status in('reserved','accepted','unknown','rejected')),provider_id text,created_by uuid not null references profiles(id),created_at timestamptz not null default now(),finished_at timestamptz);
do $$declare t text;begin foreach t in array array['shipment_plans','shipment_milestones','shipment_customer_receipts','shipment_delivery_documents','shipment_workflow_requests','shipment_mail_receipts'] loop
 execute format('alter table %I enable row level security',t);execute format('revoke all on %I from public,anon,authenticated',t);execute format('grant select on %I to authenticated',t);
 execute format('create policy staff_read on %I for select to authenticated using((select is_staff())%s)',t,case when t='shipment_workflow_requests' then ' and created_by=(select auth.uid())' else '' end);
 if t<>'shipment_mail_receipts' then execute format('create trigger shipment_history_immutable before update or delete on %I for each row execute function keep_factory_workflow_history()',t);end if;
 end loop;
end$$;
create policy actor_request_read on shipment_workflow_requests for select to authenticated using(created_by=(select auth.uid()));
create function shipment_order_role(oid uuid) returns text language plpgsql security definer set search_path=public,pg_temp as $$declare p profiles;o factory_purchase_orders;cid uuid;begin
 if auth.uid() is null then raise exception 'Authenticated shipment account required';end if;select * into p from profiles where id=auth.uid();select * into o from factory_purchase_orders where id=oid;if not found then raise exception 'Shipment order unavailable';end if;select client_id into cid from deals where id=o.deal_id;
 if is_staff() then return 'staff';elsif p.role::text='factory' and p.factory_id=o.factory_id then return 'factory';elsif p.role::text='client' and p.client_id=cid then return 'client';elsif p.role::text='logistics' and exists(select 1 from shipment_plans where order_id=oid and logistics_actor_id=p.id) then return 'logistics';end if;raise exception 'Shipment order unavailable';end$$;
revoke all on function shipment_order_role(uuid) from public,anon,authenticated;
create function shipment_context(p_order_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare actor text;o factory_purchase_orders;plans jsonb;options jsonb;product jsonb;begin
 actor=shipment_order_role(p_order_id);select * into o from factory_purchase_orders where id=p_order_id;
 select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'quantity',p.quantity,'created_at',p.created_at,'snapshot',case when actor='client' then p.snapshot-'china_address'-'china_source'-'logistics_actor_id' when actor='factory' then p.snapshot-'destination_address'-'recipient'-'phone'-'customer_name'-'logistics_actor_id' else p.snapshot end,'events',(select coalesce(jsonb_agg(case when actor='client' then jsonb_build_object('id',e.id,'kind',e.kind,'occurred_at',e.occurred_at,'tracking_number',e.tracking_number) else to_jsonb(e)-'created_by' end order by array_position(array['factory_dispatched','china_received','inspection_ready','inspection_cleared','international_departed','japan_arrived','out_for_delivery','carrier_delivered'],e.kind)),'[]') from shipment_milestones e where e.plan_id=p.id),'received_quantity',(select coalesce(sum(quantity),0) from shipment_customer_receipts where plan_id=p.id),'receipts',case when actor in('staff','client') then (select coalesce(jsonb_agg(to_jsonb(r)-'created_by'),'[]') from shipment_customer_receipts r where r.plan_id=p.id) else '[]'::jsonb end,'document',case when actor in('staff','client') then (select jsonb_build_object('id',d.id,'number',d.document_number,'mail_status',(select status from shipment_mail_receipts mr where mr.event_key=p.id::text||':delivery')) from shipment_delivery_documents d where d.plan_id=p.id) else null end) order by p.created_at),'[]') into plans from shipment_plans p where p.order_id=o.id and (actor<>'logistics' or p.logistics_actor_id=auth.uid()) and (actor<>'client' or p.client_id=(select client_id from profiles where id=auth.uid()));
 if actor='staff' then
 select jsonb_build_object('partners',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',company_name,'address',address)),'[]') from logistics_partners where is_active and partner_kind='shipping'),'actors',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',coalesce(display_name,'物流担当')||' / '||left(id::text,8))),'[]') from profiles where role::text='logistics'),'customer_default',(select default_delivery_address from clients c join deals d on d.client_id=c.id where d.id=o.deal_id)) into options;
 select jsonb_build_object('address',p.shipping_address_full,'recipient',p.shipping_recipient_name,'phone',p.shipping_phone) into product from deal_products p join deal_product_variants v on v.product_id=p.id where v.id=(o.snapshot->>'variant_id')::uuid;
 end if;
 return jsonb_build_object('actor',actor,'deal_status',(select simple_status from deals where id=o.deal_id),'order',jsonb_build_object('id',o.id,'deal_id',o.deal_id,'number',o.order_no,'quantity',o.quantity,'item_name',o.snapshot->>'item_name'),'ship_ready',factory_order_ship_ready(o.id),'plans',plans,'options',options,'saved_destination',product,'tracking_integration',false,'today',current_date);
end$$;
create function shipment_command(p_request_id uuid,p_order_id uuid,p_operation text,p_input jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor text;o factory_purchase_orders;p shipment_plans;old shipment_workflow_requests;result jsonb;rid uuid;kind text;last shipment_milestones;expected text;address text;partner logistics_partners;cid uuid;qty integer;received integer;stamp timestamptz;issuer jsonb;document shipment_delivery_documents;begin
 actor=shipment_order_role(p_order_id);perform pg_advisory_xact_lock(hashtextextended('shipment-order:'||p_order_id::text,0));perform pg_advisory_xact_lock(hashtextextended('shipment-request:'||p_request_id::text,0));
 select * into old from shipment_workflow_requests where id=p_request_id;if found then if old.created_by<>auth.uid() or old.order_id<>p_order_id or old.operation<>p_operation or old.payload<>p_input then raise exception 'Shipment retry input changed';end if;return old.result;end if;
 select * into o from factory_purchase_orders where id=p_order_id;perform id from deals where id=o.deal_id for update;select client_id into cid from deals where id=o.deal_id and archived_at is null;if cid is null or o.status<>'ordered' then raise exception 'Active company order required';end if;
 if p_operation='prepare' then
 if actor<>'staff' or not factory_order_ship_ready(o.id) or not exists(select 1 from deals where id=o.deal_id and simple_status::text='in_production') then raise exception 'Staff active manufacturing with verified QC and payment conditions required';end if;
 if coalesce(p_input->>'confirmed','false')<>'true' or coalesce(p_input->>'quantity','')!~'^[1-9][0-9]*$' or coalesce(p_input->>'method','') not in('sea','air') or coalesce(p_input->>'food_required','') not in('true','false') or coalesce(p_input->>'destination_source','') not in('saved_product','customer_default','manual') then raise exception 'Explicit shipping method, food branch, destination and quantity required';end if;
 qty=(p_input->>'quantity')::integer;if qty+(select coalesce(sum(quantity),0) from shipment_plans where order_id=o.id)>o.quantity then raise exception 'Shipment quantity exceeds order';end if;
 select * into partner from logistics_partners where id=(p_input->>'partner_id')::uuid and partner_kind='shipping' and is_active;if not found then raise exception 'Active registered shipping partner required';end if;
 if not exists(select 1 from profiles where id=(p_input->>'logistics_actor_id')::uuid and role::text='logistics') then raise exception 'Existing verified logistics actor required';end if;
 foreach kind in array array['china_address','china_source','food_basis','destination_address','recipient','phone'] loop if nullif(btrim(p_input->>kind),'') is null or length(p_input->>kind)>2000 then raise exception 'Verified address and inspection sources required';end if;end loop;
 if p_input->>'destination_source'='saved_product' then select prod.shipping_address_full into address from deal_products prod join deal_product_variants v on v.product_id=prod.id where v.id=(o.snapshot->>'variant_id')::uuid;elsif p_input->>'destination_source'='customer_default' then select default_delivery_address into address from clients where id=cid;else address=p_input->>'destination_address';end if;
 if address is null or address is distinct from p_input->>'destination_address' then raise exception 'Saved destination changed; reverify';end if;
 insert into shipment_plans(order_id,deal_id,client_id,factory_id,quantity,logistics_actor_id,partner_id,snapshot,created_by) values(o.id,o.deal_id,cid,o.factory_id,qty,(p_input->>'logistics_actor_id')::uuid,partner.id,p_input||jsonb_build_object('partner_name',partner.company_name,'item_name',o.snapshot->>'item_name','customer_name',(select company_name from clients where id=cid),'tracking_integration',false),auth.uid()) returning id into rid;result=jsonb_build_object('plan_id',rid);
 else
 select * into p from shipment_plans where id=(p_input->>'plan_id')::uuid and order_id=o.id;if not found or (actor='logistics' and p.logistics_actor_id<>auth.uid()) or (actor='client' and p.client_id is distinct from (select client_id from profiles where id=auth.uid())) then raise exception 'Own shipment plan required';end if;
 select ev.* into last from shipment_milestones ev where ev.plan_id=p.id order by array_position(array['factory_dispatched','china_received','inspection_ready','inspection_cleared','international_departed','japan_arrived','out_for_delivery','carrier_delivered'],ev.kind) desc limit 1;
 if p_operation='milestone' then
 kind=p_input->>'kind';expected=case coalesce(last.kind,'') when '' then 'factory_dispatched' when 'factory_dispatched' then 'china_received' when 'china_received' then case when p.snapshot->>'food_required'='true' then 'inspection_ready' else 'international_departed' end when 'inspection_ready' then 'inspection_cleared' when 'inspection_cleared' then 'international_departed' when 'international_departed' then 'japan_arrived' when 'japan_arrived' then 'out_for_delivery' when 'out_for_delivery' then 'carrier_delivered' else '' end;
 if kind is distinct from expected or coalesce(p_input->>'confirmed','false')<>'true' or nullif(btrim(p_input->>'source'),'') is null or nullif(btrim(p_input->>'note'),'') is null or nullif(btrim(p_input->>'tracking_number'),'') is null or length(p_input->>'source')>500 or length(p_input->>'note')>2000 or length(p_input->>'tracking_number')>200 then raise exception 'Next actual milestone and evidence required';end if;
 if (kind='factory_dispatched' and actor<>'factory') or (kind<>'factory_dispatched' and (actor<>'logistics' or p.logistics_actor_id<>auth.uid())) then raise exception 'Factory dispatch or assigned logistics confirmation required';end if;
 if not factory_order_ship_ready(o.id) then raise exception 'QC and payment conditions required';end if;
 stamp=(p_input->>'occurred_at')::timestamptz;if stamp is null or stamp>now() or stamp<p.created_at or (last.id is not null and stamp<last.occurred_at) then raise exception 'Actual chronological milestone time required';end if;
 insert into shipment_milestones(plan_id,kind,source,note,tracking_number,occurred_at,created_by) values(p.id,kind,btrim(p_input->>'source'),btrim(p_input->>'note'),btrim(p_input->>'tracking_number'),stamp,auth.uid()) returning id into rid;result=jsonb_build_object('event_id',rid,'kind',kind);
 elsif p_operation='receive' then
 if actor<>'client' or last.kind is distinct from 'carrier_delivered' or coalesce(p_input->>'confirmed','false')<>'true' or coalesce(p_input->>'quantity','')!~'^[1-9][0-9]*$' or nullif(btrim(p_input->>'note'),'') is null or length(p_input->>'note')>2000 then raise exception 'Own client actual receipt after carrier delivery required';end if;
 qty=(p_input->>'quantity')::integer;select coalesce(sum(quantity),0) into received from shipment_customer_receipts where plan_id=p.id;
 if coalesce(p_input->>'expected_received','')!~'^(0|[1-9][0-9]*)$' or (p_input->>'expected_received')::integer<>received or qty+received>p.quantity or (p_input->>'received_on')::date>current_date or (p_input->>'received_on')::date<last.occurred_at::date then raise exception 'Current remaining receipt quantity and actual date required';end if;
 if nullif(p_input->>'received_on','') is null then raise exception 'Receipt date required';end if;
 insert into shipment_customer_receipts(plan_id,quantity,received_on,note,created_by) values(p.id,qty,(p_input->>'received_on')::date,btrim(p_input->>'note'),auth.uid()) returning id into rid;result=jsonb_build_object('receipt_id',rid,'received_quantity',received+qty,'fully_received',received+qty=p.quantity);
 elsif p_operation='issue_delivery' then
 if actor<>'staff' or (select coalesce(sum(quantity),0) from shipment_customer_receipts where plan_id=p.id)<>p.quantity then raise exception 'Staff and full customer receipt required';end if;
 select * into document from shipment_delivery_documents where plan_id=p.id;if found then result=jsonb_build_object('document_id',document.id);else
 select company_info_phase1 into issuer from system_settings limit 1;if nullif(btrim(issuer->>'name'),'') is null then raise exception 'Registered issuer required';end if;
 rid=gen_random_uuid();insert into shipment_delivery_documents(id,plan_id,document_number,snapshot,created_by) values(rid,p.id,'DLV-'||to_char(current_date,'YYYYMMDD')||'-'||upper(left(rid::text,8)),jsonb_build_object('plan_id',p.id,'client_id',p.client_id,'order_no',o.order_no,'customer_name',p.snapshot->>'customer_name','item_name',p.snapshot->>'item_name','quantity',p.quantity,'destination_address',p.snapshot->>'destination_address','recipient',p.snapshot->>'recipient','received_on',(select max(received_on) from shipment_customer_receipts where plan_id=p.id),'issued_at',now(),'issuer',issuer),auth.uid());result=jsonb_build_object('document_id',rid);end if;
 elsif p_operation='advance_shipped' or p_operation='advance_delivered' then
 if actor<>'staff' then raise exception 'Staff progression required';end if;
 if exists(select 1 from factory_purchase_orders x where x.deal_id=o.deal_id and x.status='ordered' and ((select coalesce(sum(quantity),0) from shipment_plans where order_id=x.id)<>x.quantity or exists(select 1 from shipment_plans sp where sp.order_id=x.id and not exists(select 1 from shipment_milestones ms where ms.plan_id=sp.id and ms.kind='factory_dispatched')))) then raise exception 'All order quantities must actually dispatch';end if;
 if p_operation='advance_delivered' and exists(select 1 from shipment_plans sp where sp.deal_id=o.deal_id and ((select coalesce(sum(quantity),0) from shipment_customer_receipts where plan_id=sp.id)<>sp.quantity or not exists(select 1 from shipment_delivery_documents where plan_id=sp.id) or not exists(select 1 from shipment_mail_receipts where event_key=sp.id::text||':delivery' and status='accepted'))) then raise exception 'All customer receipts, delivery documents and mail acceptance required';end if;
 perform set_deal_simple_status(o.deal_id,(case when p_operation='advance_shipped' then 'shipped' else 'delivered' end)::simple_status,'Verified shipment ledger',(case when p_operation='advance_shipped' then 'in_production' else 'shipped' end)::simple_status);result=jsonb_build_object('deal_status',case when p_operation='advance_shipped' then 'shipped' else 'delivered' end);
 else raise exception 'Unknown shipment operation';end if;
 end if;
 insert into shipment_workflow_requests values(p_request_id,o.id,auth.uid(),p_operation,p_input,result,now());return result;
end$$;
create function shipment_delivery_context(p_document_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare doc shipment_delivery_documents;plan shipment_plans;actor text;begin select * into doc from shipment_delivery_documents where id=p_document_id;if not found then raise exception 'Delivery document unavailable';end if;select * into plan from shipment_plans where id=doc.plan_id;actor=shipment_order_role(plan.order_id);if actor not in('staff','client') or (actor='client' and plan.client_id is distinct from (select client_id from profiles where id=auth.uid())) then raise exception 'Own client delivery document required';end if;return doc.snapshot||jsonb_build_object('number',doc.document_number);end$$;
revoke all on function shipment_context(uuid),shipment_command(uuid,uuid,text,jsonb),shipment_delivery_context(uuid) from public,anon;grant execute on function shipment_context(uuid),shipment_command(uuid,uuid,text,jsonb),shipment_delivery_context(uuid) to authenticated;
create function guard_shipment_customer_completion() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin
 if new.simple_status=old.simple_status or new.simple_status::text not in('shipped','delivered') or not exists(select 1 from factory_purchase_orders po join factory_production_starts ps on ps.order_id=po.id where po.deal_id=new.id and po.status='ordered') then return new;end if;
 if exists(select 1 from factory_purchase_orders o where o.deal_id=new.id and o.status='ordered' and ((select coalesce(sum(quantity),0) from shipment_plans where order_id=o.id)<>o.quantity or exists(select 1 from shipment_plans p where p.order_id=o.id and not exists(select 1 from shipment_milestones where plan_id=p.id and kind='factory_dispatched')))) then raise exception 'Actual dispatch of all quantities required';end if;
 if new.simple_status::text='delivered' and exists(select 1 from shipment_plans p where p.deal_id=new.id and ((select coalesce(sum(quantity),0) from shipment_customer_receipts where plan_id=p.id)<>p.quantity or not exists(select 1 from shipment_delivery_documents where plan_id=p.id) or not exists(select 1 from shipment_mail_receipts where event_key=p.id::text||':delivery' and status='accepted'))) then raise exception 'Actual full customer receipt, delivery document and mail acceptance required';end if;return new;
end$$;
revoke all on function guard_shipment_customer_completion() from public,anon,authenticated;
create trigger shipment_customer_completion before update of simple_status on deals for each row execute function guard_shipment_customer_completion();
create function claim_shipment_email(p_plan_id uuid,p_event_key text,p_payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare p shipment_plans;prior shipment_mail_receipts;aid uuid;begin
 if not is_staff() then raise exception 'Staff mail management required';end if;select * into p from shipment_plans where id=p_plan_id;if not found then raise exception 'Shipment unavailable';end if;
 if p_event_key<>'delivery' and not exists(select 1 from shipment_milestones where plan_id=p.id and id::text=p_event_key) then raise exception 'Current shipment event required';end if;
 if p_event_key='delivery' and not exists(select 1 from shipment_delivery_documents where plan_id=p.id) then raise exception 'Delivery document required';end if;
 perform pg_advisory_xact_lock(hashtextextended('shipment-email:'||p.id::text||':'||p_event_key,0));select * into prior from shipment_mail_receipts where event_key=p.id::text||':'||p_event_key;
 if found then return jsonb_build_object('claimed',false,'status',prior.status,'attempt_id',prior.id);end if;
 insert into shipment_mail_receipts(plan_id,event_key,payload,status,created_by) values(p.id,p.id::text||':'||p_event_key,p_payload,'reserved',auth.uid()) returning id into aid;return jsonb_build_object('claimed',true,'status','reserved','attempt_id',aid);
end$$;
create function finish_shipment_email(p_attempt_id uuid,p_status text,p_provider_id text) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$begin
 if not is_staff() or p_status not in('accepted','unknown','rejected') then raise exception 'Staff mail result required';end if;update shipment_mail_receipts set status=p_status,provider_id=p_provider_id,finished_at=now() where id=p_attempt_id and created_by=auth.uid() and status='reserved';return found;
end$$;
revoke all on function claim_shipment_email(uuid,text,jsonb),finish_shipment_email(uuid,text,text) from public,anon;grant execute on function claim_shipment_email(uuid,text,jsonb),finish_shipment_email(uuid,text,text) to authenticated;
create function my_shipment_orders() returns jsonb language sql security definer set search_path=public,pg_temp as $$
 select coalesce(jsonb_agg(jsonb_build_object('id',o.id,'number',o.order_no,'item_name',o.snapshot->>'item_name','quantity',o.quantity)),'[]') from factory_purchase_orders o where exists(select 1 from shipment_plans p join profiles u on u.id=auth.uid() where p.order_id=o.id and ((u.role::text='client' and u.client_id=p.client_id) or (u.role::text='logistics' and u.id=p.logistics_actor_id)))
$$;
revoke all on function my_shipment_orders() from public,anon;grant execute on function my_shipment_orders() to authenticated;
